### ISSUE TITLE
(ghostscript) Executable not in path

### ISSUE THREAD

**Issue by knorx** [chocolatey-community/chocolatey-packages#1330]
## Expected Behavior
After installation of the package ghostscript I have the corresponding executables in path.

## Current Behavior
Exceutable can only be run with absolute path.

## Possible Solution
Generate a shim during package installation using: https://chocolatey.org/docs/helpers-install-bin-file

## Steps to Reproduce (for bugs)
1. Install ghostscript package
2. type gswin64 in command line, it will not find any command.

## Your Environment
* Package Version used: 9.27
* Operating System and version: Win 10 (10.0.17763 Build 17763)
* Chocolatey version: 0.10.15
* Install/uninstall gist: `choco install ghostscript`

**Comment by majkinetor** [comment]
I am not sure shim would suffice as it uses some parameters which could always be changed upstream. Check out the link generated by installer:

![image](https://user-images.githubusercontent.com/85767/67193795-2d5bb500-f3f6-11e9-83ea-29ddceb67b50.png)

**Comment by musm** [comment]
I have the same issue, it seems it would be best to add the `gs/bin` folder to path system wide

**Comment by 29039** [comment]
I'm having this problem also, I need to be able to always run the latest version using gswin64c.exe without having to specify the exact path as this changes with each version

**Comment by Zethson** [comment]
Could this issue be reopened please?

**Comment by Destroy666x** [comment]
Bump, this is still very relevant and will keep coming back. Not good that an officially managed package with binaries isn't added to system path in any shape or form. Is any help needed to get this done?

@majkinetor @pauby @AdmiringWorm

**Comment by pauby** [comment]
Chocolatey Software doesn't manage packages so these are not 'officially managed'.

This packages on this repository are managed by the community. If you need this issue fixed, my suggestion would be to get involved and submit a PR with a fix.
