### ISSUE TITLE
(git) update options and include symbolic links

### ISSUE THREAD

**Issue by musm** [chocolatey-community/chocolatey-packages#1452]
Please  include the option to enable symbolic links.

![image](https://user-images.githubusercontent.com/4319522/77982969-ae8b7200-72db-11ea-95bd-e1a5bf6e23d9.png)

Also please include the option to change:

![image](https://user-images.githubusercontent.com/4319522/77982983-b64b1680-72db-11ea-88f0-03339edb3616.png)

**Comment by RedBaron2** [comment]
@majkinetor @AdmiringWorm @musm 
Does anyone know if the installer has this as a switch? I have found no switch or option of triggering this from the command line.
The few options mentioned elsewhere have been to add it into the config file (not good practice besides not allowed in core packages). The other options require registry edits that are not standard. The last option is to enable a script do the changes like @ferventcoder  whipped up for his own problem with these links.
Until an option as a switch is available this issue will require up stream help.

**Comment by AdmiringWorm** [comment]
> Does anyone know if the installer has this as a switch?

Unfortunately not, could be that it is possible through the use of `/TASKS` or `/COMPONENTS` argument.

> The other options require registry edits that are not standard.

This is kind of the approach used in the package already, but only for what would have been set by the `innosetup` installer to remember the tasks provided that they use for git.

**Comment by RedBaron2** [comment]
@AdmiringWorm @musm 
I'm going to check if this is even an option in the next few weeks.

I will also contact the developers about having this option made available outside of non-silent installations.

IMHO this would be a better option for the community.

**Comment by soredake** [comment]
Any progress on this?
