### ISSUE TITLE
(thunderbird) Install parameters

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-packages#1593]
We could provide some more install parameters for thunderbird via Ini file and install param `/INI=`.

```
[Install]
InstallDirectoryName=Mozilla Thunderbird
InstallDirectoryPath= ...
CloseAppNoPrompt=true
QuickLaunchShortcut=true
DesktopShortcut=false
StartMenuShortcuts=true
MaintenanceService=false
```

For more info: https://firefox-source-docs.mozilla.org/browser/installer/windows/installer/FullConfig.html

It also looks like silent install option `--ms` should be replaced with `/S`

Firefox package supplies those args via cmd line:

```
$sa += if ($pp.InstallDir) { " /InstallDirectoryPath=" + $pp.InstallDir }
$sa += if ($pp.NoTaskbarShortcut) { " /TaskbarShortcut=false" }
$sa += if ($pp.NoDesktopShortcut) { " /DesktopShortcut=false" }
$sa += if ($pp.NoStartMenuShortcut) { " /StartMenuShortcut=false" }
$sa += if ($pp.NoMaintenanceService) { " /MaintenanceService=false" }
$sa += if ($pp.RemoveDistributionDir) { " /RemoveDistributionDir=true" }
$sa += if ($pp.NoAutoUpdate) { " /MaintenanceService=false" }
```

Probably the best to reuse these.

**Comment by olifre** [comment]
This issue also affects us, notably, when using Chocolatey and configuration management, you'll likely also want to disable the integrated auto-updater, which may cause issues for non-admin accounts. 

Is there a way to reopen this issue in case you are not the reporter? Or do I need to report this again as a new issue if it still affects me?

**Comment by pauby** [comment]
As this hasn't had any traction @olifre can I suggest you look into it and submit a PR?

**Comment by olifre** [comment]
@pauby Thanks for reopening! 
It's already on my list of issues to look into, sadly my PS knowledge is quite limited and there are many other OpenSource projects which are biting us more and eating my time. So I may not get to it in the very recent future.

**Comment by pauby** [comment]
@olifre As this seems not be getting much traction it might be something we look to close again in the future if there are no PR's coming in. This is just an FYI as it appears to be something you need and may look to prioritise.

**Comment by olifre** [comment]
This issue is still relevant. I did not get to create a PR for it just yet.

**Comment by olifre** [comment]
This issue is still relevant. I did not get to create a PR for it just yet. Indeed, it is up for grabs, if somebody with more development time available comes by.
