### ISSUE TITLE
(1password) install appears to succeed, but program is not functional

### ISSUE THREAD

**Issue by jacktose** [chocolatey-community/chocolatey-packages#1618]
## Expected Behavior
`choco install 1password` should end with a functional install of 1Password.

## Current Behavior
`choco install 1password` appears to complete successfully (with a fair bit of stderr output).
1Password does not appear in Start menu, desktop, Apps & features, or Programs & features.
1Password files are present in `%LOCALAPPDATA%\1Password\`.

## Possible Solution
In #1186, an installer change broke choco installation and was fixed in #1516. I don't think this is exactly the same, because `-f --not-silent` is not an effective workaround.

## Steps to Reproduce (for bugs)
`choco install 1password`
or
`choco install --not-silent 1password` and click Yes at the prompt

## Context
I'm a new 1Password user and just want to install and use the program.

## Your Environment

* Package Version used: 7.6.791
* Operating System and version: Win 10 20H2 (19042.804)
* Chocolatey version: 0.10.15
* Install gist: https://gist.github.com/jacktose/065831a326913bc7d185797a8d573581

**Comment by alie2n** [comment]
I just came access the same issue. I can confirm that this problem exists on a brand new, fresh installed, Windows 10 20H1.
It seems, that the last step for the installation `%LOCALAPPDATA%\1Password\1Password.exe setup` should now be `%LOCALAPPDATA%\1Password\1Password.exe --silent`

**Comment by alie2n** [comment]
I'd really like to submit a PR, but I don't understand the logic how the executed command gets assembled. From what I gather from the install.ps1 and the update.ps1 the command should be correct. But for some reason it is not.

**Comment by michaelmhoffman** [comment]
I am having the same issue. Running `%LOCALAPPDATA%\1Password\1Password.exe --silent` runs 1Password, but it didn't seem to install it in the start menu, but `%LOCALAPPDATA%\1Password\1Password.exe setup` did.

**Comment by michaelmhoffman** [comment]
The current installer logic kills the installer after it finds "Installation completed successfully" in the log. Is it possible that this is no longer really enough to complete installation?

**Comment by AdmiringWorm** [comment]
It is very possible that it is no longer needed, or the installation completed is prematurely added to the log.

I am not a user of 1password myself, so need to leave this up to someone else to investigate.

**Comment by compuguy** [comment]
This is still an issue as of Nov 2023.
