### ISSUE TITLE
(spotify) Not installing correctly

### ISSUE THREAD

**Issue by tipek360** [chocolatey-community/chocolatey-packages#1620]
## Expected Behavior
Spotify was expected to installed.

## Current Behavior
Chocolatey downloads normal installer and than it stucks on "SUCCESS: The scheduled task "spotify" was successfully deleted."

## Possible Solution
Changing download link to [https://download.spotify.com/SpotifyFullSetup.exe](https://download.spotify.com/SpotifyFullSetup.exe)

## Steps to Reproduce (for bugs)
```
choco install spotify
```

## Context
Spotify was not installed

## Your Environment

* Package Version used: 1.1.53.608
* Operating System and version: Windows 10 Pro 20H2
* Chocolatey version: 0.10.15
* Install/uninstall gist: [https://gist.github.com/tipek360/34a25de8d637b8c0d3a00e850a49d333](https://gist.github.com/tipek360/34a25de8d637b8c0d3a00e850a49d333)

**Comment by AlexHeylin** [comment]
The code certainly has the possibility of this happening because it contains a loop that could easily become endless. 
@tipek360 what user context were you executing this in? User / Admin / SYSTEM / something else?

Bad things happen when running as SYSTEM, and I think they're all related to this issue. 

Does anyone know why this is using a scheduled task rather than just running ```SpotifySetup.exe /silent``` directly?

The scheduled task creation fails for SYSTEM, so Spotify can't install.  Then the script enters an endless loop waiting for Spotify to start so it can kill it.

**Comment by tipek360** [comment]
@AlexHeylin I don't know why original author of install script used loop which can become endless I thought that issues is just with online installer.

**Comment by AlexHeylin** [comment]
Thanks @tipek360 
What user context were you executing this in?

**Comment by tipek360** [comment]
Well when I install something using chocolatey I usually use powershell with admin privileges and if I know correctly chocolatey even doesn't let you install something without privileges if you don't allow it in configuration.

**Comment by tipek360** [comment]
But now I tried to install spotify using chocolatey in VM and it worked so this package is probably now fixed in chocolatey repository.

**Comment by TheCakeIsNaOH** [comment]
> Changing download link to https://download.spotify.com/SpotifyFullSetup.exe

The Chocolatey package moved away from using the full setup because it had an inconsistent checksum. Read this for more information: https://github.com/chocolatey-community/chocolatey-packages/issues/1273

**Comment by AlexHeylin** [comment]
I've fixed this, I just need to formally test it before I submit the PR. It's only changing a couple of lines - barely worth testing, but I will anyway.

Don't worry - changing the installer exe isn't going to solve this problem, and I won't do it but thanks for the reference @TheCakeIsNaOH
