### ISSUE TITLE
(avidemux) 2.7.8 upgrade is not silent

### ISSUE THREAD

**Issue by HunterZ** [chocolatey-community/chocolatey-packages#1627]
## Expected Behavior

Upgrade should occur without any need for user input.

## Current Behavior

A popup appears asking the user to specify/confirm installation location, and upgrade does not proceed until the user hits OK button.

## Possible Solution

Whatever it takes to keep the popup from appearing, or to dismiss it automatically.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Upgrade was stimulated by a `cup -y all` command in an elevated command prompt.

## Your Environment

* Package Version used: 2.7.8 (sorry, don't remember previous version - probably 2.7.6 since it's been out for a while)
* Operating System and version: Windows 10 x64 20H2
* Chocolatey version: v0.10.15
* Install/uninstall gist: I don't know what this means, but I probably can't get it for you at this point anyway.

**Comment by AdmiringWorm** [comment]
> Install/uninstall gist: I don't know what this means, but I probably can't get it for you at this point anyway.

A gist is a file that is uploaded to: https://gist.github.com/ (or embedded in the issue using code blocks, but the former is recommended).
It the context of this repository, that would mean the chocolatey logs for the process that was being run (in your case upgrade).

In this case, though, a gist is probably not needed.

Sounds like we may have to check if there is a previous version already installed, and either uninstall the program or run an AutoHotkey script to automate the clicking.
Marking this as an enhancement request for now.

**Comment by HunterZ** [comment]
This is still relevant.

Both `cup -y --force avidemux` (installs over current install) and `cinst -y --force avidemux` (uninstalls then reinstalls) still prompt the user for an install location and just sit there.

`cuninst -y avidemux` followed by `cinst -y avidemux` does NOT prompt the user.
