### ISSUE TITLE
Rename this repository to chocolatey-packages

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-packages#1633]
There have been talks of potentially renaming the repository to something other than `chocolatey-coreteampackages` repository.
The current name of `chocolatey-coreteampackages` sounds like it is part of chocolatey itself or one of the team members which is not the case.

The repository should be renamed to something else that reflects that the repository is completely maintained by the community and volunteers (hence the `chocolatey-community` organization), and not the Chocolatey organization or its team members.

One of the suggested changes is to change the name to one that is commonly used by other Chocolatey maintainers, and don't have the the `coreteam` in the name. i.e: `chocolatey-packages`.

Suggestions from other community members regarding both renaming the repository, and what it should be renamed to is appreciated.

**Comment by majkinetor** [comment]
Definitely.

However, I don't like current suggestions, its just too ordinary and doesn't properly convey significance of this repository over other similar repositories - first few gallery pages are almost exclusively from this repository and chocolatey user has multiple millions downloads, so its clearly different from other users.

Also, about chocolatey user! It should also get renamed as it doesn't have anything to do with chocolatey as a company and is community effort.

I think `chocolatey-community-packages` and `community` user are logical and meaningful names.

**Comment by gep13** [comment]
@majkinetor the user that is used to push the packages from this repository is called `chocolatey-community`, which I think conveys exactly what is meant to, no?

**Comment by majkinetor** [comment]
Where is it called like that ? I only see chocolatey: https://community.chocolatey.org/profiles/chocolatey

**Comment by gep13** [comment]
That user only has three packages, the official packages published by Chocolatey. This is the user that has the packages from this repository:

https://community.chocolatey.org/profiles/chocolatey-community

**Comment by majkinetor** [comment]
OK, it must have been already renamed/changed then without me noticing it...

**Comment by gep13** [comment]
Regarding the repository name, `chocolatey-community-packages` makes sense to me, the reason I didn't suggest something like that was due to the repo already being in the `chocolatey-community` organisation. So the full path would be `chocolatey-community/chocolatey-packages`.

I am not against the suggestion, just seems that `chocolatey-community/chocolatey-community-packages` duplicates part of the name.

Thoughts?

**Comment by AdmiringWorm** [comment]
> Definitely.
> 
> However, I don't like current suggestions, its just too ordinary and doesn't properly convey significance of this repository over other similar repositories - first few gallery pages are almost exclusively from this repository and chocolatey user has multiple millions downloads, so its clearly different from other users.
> 
> Also, about chocolatey user! It should also get renamed as it doesn't have anything to do with chocolatey as a company and is community effort.
> 
> I think `chocolatey-community-packages` and `community` user are logical and meaningful names.

It is supposed to be ordinary. What makes this repository different from other maintainer repositories is that multiple maintainers have access and can commit to the repository, and it aims to have high-quality packages (in other cases, it is more or less the same as other maintainer repositories).
Also, saying that the first few gallery pages are almost exclusively packages from this repository is just plain wrong. They have the majority, yes, but not even close to being **almost** exclusive. (around 27-28 packages are from the repository on the first two pages. Out of 60)

Also, having the name of the repository being `chocolatey-community-packages` is something I would be against on two counts.
1. The duplication of the word `community` as @gep13 mentioned
2. Higher likelihood of a user thinking this repository is the actual community repository and opening issues for other packages not hosted here (which we have already seen happen at times, and I believe will happen more frequently if changing it to that).

While yes, it will most likely cause users to open issues here regarding other packages if it gets renamed to `chocolatey-packages`, but I believe it will be less likely to happen due to it being a common name that multiple maintainers are using.
Not saying there isn't a better name, though.

**Comment by majkinetor** [comment]
If we talk about name duplication with parent namespace, then we should only go with `packages` as we already have chocolatey and community as words. 

> Also, saying that the first few gallery pages are almost exclusively packages from this repository  is just plain wrong.

OK, let me be pedantic - half of the packages. Most downloads. Not the typical repository for sure either by number of packages or by downloads or by anything. Claiming its the same as anything else is just plain wrong and even unrespectful. 

So how about just `packages` ?

**Comment by pauby** [comment]
`chocolatey-packages` gets my vote. It's a common name used for maintainers Chocolatey packages repositories.

**Comment by pauby** [comment]
Since there's been no update here in the last 7 days, can we get agreement on the name change and the next steps on this?

**Comment by AdmiringWorm** [comment]
IMO, I believe we can go ahead with the name change to `chocolatey-packages` (since most agreed with this name).
I am not sure how it would affect open pull requests, so we might want to spend some time getting those pulled in or rejected first though (I plan to do that this weekend).

**Comment by pauby** [comment]
It's important that everybody knows that this repository will be renamed. Please leave this issue pinned just now until the work is done.

**Comment by gep13** [comment]
Based on discussions, I plan on moving forward with renaming of this repository tomorrow, with the chosen name of `chocolatey-packages`.

> @AdmiringWorm said...
I am not sure how it would affect open pull requests, so we might want to spend some time getting those pulled in or rejected first though (I plan to do that this weekend).

I don't believe that this will cause any problems in this area.  There will be work required to ensure that all URL's are updated, that AppVeyor configuration is updated, etc. but I will take care of those things once the rename is complete.

**Comment by gep13** [comment]
I am going to mark this as closed, as I haven't heard any screams that this has broken anything, and new packages have been getting submitted to community.chocolatey.org

**Comment by mwallner** [comment]
maybe this changes should be reflected in https://github.com/chocolatey-community/chocolatey-packages#readme as well?
> Chocolatey Community **Core Team** Packages
