### ISSUE TITLE
(sourcetree) package is outdated

### ISSUE THREAD

**Issue by tipek360** [chocolatey-community/chocolatey-packages#1641]
I'm posting this also here because I was asked in email by @gep13 to create issue here so it can be tracked.
When I looked at sourcetree website a quickly foundout that chocolatey package is bit outdated version 3.4.1 but newest is 3.4.4

## Expected Behavior
`choco install sourcetree` installs recent v3.4.4

## Current Behavior
`choco install sourcetree` installs outdated v3.4.1

## Your Environment

* Package Version used: 3.4.1
* Operating System and version: Windows 10 Pro 20H2 Build 19042.906
* Chocolatey version: 0.10.15
* Install/uninstall gist:

**Comment by gep13** [comment]
@pascalberger is this something that you can take a look at?  Thanks

**Comment by RedBaron2** [comment]
@gep13 
The current logic of the update for this package uses internet explorer to read the website. This is because the site uses JavaScript to render the webpages. This is also detecting the operating system of the browser too.

Options
- Ask Sourcetree publisher of the could provide a API for chocolatey

- Ask Sourcetree publisher to take over the package

- Use other methods to parse the Sourcetree website

**Comment by pauby** [comment]
So we know the issues. @RedBaron2 are you able to look at this?

**Comment by RedBaron2** [comment]
@pauby 
I'll check other avenues of parsing the webpage and get back to you.

**Comment by Trellmor** [comment]
Still an issue, Sourcetree is now up to version 3.4.7 while the version in chocolatey is still 3.4.1

**Comment by RedBaron2** [comment]
@Trellmor 
I'm curious to found out if the version number has gone past 10 for the last digit (EX: X.X.10)?

@AdmiringWorm 
Working on a solution and waiting on a reply from **Trellmor**

**Comment by Trellmor** [comment]
Currently? No, the current version is [3.4.8](https://product-downloads.atlassian.com/software/sourcetree/windows/ga/SourceTreeSetup-3.4.8.exe) ([changelog](https://product-downloads.atlassian.com/software/sourcetree/windows/ga/ReleaseNotes_3.4.8.html))

There have been 2 digit version numbers in the past, e.g. [3.0.10 to 3.0.17](https://product-downloads.atlassian.com/software/sourcetree/windows/ga/ReleaseNotes_3.0.17.html)

**Comment by RedBaron2** [comment]
I'm still testing my fix for consistency, but it appears to be stable.

I will as time allows submit a PR for this package. @Trellmor thanks for the help.

**Comment by RedBaron2** [comment]
PR is up and hopefully will be approved soon. This update should work for the foreseeable future.

**Comment by pauby** [comment]
I've had a look at the PR and I'm wondering why this is so complicated? I'm coming to it fresh so forgive me missing anything.

Am I right in thinking that this is the [correct website for SourceTree](https://sourcetreeapp.com)? If that is the case the latest available version they offer is 3.4.7 both on the initial web page and also in their [archives](https://www.sourcetreeapp.com/download-archives). I saw the link above for 3.4.8 in the release notes.

If this is all correct, then it's a simple case of parsing the website / download archive page to get it?

`(iwr https://www.sourcetreeapp.com/ -UseBasicParsing).links.href -match 'sourcetreesetup'` is basic, but confirms it works.

If I'm missing something then apologies.

**Comment by pascalberger** [comment]
That's the complicated part with the Sourcetree package: Inconsistencies all over the place and documented release processes changing all the time 😞. It is basically impossible to get it right.

There are basically two versions of SourceTree:
- Personal
- Enterprise

This package installs Enterprise edition, since this is the version suitable for automated machine-wide deployments.

If you look in the [archive it says 3.4.7](https://www.sourcetreeapp.com/download-archives), but if you check the [download link at the SourceTree enterprise page](https://sourcetreeapp.com/enterprise) it points to 3.4.8.

**Comment by pascalberger** [comment]
Also they once documented the release process with `Alpha -> Blitz -> Beta -> Early Access -> GA` stages (See [Blog post](https://blog.sourcetreeapp.com/2016/03/31/sourcetree-beta-program-a-look-behind-the-curtains/)), but they didn't stick to it, which also caused confusion in the past.

**Comment by meek2100** [comment]
Take a look at these two PRs they should solve the source tree automatic updates.

https://github.com/chocolatey-community/chocolatey-packages/pull/1853
https://github.com/chocolatey-community/chocolatey-packages/pull/1854

**Comment by RedBaron2** [comment]
@meek2100 
There is currently a PR that will resolve this issue #1833

**Comment by pauby** [comment]
The previous PR has been closed without merging. I've put this issue up for grabs.

**Comment by umol-unibas** [comment]
Hi there, would be great if you would take a look at the open PR solving this issue: 
[Sourcetree new update script #2162 ](https://github.com/chocolatey-community/chocolatey-packages/pull/2162)
Thanks!

**Comment by corbob** [comment]
@umol-unibas I've assigned this to you, and adjusted the labels on this issue. This should stop it from automatically closing. 

I can't say when someone might be able to review the PR as they're typically reviewed by community volunteers in their free time, but I will try to take a look at it this week if my free time permits it.

**Comment by umol-unibas** [comment]
Thanks @corbob I appreciate!
[Stunkymonkey](https://github.com/Stunkymonkey) also already approved my PR. If you need further help let me know
