### ISSUE TITLE
(googlechromebeta) Moderation emails for old versions

### ISSUE THREAD

**Issue by nsleigh** [chocolatey-community/chocolatey-packages#1647]
Over the last week I have been receiving moderation emails for old versions of the googlechromebeta - any idea why?

Examples (current version is  googlechromebeta v91.0.4472.27-beta):
[Chocolatey.org Moderation] googlechromebeta v89.0.4389.69-beta - Action Required - Review Comments
[Chocolatey.org Moderation] googlechromebeta v89.0.4389.69-beta - Finished Automated Moderation Review
[Chocolatey.org Moderation] googlechromebeta v89.0.4389.58-beta - Action Required - Review Comments
[Chocolatey.org Moderation] googlechromebeta v89.0.4389.58-beta - Finished Automated Moderation Review

**Comment by gep13** [comment]
@nsleigh we have been making some changes to the Package Moderation Services, as documented here: https://blog.chocolatey.org/2021/04/package-moderation-added-to-moderation-process/ so it is possible that these additional emails are coming from the work that was done here.

Do you happen to have a complete example of one of the emails that you have recieved?

**Comment by nsleigh** [comment]
I got these two recently (they always come in pairs), Sunday 02/05 @10:05 (BST):

**[Chocolatey.org Moderation] googlechromebeta v90.0.4430.41-beta - Action Required - Review Comments**
'googlechromebeta' is Exempted.
chocolatey-ops left the following comment(s):
googlechromebeta has passed automated virus scanning.
The package was exempted by chocolatey-ops on 01 Jan 0001.
Attention - DO NOT REPLY TO THIS MESSAGE!
•	No human moderators see packages until automated checks are passed or the maintainer uses the review comments box to respond. This is very important to understand, if a package has failed any automated checks, you must take action to fix or respond.
•	ATTENTION: If your package is failing any automated checks, the ONLY way to get in front of a human moderator is to follow the instructions in the next step.
•	If you need to update or respond to package review information, please login and visit your package page (listed below). Use the Add to Review Comments box ONLY, Disqus/Gist comments will not reach a human reviewer.
•	This may include review comments prior to the automated checks, check the status on the package - it must be in 'Ready' or 'Responded' to be in front of a human moderator.
•	You can also self-reject packages in certain scenarios - see self-reject for more information.
Package Url: https://community.chocolatey.org/packages/googlechromebeta/90.0.4430.41-beta
Maintainer(s): chocolatey-community, nsleigh

**[Chocolatey.org Moderation] googlechromebeta v90.0.4430.41-beta - Finished Automated Moderation Review**
'googlechromebeta' is Exempted.
The package was exempted by the reviewer on 01 Jan 0001.
Attention - DO NOT REPLY TO THIS MESSAGE!
•	No human moderators see packages until automated checks are passed or the maintainer uses the review comments box to respond. This is very important to understand, if a package has failed any automated checks, you must take action to fix or respond.
•	ATTENTION: If your package is failing any automated checks, the ONLY way to get in front of a human moderator is to follow the instructions in the next step.
•	If you need to update or respond to package review information, please login and visit your package page (listed below). Use the Add to Review Comments box ONLY, Disqus/Gist comments will not reach a human reviewer.
•	This may include review comments prior to the automated checks, check the status on the package - it must be in 'Ready' or 'Responded' to be in front of a human moderator.
•	You can also self-reject packages in certain scenarios - see self-reject for more information.
Package Url: https://community.chocolatey.org/packages/googlechromebeta/90.0.4430.41-beta
Maintainer(s): chocolatey-community, nsleigh

**Comment by gep13** [comment]
So, this is "working as expected" but I understand why it is causing a concern....

After the latest round of changes, package-scanner has now been fully integrated into the package moderation process, meaning that before it will be able to be marked as approved/exempted, it has to successfully get through the package-scanner checks.  This was not the case previously.

In the case of this beta package, the package-scanner had never run on the package, and the package-scanner is now playing "catch-up" to complete the necessary scan of this package.

I don't think this is anything to worry about, but you may see some other emails coming through, as it works its way through the backlog.

**Comment by nsleigh** [comment]
Ok thanks for the update. I think that now it is on v90 it is probably up to date.

**Comment by AdmiringWorm** [comment]
I am closing this issue, as there do not seem to be any actionable change we need to do.

If I am wrong, please do open a discussion over at: https://github.com/chocolatey-community/chocolatey-packages/discussions
