### ISSUE TITLE
(autohotkey.portable) Error when installing AutoHotkey v2.0-a135-b66a8739+ (--pre)

### ISSUE THREAD

**Issue by Ragnar-F** [chocolatey-community/chocolatey-packages#1663]
## Expected Behavior

It should be installed.

## Current Behavior

The installation fails.

## Possible Solution

See PR #1662. The installation script tries to deal with files which do not exist anymore in AutoHotkey v2.0-a135-b66a8739+. Reason: The executable files "AutoHotkeyU32.exe" and "AutoHotkeyU64.exe" have been renamed to "AutoHotkey32.exe" and "AutoHotkey64.exe".

## Steps to Reproduce (for bugs)

1. Run `chocolatey install autohotkey.portable --pre`
2. Check output

## Your Environment

* Package Version used: Latest stable
* Operating System and version: Windows 10 21H1
* Chocolatey version: Latest stable

**Comment by majkinetor** [comment]
AHK v2 should probably go into its own package IMO.

**Comment by RedBaron2** [comment]
@Ragnar-F
I saw the PR and I don't understand why the need to be so specific about the filenames. A crafted regular expression could find the right filenames and move out remove them. It would be more future proof.
This might be the issue now, but next release could break this change (Ex:  FreeCAD package).

**Comment by Ragnar-F** [comment]
My point was not to optimize this process, but just to make it work again. That's why I just took what was already there. Surely there are better methods for this. If someone has a better solution, feel free to submit it. I have absolutely nothing against it, if my PR is closed because of this.

**Comment by majkinetor** [comment]
AHK2 is different beast and using the same package name will probably break lots of other packages.
