### ISSUE TITLE
(vlc) With iSpy installed VLC can't upgrade

### ISSUE THREAD

**Issue by mavhc** [chocolatey-community/chocolatey-packages#1689]
## Expected Behavior

Run choco upgrade vlc, it shouldn't fail to upgrade vlc
## Current Behavior

With iSpy installed, which apparently comes with its own embedded version of VLC I get this error:

vlc installed to 'C:\Program Files\iSpy\VLC64'
ERROR: Path doesn't exist: C:\Program Files\iSpy\VLC64\vlc.exe

## Steps to Reproduce (for bugs)

1. Install iSpy (I think this was installed via choco too)
2. choco install vlc
3. wait for new version of vlc
4. choco upgrade vlc

## Your Environment

* Package Version used:
* Operating System and version: Windows 10 64 bit
* Chocolatey version:
* Install/uninstall gist:

**Comment by majkinetor** [comment]
Until this is fixed simple solution would be to install iSpy somewhere else outside Program files, or one level deeper (for example 'C:\Program Files\iSpy\iSpy`)

**Comment by J-Arx** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward? This issue will be closed in 14 days if it continues to be inactive.

Yes, seems still relevant.
With iSpy installed, upgrading VLC via Chocolatey gives "ERROR: Path doesn't exist: C:\Program Files\iSpy\VLC64\vlc.exe".

A workaround is still renaming the "iSpy" folder, so it is listed after the "VideoLAN" folder alphabetically. e.g:
1. rename "C:\Program Files\iSpy" to "C:\Program Files\ziSpy";
2. upgrade VLC via Chocolatey;
3. rename the "C:\Program Files\ziSpy" folder back to its original name "C:\Program Files\iSpy".

**Comment by J-Arx** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward? This issue will be closed in 14 days if it continues to be inactive.

After commit [55921699e62ed3b1e486a7f3cb18fa1f37d18256](https://github.com/chocolatey-community/chocolatey-packages/commit/55921699e62ed3b1e486a7f3cb18fa1f37d18256), upgrading VLC via Chocolatey seemed working fine for me.

**Comment by mavhc** [comment]
Works for me now, thanks to whoever fixed it
