### ISSUE TITLE
(git) offer an install switch to support the windows terminal profile installation added in git v2.32.0

### ISSUE THREAD

**Issue by frehov** [chocolatey-community/chocolatey-packages#1692]
## Expected Behavior

Following the [release of Git for windows 2.32.0](https://github.com/git-for-windows/git/releases/tag/v2.32.0.windows.1), git for windows added support for installing a windows terminal profile to make git bash usable from the windows terminal app.
I would like to see a switch for installing the windows terminal profile/fragment when installing git for windows through chocolatey.

## Current Behavior

The current behavior of the install when passing the "/WindowsTerminal" flag is to set CMD.exe as the terminal emulator instead of MinTTY. This switch could be ambiguous going forward as there now is support in Git for windows to install a Windows terminal fragment/profile when installing.

## Possible Solution

I'd like to suggest adding a switch `/InstallWindowsTerminalFragment` or `/InstallWindowsTerminalProfile` to identify the option for installing the windows terminal profile.

## Context

I've not had any adverse affects from this yet, but I'd like to collect all my terminal use into one terminal app in windows.

## Your Environment

* Package Version used: v2.32.0.2
* Operating System and version: Windows 10 - 21H1 - 19043.1083
* Chocolatey version: v0.10.15
* Install/uninstall gist:

**Comment by benbensenton** [comment]
whats the cmd flag to get ConHost, using git.exe /InstallWindowsTerminalProfile nor /WindowsTerminal does it?

**Comment by pauby** [comment]
@benbensenton this issue is closed. If you have a problem with the package please raise another issue. If you need support on git, or have questions, please see the git support documentation.
