### ISSUE TITLE
(simplewall) updates fail 

### ISSUE THREAD

**Issue by aminya** [chocolatey-community/chocolatey-packages#1700]
All the simplewall updates fail.

## Expected Behavior

Upgrade without errors

## Current Behavior

```
ERROR: Running ["C:\ProgramData\chocolatey\lib\simplewall.install\tools\simplewall-3.4.1-setup.exe" /S ] was not successful. Exit code was '2'. Exit code indicates the following: Setup was cancelled..
The upgrade of simplewall.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\simplewall.install\tools\chocolateyInstall.ps1'.
 See log for details.

```

## Possible Solution

Delete the simplewall folder manually, and install --force.

## Steps to Reproduce (for bugs)

1. choco upgrade simplewall

## Your Environment

* Package Version used: 3.4.1
* Operating System and version: Win 11 build 132
* Chocolatey version: 0.10.15
* Install/uninstall gist:

**Comment by 3941** [comment]
For me this only happens when I get an automated update notification.
If I use the Help menu and Check for updates, the update works just fine.
