### ISSUE TITLE
(everything) Create new package for es commandline client

### ISSUE THREAD

**Issue by corbob** [chocolatey-community/chocolatey-packages#1705]
## Expected Behavior

Everything has a [cli](https://www.voidtools.com/support/everything/command_line_interface/) that's available. It would be really helpful if this was included with the everything package.

## Current Behavior

Currently the cli is not included with everything, so a user needs to download it on their own and add it to their path.

## Possible Solution

I can think of two solutions:

1. Include es as part of `everything`.
2. Create an `everything-cli` package that takes `everything` as a dependency.

## Steps to Reproduce (for bugs)

N/A: Not a bug

## Context

I love Everything for the speed of searching on filenames. Recently I had a need to search for all files with a particular name on my system and found the Everything cli.

## Your Environment

N/A: Not a bug with the package. Anywhere that Everything is supported could theoretically benefit from the cli.

**Comment by mkevenaar** [comment]
A Chocolatey package is only allowed to install one piece of software. 

If the author ships it in one bundle / package we could argue that it's one.

As far as I can tell, `everything-cli` is another piece of software and therefor requires it's own package ID.

**Comment by majkinetor** [comment]
Its already included.

![image](https://user-images.githubusercontent.com/85767/131898644-a7263f74-f36a-42e1-b75a-505628f830ac.png)

**Comment by pauby** [comment]
We should look to pull the CLI out of the package and make it available separately.

**Comment by majkinetor** [comment]
No we shouldn't. Feel free to pursue this in your own spare time.

**Comment by pauby** [comment]
@majkinetor I've reopened the issue until we can address the issues that have been raised by both myself and @mkevenaar. Please leave it open.

**Comment by majkinetor** [comment]
This has nothing to do with this ticket. This ticket is about es not being included while it is. Create a new one for discussion. Thanks for keeping this place in order.

**Comment by mkevenaar** [comment]
Opening again, as requested by @pauby

**Comment by majkinetor** [comment]
Amazing behavior. Good job guys. Hope you are proud for your typical useless shenanigan in making this places harder to maintain.

**Comment by TheCakeIsNaOH** [comment]
> We should look to pull the CLI out of the package and make it available separately.

Should it be added as a dependency to the `everything` package? It would prevent a breaking change (for people currently using it via the everything package).

**Comment by pauby** [comment]
I can understand the desire for this, but it's not a dependency on the package itself. But as you said, it would avoid this being a breaking change.

**Comment by TheCakeIsNaOH** [comment]
I've discovered that es requires everything to be running to work, so the dependency actually needs to go the other way.

**Comment by TheCakeIsNaOH** [comment]
The [es](https://community.chocolatey.org/packages/es) has been approved.
