### ISSUE TITLE
(autohotkey) Create virtual, v1 and v2 packages

### ISSUE THREAD

**Issue by majkinetor** [chocolatey-community/chocolatey-packages#1710]
AHK v2 is dramatically different from AHK v1. Given the importance of this package for unattended installations, I propose the following:

1. Current ID `autohotkey` should become virtual package
2. Rename current autohotkey to autohotkey1
3. Create new package, autohotkey2
4. Via streams, make autohotkey to contain all releases from both versions.

Example for this methodology is done once by me in package PostgreSql and seems to work fine as one can choose major version but also choose not to care and entire thing is easily discoverable.

Alternatively, we could leave autohotkey as it is, and create set of new packages with different names: ahk, ahk1, ahk2 and deprecate autohotkey to target ahk1. Seems more clean and I like shorter name.

Also, this would have to handle portable variants. So its some work, but it could be done as single package with 5 streams.

If done, this would make #1663 and its PR obsolete.

Thoughts ?

**Comment by slycordinator** [comment]
This issue is valid/relevant.

Currently:
1) many packages depend on autohotkey.install and use version 1 syntax for their AHK scripts.
2) autohotkey.portable is currently at version 2
3) autohotkey.portable places the version 2 'AutoHotkey.exe' into $env:ChocolateyInstall\bin
4) And packages that use autohotkey.install and expect version 1 will call 'AutoHotkey', which then runs the version 2 executable from above and the user receives popups of syntax errors.

**Comment by pauby** [comment]
I've reopened this issue as I noticed 1.1 is deprecated so we can'yt just leave everything at v1.

If a package has a dependency on `autohotkey` or `autohotkey.install` (latest is 1.1.36.02), and they install another package that  requires `autohotkey.portable` (latest is 2.0.2) then the Auothotkey software will be upgraded to 2.0.2 overwriting the 1.1.36.02 version. You can't have both versions of Autohotkey installed. 

We have:

* `autohotkey.portable` at version 2.0.3.
* `autohotkey.install` at version 1.1.36.02.
* `autohotkey` at version 1.1.36.02 (it takes `autohotkey.install` as a dependency.

This is a bit of a mess.

It appears that you can install both v1 and v2 of Auothotkey and v2 will therefore be able to execute v1 scripts. I don't know how this works with portable versions as I haven't looked at that yet. However, I have submitted #2246 for the `autohotkey.install` v2 version that includes backwards compatibility with v1 scripts.
