### ISSUE TITLE
(thunderbird) Add option to not kill Thunderbird during update

### ISSUE THREAD

**Issue by opoplawski** [chocolatey-community/chocolatey-packages#1721]
## Expected Behavior
We perform automatic updates on user's machines via a remote connection by an admin user.  Killing Thunderbird on a user during the update is not acceptable.

## Current Behavior
The current package will kill Thunderbird processes and attempt to restart it.  Restarting it also does not make sense in this case because the user performing the update is not the user of the machine.

## Possible Solution
Add package argument NoKill or similar

## Steps to Reproduce (for bugs)
1.  As a remote user run "cup thunderbird"

## Your Environment
* Package Version used: 91.1.2

**Comment by pauby** [comment]
Is this something you can submit a PR for?

**Comment by opoplawski** [comment]
Not easily.  I've never worked on a chocolatey package before and I don't know what to change or how to test it.
