### ISSUE TITLE
(everything) package prereleases of the newest early "alpha" versions

### ISSUE THREAD

**Issue by K0media** [chocolatey-community/chocolatey-packages#1743]
Everything now has an alpha version full of new features and it's under development.

## Expected Behavior

It would be nice if the prereleases ("alpha") versions could be packaged into Choco's package.

## Current Behavior

It's not cached/packaged to Choco's packages, so I'd like to have it to ease the task of installation.

## Possible Solution

1. Include the prerelease as a part of the existing package with the `--pre` argument;
2. Or either implement the `everything-alpha` package to the public repo.

## Steps to Reproduce (for bugs)

It is not a bug. Just lacking information/data.

## Context

Without this package I have to install it directly by browsing the forums which is a tedious process. Please implement the early builds to ease the installation beforehand.

## Your Environment

* Package Version used: 1.5.0.1284a
* Operating System and version: Windows 10 21H1 (stable build)
* Chocolatey version: 0.11.3
* Install/uninstall gist: https://www.voidtools.com/forum/viewtopic.php?f=12&t=9787#download

**Comment by pauby** [comment]
Is this somethign you can submit a PR for?

**Comment by K0media** [comment]
> Is this something you can submit a PR for?

Sorry, I'm not a programmer myself.

Just asked for this to be added since I need to install the package in an easy way.

**Comment by AdmiringWorm** [comment]
Pre-Release packages are normally very low on the priority list in this repository, and we rarely add support for these ourselves.
Usually, the only time pre-releases is started to be supported for packages in the repository is if it is contributed by any community member as a pull request.

I'll mark the issue as up for grabs, it should in general be easy to implement, but will need to know a bit about AU and AU streams.
