### ISSUE TITLE
(waterfox) version G4.0.3 released

### ISSUE THREAD

**Issue by slycordinator** [chocolatey-community/chocolatey-packages#1751]
https://www.waterfox.net/download/
At the above, a Waterfox.G4.0.3.Setup.exe is available to download/install.

Expected Behavior
Current version able to be installed

Current Behavior
Most recent version available is 3.2.6, released a couple of months ago.

**Comment by AdmiringWorm** [comment]
Our update script has been fixed (🤞), and a new version of the package should be submitted to Chocolatey Community Repository soon. Will take a few hours until it has passed the automated moderation checks before it is available for normal consumption.
