### ISSUE TITLE
(ruby.portable) Migrate package

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-packages#1757]
Accepted as it is a Core package used by Chocolatey CLI itself, and we are already maintaining the installer edition of the package.

### Discussed in https://github.com/chocolatey-community/chocolatey-packages/discussions/1756

<div type='discussions-op-text'>

<sup>Originally posted by **TheCakeIsNaOH** November 25, 2021</sup>

The `ruby.portable` package is out of date and is currently broken due to the shutdown of bintray. 
https://community.chocolatey.org/packages/ruby.portable

The current maintainer, @ferventcoder, is not actively maintaining packages on CCR at the moment. This package is used by the ruby alternate source for the Chocolatey CLI install command, so it is important that it is working, thus the suggestion by @AdmiringWorm to bring it into this repository.

It should be able to be updatable by AU with a similar script to the one for the `ruby` package.

As a part of this migration, the `ruby` package should probably be converted to a virtual package, and a `ruby.install` package should be created.

I'm not sure who should be responsible for this package, perhaps someone would be able to volunteer?</div>

## Done checklist

- [x] Rename existing `ruby` package to `ruby.install`
- [x] Create meta package `ruby` that have a dependency on `ruby.install`
- [x] Migrate `ruby.portable` from https://github.com/ferventcoder/chocolatey-packages/tree/master/manual/ruby.portable to this repository
- [x] Update and modernize `ruby.porptable` to latest Contributing Guidelines
- [x] Create AU update script to keep `ruby.portable` automatically up to date
- [x] Open PR to remove `ruby.protable` from https://github.com/ferventcoder/chocolatey-packages
- [x] Update `CODE_OWNERS` file with GitHub user responsible of keeping the package up to date, and fix any issues

**Comment by TheCakeIsNaOH** [comment]
I have opened PRs to take care of all but the last item on the todo list.

**Comment by AdmiringWorm** [comment]
This issue has now been completed thanks to @TheCakeIsNaOH.

A new version of the ruby.portable package should also be submitted soon to CCR.
