### ISSUE TITLE
(python) installer does not update PATH env

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-packages#1761]
## Expected Behavior
Installer should update PATH env when PrependPath=1 is used.

## Current Behavior
It does not, PATH is not changed.

## Steps to Reproduce (for bugs)

1. Install python
2. Path is not changed.

## Your Environment

* Package Version used: python v3.10.0
* Operating System and version: Windows 11
* Chocolatey version: 0.11.3
* Install/uninstall gist: https://gist.github.com/soredake/d6acf05312c52e0fc68f17e2d863e8a9

**Comment by TheCakeIsNaOH** [comment]
Please include the command you are using in the "Steps to Reproduce", but I'll take a stab at this anyway.

Have you read the notes in the description of the python package? 
> Notes
  This package depends on the the latest major version of python package.
   This package do not support package parameters, please install the package python3 directly when using package parameters.

The `python` package does not install anything itself, instead, it takes a dependency on the `python3` package, which is what installs python. So, if you are wanting to pass custom arguments to the python installer with `--install-arguments`, you either need to install the `python3` package, or add the `--apply-args-to-dependencies` so the custom install arguments actually get to the `python3` package.

Also, the python3 package already should be passing `PrependPath=1` automatically unless you are using the `/InstallDir32:` parameter.

**Comment by soredake** [comment]
My bad, i was reinstalling meta package instead of actual python.
