### ISSUE TITLE
(blender) Servers fail to push the latest version to the repository (v3.0.0)

### ISSUE THREAD

**Issue by Some-Dood** [chocolatey-community/chocolatey-packages#1763]
## Expected Behavior
The repository should pick up the latest Blender version (3.0.0), released 3 December 2021.

## Current Behavior
Based on [Choco Bot's error section](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#errors), a "request entity [appears to be] too large" to be pushed. Hence, the `blender` package is currently stuck on `2.93.6` as of writing. Choco Bot's error message is given below:

```
Chocolatey v0.10.15 Attempting to push blender.3.0.0.nupkg to https://push.chocolatey.org
Failed to process request. 'Request Entity Too Large'.
The remote server returned an error: (413) Request Entity Too Large..
```

## Possible Solution

Although I'm not greatly familiar with the Chocolatey infrastructure, I inferred from Choco Bot's error message that perhaps a limits exception may be issued for the Blender package?

**Comment by TheCakeIsNaOH** [comment]
The current maximum size for packages (`.nupkg`s) on the community repository is 200mb. It looks like the blender 3.0 installer is slightly over 200mb, so with it included in the package it makes the package too big for the community repository.

The solution is to download the installer at runtime, instead of embedding it inside the package. 

PRs are welcomed here, or I think I may be able to get to this fairly soon.

**Comment by AdmiringWorm** [comment]
What @TheCakeIsNaOH says is most likely the culprit of the package failing.

As such this package needs to be changed to download the installer instead of having it embedded inside the package going forward 😢

**Comment by fkrauthan** [comment]
Any news on this? Are there any samples of other apps that I could look into to give this a stab?

**Comment by RedBaron2** [comment]
@fkrauthan 
Several of the community packages make use of downloading the installer on the consumer's computer; when being installed through chocolatey. Chromium, Firefox, and Google Chrome are a few examples. Good luck in the new year.

**Comment by fkrauthan** [comment]
@RedBaron2 Ok perfect. I gave it a stab. Never worked with Powershell before so there might be room for improvement but it works. Created a PR already.

**Comment by fkrauthan** [comment]
Seem to be working now after my merge request. I see version `3.0` on the repo. This can probably be closed.

**Comment by Some-Dood** [comment]
Alrighty, thanks for your help! @fkrauthan 🎉
