### ISSUE TITLE
(ffmpeg*) descriptions missing codecs/libraries included in each

### ISSUE THREAD

**Issue by slycordinator** [chocolatey-community/chocolatey-packages#1765]
The packages "ffmpeg" and "ffmpeg-full" descriptions make no reference to the libraries included in each.
They instead refer to "essentials" and "full", neither of which exist in the upstream ffmpeg project at www.ffmpeg.org.

## Expected Behavior
1) Be able to look at package description and see the differences between the packages.
or
2) Have the package description link to a site that shows the differences

## Current Behavior
"ffmpeg" is described as the "essentials ffmpeg version"
"ffmpeg-full" is described as the "full ffmpeg version"

## Possible Solution
The packages seem to be using builds from gyan.dev, so a reference to https://www.gyan.dev/ffmpeg/builds/#libraries could suffice, since it lists the included libraries for each there.

**Comment by AdmiringWorm** [comment]
@slycordinator that is a good catch that we somehow had missed.

If you are interested, I have marked this issue as Up for grabs if you are willing to provide a PR to get the link containing the libraries added (only the `Readme.md` file need to be updated, and should be in a `## Notes` section in that file).
