### ISSUE TITLE
(notepadplusplus.install) issue when exe is currently running

### ISSUE THREAD

**Issue by Vankog** [chocolatey-community/chocolatey-packages#1766]
Choco upgrade cannot handle running Notepad++ instances.

## Expected Behavior
If notepadd++.exe is running, either:
* close the application to make upgrading possible
* or fail the upgrade.

## Current Behavior
If notepad++.exe is running, the upgrade is seemingly successful, but that's not correct.
When checking the "about" dialog of the app after restarting it, it still shows the old version.

## Possible Solution
* close the application to make upgrading possible
* or fail the upgrade.

## Steps to Reproduce (for bugs)
1. open Notepad++ in an older version
2. run `choco upgrade notepadplusplus -y` or `choco upgrade notepadplusplus.install -y`:
```
Installing 64-bit notepadplusplus.install...
notepadplusplus.install has been installed.
notepadplusplus.install installed to 'C:\Program Files\Notepad++'
Added C:\ProgramData\chocolatey\bin\notepad++.exe shim pointed to 'c:\program files\notepad++\notepad++.exe'.
 The upgrade of notepadplusplus.install was successful.
  Software installed as 'exe', install location is likely default.
```
3. close and reopen Notepad++
4. check menu -> "?" -> "About Notepad++"   
version is still the old one

## Your Environment
* Package Version used:
notepadplusplus and notepadplusplus.install v. 8.1.9.2 upgraded to 8.1.9.3
* Operating System and version:
Wind 10 Pro x64 - 21H1 - 19043.145
* Chocolatey version:
chocolatey 0.11.3
chocolatey-core.extension 1.3.5.1
chocolatey-dotnetfx.extension 1.0.1
chocolatey-misc-helpers.extension 0.0.4
chocolatey-windowsupdate.extension 1.0.4
* Powershell 7.2.1

**Comment by AdmiringWorm** [comment]
As @TheCakeIsNaOH already mentioned, the work are not lost even if notepad++ is closed.
If it is closed with the `-Force` flag when calling `Remove-Process` there may be something lost, or if there is a very old version of notepad++.
