### ISSUE TITLE
(mpc-hc-clsid2) new release available

### ISSUE THREAD

**Issue by gwendal-g** [chocolatey-community/chocolatey-packages#1767]
Hello,

There is a new version for the package https://community.chocolatey.org/packages/mpc-hc-clsid2
The update is available at this address: https://github.com/clsid2/mpc-hc/releases/tag/1.9.18

Current version: 1.9.16
New version: 1.9.18

Kind regards,

**Comment by AdmiringWorm** [comment]
hmm, looks like there is something going on when we try to update the package.

I'll have a look at it as soon as I can.

**Comment by AdmiringWorm** [comment]
A new update of this package is now queued on our update CI, a new package version should be submitted shortly and will be available once it has completed the moderation checks.
