### ISSUE TITLE
(kitty) Upgrade for Kitty

### ISSUE THREAD

**Issue by BenoitPoulet** [chocolatey-community/chocolatey-packages#1768]
Hello,

The Kitty package is pretty old (0.74), the last version is 0.76.0.2.

An upgrade is possible ?

Thank you.

**Comment by AdmiringWorm** [comment]
Looks like there have been an up stream change that prevents the update, I'll take a look at what is going on.

**Comment by AdmiringWorm** [comment]
hmm, looks like they are now only providing the portable executable through fosshub now, which we unfortunately can not use.

There is a zip package that may be possible to be used instead, but I have not looked far enough into it to see if it is a viable option yet.

**Comment by majkinetor** [comment]
It can be done by unpacking latest releases zip file:

![image](https://user-images.githubusercontent.com/85767/151063201-6fb76e4e-27c5-47eb-966c-99f2b9e14a9c.png)

There are some changes: 

1. `gensfc.exe` is gone 
2. There are now 2 cygwin files. 

So I think we should just pack everything into choco package as before.

**Comment by ZatsuneNoMokou** [comment]
There is also a zip file in the github releases https://github.com/cyd01/KiTTY/releases/tag/v0.76.0.8

**Comment by d-Rickyy-b** [comment]
Hi there, I'd appreciate having an up-to-date version of kitty on chocolatey. Is there anything one can do to help update this package?

**Comment by pauby** [comment]
@d-Rickyy-b You could submit a PR with a fix for the issues outlined above?

**Comment by oldium** [comment]
It should be possible to embed the Kitty installer directly in the package - see https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0028, option 2.

**Comment by yelkarama** [comment]
Just submitted a [PR](https://github.com/chocolatey-community/chocolatey-packages/pull/1876) for it.

**Comment by yelkarama** [comment]
Hi @AdmiringWorm 
Are you able to merge my PR? 
Thanks
