### ISSUE TITLE
(1password) Update to Version 8.x

### ISSUE THREAD

**Issue by BlythMeister** [chocolatey-community/chocolatey-packages#1773]
Can the 1passoword package be updated to version 8.x (I've had a look and there seems to be ongoing issue under discussion/fix regarding 1password, but that's for V7.x

Wondering if upgrading to V8 will change the way things work and will then also solve the issues with V7.x :)

**Comment by bereldhuin** [comment]
+1

**Comment by Chadfarkas** [comment]
+1

**Comment by anthonysomerset** [comment]
I want this but it looks like AgileBits need to update the auto update feed first - https://app-updates.agilebits.com/ is still showing v7 and the choco package is dependent on that

**Comment by crosscontrol** [comment]
Is there an effective way to use this?

https://downloads.1password.com/win/1PasswordSetup-latest.exe

If not, I'll follow up with an additional post in the Agile Bits forum.

**Comment by anthonysomerset** [comment]
the only issue i see there is not being able to easily determine the version number but it would be a simple solution all round

**Comment by crosscontrol** [comment]
Okay I think I've got an idea. I just tested this and it works (substitute latest with the version):

- https://downloads.1password.com/win/1PasswordSetup-8.7.0.exe
- https://downloads.1password.com/win/1PasswordSetup-8.6.0.exe
- etc...

What if during the build we get the version number by running the following on the downloaded latest file:

`(get-itemproperty .\1PasswordSetup-latest.exe).VersionInfo.ProductVersion` which at the time of writing returns 8.7.0.

Then take that version number and build the download link:

https://downloads.1password.com/win/1PasswordSetup-8.7.0.exe

Or you can just keep it simple and manually put it into the source. I haven't gone deep into how the community build repo works but if it runs periodically, you could work it out that way too.

Thoughts?

**Comment by anthonysomerset** [comment]
that was ironically going to be my original approach....

but Get-ItemProperty is probably the safer bet considering the package is auto updated on choco side

**Comment by RedBaron2** [comment]
@anthonysomerset 
My suggestion is find out from AgileBits if the 1password8 nightly builds are stable releases?
The way the updater currently looks for its needed information is by reading the page and then getting the version from the file name. Updating the releases url for versions with 8 isn't to hard, but the current page lists nightly builds besides the stable. The nightly builds would be considered beta or `--pre` builds according to the version number in chocolatey.

I hope this helps you out.

**Comment by BlythMeister** [comment]
Bump

**Comment by AdmiringWorm** [comment]
@BlythMeister please do not bump issues unless you intend to work on the issue itself. This issue is marked as up for grabs for a reason.

It will only be fixed if there is someone in the community that is interested in opening a PR to add the support for version 8 or if one of the _core_ maintainers has a personal interest in adding the support, if the issue gets closed automatically by the bot that is running on this repository it may become a candidate for discussion to be moved out of this repository and an RFM issue on https://github.com/chocolatey-community/chocolatey-package-requests will be created in that case.

I will be re-adding the `Pending closure` label to this issue, and further bumping of the issue may result in it becoming closed immediately instead.

**Comment by BlythMeister** [comment]
Sorry I bumped as the pending closure was added, but it's not resolved so why should it be closed?

**Comment by crosscontrol** [comment]
I do want to work on this issue. I should get some time soon. I've already been priming for it by understanding AU, etc.

**Comment by KUTlime** [comment]
This problem is just annoying. I'm willing to fix it. An easy solution to bypass _the latest version problem_ is just simply ping to urls and iterate up. I did that approach couple of times already.

Is there any startup tutorial for people like how to write PR to this repo + how these packages should be written? Thank you. 👍🏿

**Comment by jacktose** [comment]
FYI https://app-updates.agilebits.com/download/OPW8 is apparently a 302 redirect to the latest nightly: currently https://c.1password.com/dist/1P/win8/1PasswordSetup-8.9.6-15.NIGHTLY.exe. The header (e.g. `curl -iI`) has enough info to parse out the version number. I suppose `--pre` could use that, but I can't find an equivalent for the latest stable v8.

https://app-updates.agilebits.com/download/OPW7 is a 302 redirect to the latest stable v7: currently https://c.1password.com/dist/1P/win6/1PasswordSetup-7.9.832.exe That could be useful for a `1Password7` versioned package.

**Comment by jacktose** [comment]
> I want this but it looks like AgileBits need to update the auto update feed first - https://app-updates.agilebits.com/

@anthonysomerset Could you scrape https://app-updates.agilebits.com/product_history/OPW8 for the first listing without `.NIGHTLY`?

**Comment by imiddleton1** [comment]
Can this link be used?  It was sent to my by 1Password support.

https://downloads.1password.com/win/1PasswordSetup-latest.msi

**Comment by chrrobi-sagard** [comment]
Hello, 

Is there anything specific needed looked at or reworked for this pull? I am hoping to be able to deploy it soonish.

Given 1Passwords change in approach (and the fact they only support x64 now) I have committed a new package. The other thing I have done is leveraged the MSI (machine wide install) vs the EXE (user centric install) which permits it to be used within an MDM solution without requiring user impersonation

Thanks for your help and reviews.

Best Regards
