### ISSUE TITLE
(vcredist140) Fails installation on 64bit system when `--x86` is used for parent package

### ISSUE THREAD

**Issue by petezx9** [chocolatey-community/chocolatey-packages#1774]
We are using choco as an easy way to install (and update) software inside our containers.
we need to install the 32-bit python into a base Microsoft image,
The issue is reported by my colleague Chris Hopkins to the choco package maintainer here...
https://community.chocolatey.org/packages/python3/3.10.1
We think maybe it's a choco issue?

## Expected Behavior
it works :-). 
python3 32bit is installed.

## Current Behavior
get an Error 

> Download of VC_redist.x86.exe (13.06 MB) completed.
> Hashes match.
> Installing vcredist140-x86...
> vcredist140-x86 has been installed.
> ERROR: This package does not support 32 bit architecture.
>   vcredist140 can be automatically uninstalled.
> The install of vcredist140 was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\vcredist140\tools\chocolateyInstall.ps1'.
>  See log for details

## Steps to Reproduce (for bugs)
Get a PowerShell terminal in a docker container...
  _docker run --rm -it  mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2019 powershell_
install choco inside the Container.
  _iex ((New-Object System.Net.WebClient).DownloadString("https://chocolatey.org/install.ps1"));_
use choco inside the container to install python3, forcing 32 bit (--x86).
   _choco install python3 --version=3.10.1 -y --no-progress --reduce-package-size --x86 --installargs 'InstallAllUse
rs=1 Shortcuts=0 Include_doc=0 Include_pip=1 Include_test=0'_

## Context
we are using choco as an easy way to install (and update) software inside our containers.
we need to install the 32-bit python onto this base Microsoft image,

## Your Environment
Docker desktop installed and set to windows containers and hyper-v isolation.
Docker image as above.

**Comment by AdmiringWorm** [comment]
This looks to be an oversight in the vcredist140 package and not a problem with the python3 package itself.

The `--x86` argument gets inherited by any dependent package as well, for now I would recommend that you install the dependency `vcredist140` first without the `--x86` argument before installing the python3 package itself.

At least until we have a fix available for the problem in the package.

**Comment by petezx9** [comment]
Thanks for taking the time to look.
I can confirm that running
_choco install vcredist140 -y --no-progress --reduce-package-size_
before the python 32bit install is a successful 'workaround' for us.  :-)

**Comment by AdmiringWorm** [comment]
Good to know that is a workaround for you, I do hope to look back into this when I have more time to work on this repository so that workaround won't be necessary for the future.

/cc @jberezanski for visibility

**Comment by pauby** [comment]
@jberezanski Are you able to look at this?

**Comment by jberezanski** [comment]
Fixed and pushed, versions:
14.31.31103.20220402 (Visual Studio 2022 stream)
14.29.30139.20220402 (Visual Studio 2019 stream)
14.16.27033.20220402 (Visual Studio 2017 stream)

**Comment by jberezanski** [comment]
However,

> The --x86 argument gets inherited by any dependent package as well,

I don't like this behavior. I understand its usefulness in one narrow use case (metapackages depending on *.install), but in general I believe it is actively harmful, same as `--apply-package-parameters-to-dependencies` / `--apply-install-arguments-to-dependencies` (fortunately false by default).

Here, for example, only the 32-bit VC++ runtime will be installed as a dependency of python3, but the vcredist140 package will be considered fully installed by choco. Subsequent installation of some 64-bit software depending on the VC++ runtime will not trigger installation of the 64-bit runtime and the application will not work.
