### ISSUE TITLE
(git) git install fails with access violation when installing in windows container (ltsc2022) with process isolation

### ISSUE THREAD

**Issue by TomSmithGR** [chocolatey-community/chocolatey-packages#1776]
## Expected Behavior
installing git on a windows server core container using process isolation should be successful. 

## Current Behavior
I am using mcr.microsoft.com/windows/servercore:ltsc2022 base image
installing git without process isolation on the container works as expected
installing git with process isolation on the container causes an error with Git-2.34.1-64-bit.exe. An unhandled exception occurs which stops the git.install package being installed correctly. 

## Steps to Reproduce (for bugs)
1. download attached dockerfile
2. docker build --isolation=process .
3. see error:
`ERROR: Running ["C:\ProgramData\chocolatey\lib\git.install\tools\Git-2.34.1-64-bit.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOCANCEL /SP- /LOG /COMPONENTS="icons,assoc,assoc_sh,,,,gitlfs,icons\quicklaunch" /o:PathOption=Cmd /o:BashTerminalOption=ConHost /o:CRLFOption=CRLFCommitAsIs ] was not successful. Exit code was '-1073741819'. See log for possible error messages.
The install of git.install was NOT successful.`
4. docker build .
5. see successful install complete.

## Context
I need to support process isolation as this is part of a larger build environment

## Your Environment
* Package Version used: git v2.34.1
* Operating System and version:  I am running windows 11, Docker Desktop 4.3.2 (72729), ltsc2022 tag for server core images
* Chocolatey version: latest, installed from website during docker build
* Install/uninstall gist:

[Dockerfile.txt](https://github.com/chocolatey-community/chocolatey-packages/files/7815000/Dockerfile.txt)

**Comment by TomSmithGR** [comment]
One thing that may or may not be relevant, but manually installing the git installer with the command line parameters shown above gives an error parsing the /COMPONENTS= parameter due to the repeated commas, and a return value of 1.

**Comment by slonopotamus** [comment]
Reported to Microsoft: https://github.com/microsoft/Windows-Containers/issues/197
It is very likely that this bug is not Chocolatey fault.

**Comment by TomSmithGR** [comment]
closing this as its related to specific container and hardware combo
