### ISSUE TITLE
(sysinternals) `ShellRunAs.exe` Prompted For Eula

### ISSUE THREAD

**Issue by mattcargile** [chocolatey-community/chocolatey-packages#1777]
## Expected Behavior

I'd prefer to accept all Eula's during install.
## Current Behavior

I was asked to accept the Eula when running `ShellRunAs.exe`
## Possible Solution

The registry key added was `ShellRunas - Sysinternals: www.sysinternals.com` at path of `HKCU:\SOFTWARE\SysInternals\` with `EulaAccepted` value at `1`. [Here](https://www.hexacorn.com/blog/2014/11/30/sysinternals-eulagoogoolizer/) is an article discussing in more detail.
## Steps to Reproduce (for bugs)

1. Install sysinternals fresh
2. Run `ShellRunAs.exe` without any flags.

## Context

It was a minor inconvenience.
## Your Environment

* Package Version used: Unknown. I have the latest sysinternals version and used `choco upgrade`.
* Operating System and version: `Windows 10 1909 ( OS Build 18363.1377 )`
* Chocolatey version:`0.11.3`
* Install/uninstall gist:

**Comment by TheCakeIsNaOH** [comment]
I've double check this, and yup, the wrong registry key for license acceptance was specified in the helper function.
