### ISSUE TITLE
There is a misspelling in the script that installs from the online repository

### ISSUE THREAD

**Issue by Nio9345** [chocolatey-community/chocolatey-packages#1780]
There is a spelling error somewhere in the script that installs iTunes from the online repository. The choco installer reports something about "isntall" or "istnall" not being a valid command, so somewhere there is a misspelling.
The offline packet installs just fine so the problem is definitely with the online script. I could provide a log file but for some reason it just skips the install all together and I don't get an execution log file only if the install starts.

**Comment by TheCakeIsNaOH** [comment]
You can run with `--verbose` and `--debug`, which will print out the log information to the console.

**Comment by AdmiringWorm** [comment]
@Nio9345 please provide the log file, without it, we can not do much.

I had a look at the package and there is not a single place where the usage of `isntall` or `istnall` is being used.

Just making an assumption here, but to me, it sounds like you may have had a typo when typing in the command to install the package (can not say for sure though).

**Comment by Nio9345** [comment]
While I tried to use the --verbose command I found the misspelling on my batch file. So now the program runs correctly. Sorry for the trouble.
