### ISSUE TITLE
(ruby) Many versions of Ruby have no corresponding version on Chocolatey

### ISSUE THREAD

**Issue by chrisdjali-wrld3d** [chocolatey-community/chocolatey-packages#1783]
## Expected Behavior

Major versions of Ruby increment the second number in the version rather than the first, so, for example, 2.5.8-1 is backwards-compatible with 2.5.3-1, but not 2.4.7-1. There can still be bugs and incompatibilities to resolve in the previous major version, though, so there are still 2.n.x releases after 2.n+1.0-1 is released. One might expect that those releases are available through chocolatey if `--version` is passed.

## Current Behavior

Instead, once 2.n+1.0-1 is released, any further 2.n.x-y releases are ignored by the package generation script. For example, Ruby 2.5.9-1 was released in April 2020, but the latest 2.5.x on Chocolatey is 2.5.3-101 (with the 01 suffix being a fix version from Chocolatey rather than part of the Ruby version) from 2018.

## Possible Solution

* #1298, so there'd be a `ruby2.5` package and a `ruby2.6` package and a `ruby2.7` package etc. plus one `ruby` metapackage that just installed the latest. This has been previously rejected.
* Change the package generation script so it'll pick up minor and patch releases for older major versions, and generate and publish packages for them.

## Context

Because Ruby native gems rely on MSYS2, and MSYS2 has a rolling release model, sometimes a change to MSYS2 breaks Ruby (even if the MSYS2 version's pinned in Chocolatey). Because MSYS2 removed some old versions of automake a week ago with https://github.com/msys2/MSYS2-packages/commit/de632449e0562c3621497448f646046d88a26596, Ruby 2.5.3-101 from Chocolatey doesn't work properly (`ridk install 3` fails). Ruby 2.5.8-1 removed the dependency on these automake MSYS2 packages, but it isn't available through Chocolatey, so if you've got Ruby 2.5 code, you'd need to either stop using the Chocolatey package to install Ruby, or port the Ruby code to a newer version.

Locally, I've worked around this by creating a 2.5.9-1 version of the public package by swapping out the version numbers and files - the package scripts themselves are compatible with the missing versions, it's just the package generation script not creating the missing package versions.

**Comment by TheCakeIsNaOH** [comment]
> Change the package generation script so it'll pick up minor and patch releases for older major versions, and generate and publish packages for them.

This is definitely the way to go. 

There are a number of packages on the community repository that continue to upload minor releases for older major versions after a new major version has been released. An example of it in this repository is the python3 package: https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/python3

The way it accomplishes this is by having AU streams:
https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/python3/update.ps1#L25-L61

I think this should be quite possible for the ruby package, although perhaps this should be done after the switch to a `.install` package, #1757

**Comment by AdmiringWorm** [comment]
Changes required to fulfil this issue has been completed in the repository, it will take a while until these changes will surface on CCR though.
