### ISSUE TITLE
vagrant v2.2.19  vagrant (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\vagrant\tools\chocolateyinstall.ps1

### ISSUE THREAD

**Issue by eoumenwa** [chocolatey-community/chocolatey-packages#1784]
Trying to install vagrant on Windows 10 powershell but keep getting the errors below.

PS C:\WINDOWS\system32> choco install vagrant
Chocolatey v0.11.3
Installing the following packages:
vagrant
By installing, you accept licenses for the packages.
Progress: Downloading vagrant 2.2.19... 100%

vagrant v2.2.19 [Approved]
vagrant package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was '792868E112CD487CC8BBEEE9B42F56E53D7BC60E8677950BB8D3FC31F76CE147'.
Downloading vagrant 64 bit
  from 'https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.msi'
Progress: 65% - Saving 169.54 MB of 258.29 MB                                                                          
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_x86_64.msi'. Exception calling "Read" with "3" argument(s): "The decryption operation failed, see inner exception."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
The install of vagrant was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\vagrant\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - vagrant (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\vagrant\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by pauby** [comment]
This looks to be a network / connection issue and not a package issue as the download fails at 65%. I've tested installing this and it's working fine. Going to go ahead and close this.
