### ISSUE TITLE
Problem downloading files for offline installation

### ISSUE THREAD

**Issue by Nio9345** [chocolatey-community/chocolatey-packages#1785]
I try to download the package in order to install Firefox offline and the ChocBox.cmd troughs this error every time.

Version number [ ENTER=current version ] :

Downloading and converting Firefox  to run from C:\DRIVERS\chocbox
Running ChocolateStore to make package...
Skipped: Firefox.96.0.1.nupkg - File already exists on disk.
Download Failed: https://download.mozilla.org/?product=firefox-96.0.1-ssl&os=win&lang=${locale}
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at ChocolateStore.PackageCacher.DownloadFile(String url, String destination)
Download Failed: https://download.mozilla.org/?product=firefox-96.0.1-ssl&os=win64&lang=${locale}
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at ChocolateStore.PackageCacher.DownloadFile(String url, String destination)

**Comment by pauby** [comment]
What's `ChocBox.cmd`?

**Comment by Nio9345** [comment]
it's the script I use through E2B to run the chocolatey PowerShell program to download the packages and nupkg files in order to have offline installs for auto installations. Though it's a third party program it still calls the Chocolatey PowerShell program

**Comment by gep13** [comment]
Looks like ChocolateStore isn't replacing the `{locale}` variable in the URL, therefore the download isn't working.

**Comment by Nio9345** [comment]
Yeah. Good point, is there a way to force or choose a locale to download?

**Comment by gep13** [comment]
That would come down to how ChocolateyStore works, and this is not the right place to answer that question.

**Comment by Nio9345** [comment]
Yeah, figured as much. So I closed the issue since I'm pretty sure I won't get my answer here.

**Comment by gep13** [comment]
@Nio9345 seems like this is a none issue with ChocolateStore: https://github.com/BahKoo/ChocolateStore/issues/4
