### ISSUE TITLE
(brave) Release vs Pre-Release Version Confusion

### ISSUE THREAD

**Issue by Skatterbrainz** [chocolatey-community/chocolatey-packages#1791]
The current package shows 1.35.99 as the latest "official release version" but 1.34.81 is the latest official release. 1.35.99 was a nightly pre-release build.  The source list for pulling versions may be the root cause of this (from Brave.com).  Just letting you know because several customers of mine expressed concern that the different versions could be construed as being tampered with and untrusted.

## Expected Behavior
Should match "official release version" to the actual vendor latest release version (see above)

## Current Behavior
Pulls releases from a source list that may be merging pre-release builds with stable builds. The result is pre-release version getting packaged and labeled as the latest stable version.

## Possible Solution
Not sure.

## Steps to Reproduce (for bugs)
1. Compare Chocolately package version with Brave.com latest stable release version (1.35.99 vs 1.34.81)
2.
3.
4.

## Context
Some of my customers expressed concern that package may be untrustworthy and tampered with since no 1.35.99 version could be found on the brave.com web site (without digging into the nightly build history in Github).  The official download shows 1.34.81.

## Your Environment
* Package Version used: (latest is 1.35.99)
* Operating System and version: Windows 10 and 11 (21H1 for both)
* Chocolatey version: 0.11.3
* Install/uninstall gist:

**Comment by TheCakeIsNaOH** [comment]
> The source list for pulling versions may be the root cause of this (from Brave.com). 

The script that updates the package actually uses the github releases:
https://github.com/brave/brave-browser/releases

> Pulls releases from a source list that may be merging pre-release builds with stable builds. The result is pre-release version getting packaged and labeled as the latest stable version.

Yes, that is what is happening as far as I can see.

The update script looks for `StandaloneSilentSetup.exe` in the filename to filter to the stable releases:
https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/brave/update.ps1#L14-L15

Example of the filename for stable releases here:
https://github.com/brave/brave-browser/releases/tag/v1.34.81

The nightly releases have a filename of `BraveBrowserStandaloneSilentNightlySetup.exe`, so they should be filtered out:
https://github.com/brave/brave-browser/releases/tag/v1.37.17

But, version `1.35.99` has the filename of a stable version:
https://github.com/brave/brave-browser/releases/tag/v1.35.99

So it seems like there is an issue on the brave infrastructure end, where not all nightly versions get the correct filename.

**Comment by Skatterbrainz** [comment]
No worries. I explained the issue to my customers and they understand. I will proceed with the public shaming of Brave on twitter. :)

**Comment by jonathansampson** [comment]
Hello, Sampson here (Developer Relations at Brave). Just wanted to preface this by saying we (at Brave) DO NOT manage the listing/package-manager discussed. That said, I would be more than happy to help determine recent builds from each channel. This was a challenge I had faced not too long ago when putting together https://sampson.codes/brave/latest/.

### Ask GitHub

One option is to ping GitHub directly. You can get a JSON representation of our recent releases via https://api.github.com/repos/brave/brave-browser/releases. Each release name includes both the channel and the version number. For example, "Nightly v1.37.15" informs us that this is version 1.37.15 _from the Nightly channel_. Naturally, you can split that string on spaces, and take the first two values as the channel and version respectively.

> Caveat: Just because "Release" is in the `name` doesn't mean the build is a release build; check the `prerelease` property as well (official releases also include *Release Notes* in their `body`.

### Ask Brave's Update Server

You can send a small XML payload to `https://updates.bravesoftware.com/service/update2` to determine the latest version for a given channel. Each channel has a distinct CLSID, which needs to be provided in the POST payload.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<request protocol="3" updaterversion="1" ismachine="1" sessionid="{$sGUID}" requestid="{$rGUID}" dedup="cr">
  <os platform="win" version="" sp="" arch="x64"/>
  <app appid="{$id}" version="" nextversion="" ap="{$ap}" lang="" brand="" client="">
    <updatecheck/>
  </app>
</request>
```

In the above, `$sGUID` and `$rGUID` can both be generated on the spot. They just need to conform to GUIDv4. The `$id` and `$ap` values will be based on the channel you're querying. Here's a section of code from a local PHP script:

```
case "release":
    $ap = "x64-rel";
    $id = "{AFE6A462-C574-4B8A-AF43-4CC60DF4563B}";
    break;
case "beta":
    $ap = "x64-be";
    $id = "{103BD053-949B-43A8-9120-2E424887DE11}";
    break;
case "dev":
    $ap = "x64-dev";
    $id = "{CB2150F2-595F-4633-891A-E39720CE0531}";
    break;
case "nightly":
    $ap = "x64-ni";
    $id = "{C6CB981E-DB30-4876-8639-109F8933582C}";
    break;
```

I hope this helps!

**Comment by AdmiringWorm** [comment]
Updating of the "stable" brave version has been disabled temporarily while we investigate how to proceed with the updating.

The Beta version updates are still enabled.

Asking the Brave update service may be an option, as suggested by @jonathansampson (thank you for that).
Using the GitHub JSON is unfortunately not an option due to the inconsistencies in how releases are being provided on the GitHub releases page (which is also what caused us to suddenly start picking up unstable versions, and what caused us to not pick up stable releases in the past).

**Comment by pauby** [comment]
@jonathansampson Thanks for clarifying that.

It seems like releases, particularly through GitHub, are inconsistent / in flux. Is there a potential for the process you mentioned above to be changed again in the near future or has it been settled on?

**Comment by jonathansampson** [comment]
@pauby Let me reach out to the release team for clarity. Expect a response soon 🙂

**Comment by jonathansampson** [comment]
After taking a closer look at the issue, I think I see the problem.

I queried for the 38 most recent "release" builds on GitHub for brave/brave-browser/. Of these, 33 contained a _StandaloneSilentSetup.exe_, and 5 did not. The 5 releases that did not contain that asset were all mobile builds (iOS and/or Android).

As such, simply ignoring any release that lacks a _StandaloneSilentSetup.exe_ should be sufficient to filter-out mobile builds. We intend to continue producing a _StandaloneSilentSetup.exe_ for all releases intended for Windows users.

**Comment by gep13** [comment]
Yes, there is a linked PR that was opened a few days ago, so this issue is still relevant.

**Comment by pauby** [comment]
@jonathansampson this endpoint (https://brave-browser-downloads.s3.brave.com/latest/release.version) is now broken - instead of returning the latest version it tries to download the software.

There was a lot of work put into reworking this package to use the endpoints. If we can't rely on the endpoint being consistent, we can't use it.

Are you able to provide a consistent, valid endpoint to query for stable releases and confirm that the beta releases URL [you mentioned above](https://github.com/chocolatey-community/chocolatey-packages/issues/1791#issuecomment-1030152913) is still valid?

**Comment by pattyland** [comment]
The answer seems to look very different depending on how you ask:
```powershell
PS H:\> (Invoke-WebRequest -Uri 'https://brave-browser-downloads.s3.brave.com/latest/release.version' -UseBasicParsing).Content
49
46
51
55
46
49
49
49
```

```
H:\>curl https://brave-browser-downloads.s3.brave.com/latest/release.version
1.37.111
```

Maybe depending on the user agent?

**Comment by pauby** [comment]
> It seems that was am temporary issue?

The `beta.version` endpoint continued working. It was the `release.version`  endpoint that changed.

The code _did_ work as I tested it prior to submitting the PR. A user agent for one and not the other endpoint doesn't make a lot of sense. And having to install curl on the automation machine isn't a great choice.

But you did pique my curiosity again. `Invoke-RestMethod` works:

```powershell
> irm https://brave-browser-downloads.s3.brave.com/latest/release.version
1.37.111
```
But how long for.

So there seems to be a working solution just now, and I can update the PR.

We are working around an issue that shouldn't exist. And doesn't exist consistently across the endpoints. Something has changed at the Brave end, and we're now jumping through hoops to follow and fix it. Do we do this again when it changes again tomorrow, next week, month? I don't want to have to keep coming back to update the code every time that happens.
