### ISSUE TITLE
choco uninstall python does not really uninstalls python

### ISSUE THREAD

**Issue by rgl** [chocolatey-community/chocolatey-packages#1797]
`choco uninstall python` does not really uninstalls python from the system.

## Expected Behavior

I expected python to be removed from the system.

## Current Behavior

```console
PS C:\Users\vagrant> choco uninstall -y python
Chocolatey v0.12.1
Uninstalling the following packages:
python

python v3.10.2
 Skipping auto uninstaller - No registry snapshot.
 python has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

## Steps to Reproduce (for bugs)

1. `choco install -y python` (this installed 3.10.2)
2. `choco uninstall -y python`

## Your Environment

* Package Version used: 3.10.2
* Operating System and version: Windows 2022
* Chocolatey version: 0.12.1
* Install/uninstall gist:

**Comment by rgl** [comment]
Oh, python is a "stub" package that depends on python3. Is there a way to uninstall python that triggers a python3 uninstall?

**Comment by AdmiringWorm** [comment]
As you noticed as well, `python` is a stub package or as we call them a `meta package`. Unfortunately, it is not a true meta-package, as those would have also removed the dependency (this is based on the naming).

To also remove the `python3` package when uninstalling `python` you need to pass in the argument `--remove-dependencies` as well. See https://docs.chocolatey.org/en-us/choco/commands/uninstall for what is available when calling `choco uninstall`.

From a packaging perspective, there isn't much we can do about this (short of creating duplicate packages), I'll be closing this issue now.
