### ISSUE TITLE
(palemoon) validation failing due to invalid URLs

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-packages#1801]
### Chocolatey Version

0.12.1

### Package Version

29.4.1 through 29.4.4

### Current Behaviour

Validation is failing because the `BugTrackerUrl`, `LicenseUrl` and `ProjectSourceUrl` are all invalid. They all 404 when viewed in a brower, so it is not a validator issue.

### Steps To Reproduce

View package page on CCR: https://community.chocolatey.org/packages/palemoon/29.4.4#versionhistory

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A
```

**Comment by pauby** [comment]
Versions 30.0.0 and 30.0.1 have since been approved. Closing this.
