### ISSUE TITLE
(libreoffice-fresh) Outdated

### ISSUE THREAD

**Issue by sazk07** [chocolatey-community/chocolatey-packages#1803]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

7.3.0

### Download location

https://www.libreoffice.org/download/download/

### Package Page

https://community.chocolatey.org/packages/libreoffice-fresh#versionhistory

**Comment by AdmiringWorm** [comment]
@wget as you are the one with the most knowledge about this package, is this something that you would be able to look into?

**Comment by RedBaron2** [comment]
@sazk07 @AdmiringWorm 
I'll quote the chocolatey wget discussion listed on the package page.
" ... The tacit distribution policy of TDF is as follow: distribute LibreOffice immediately via its website, but after some (1-2 weeks) delay, the update service is notified of the new version. ... "

The official release of the 7.3.0 version was completed according the the release schedule for LibreOffice on February 6, 2022. Figuring in the 2 week delay the beginning of March the package should become available through chocolatey.

**Comment by pauby** [comment]
I've raised the above PR to clarify the update cycle for this package. Good catch @RedBaron2.
