### ISSUE TITLE
(inkscape) package name error due to "Dotted and dotless I letter"

### ISSUE THREAD

**Issue by hkdemiralp** [chocolatey-community/chocolatey-packages#1805]
### Chocolatey Version

0.12.1

### Package Version

1.1.2

### Current Behaviour

Doing a `choco upgrade all -y` gives this failure message for inkscape in Windows OS using Turkic languages:
`Failures
 - ınkscape - ınkscape not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.`

### Expected Behaviour

"choco upgrade all -y" command should not give "ınkscape" error. The latest inkscape is already installed with chocolatey.

### Steps To Reproduce

1. choco install inkscape -y
2. choco upgrade all -y
3. `Failures
 - ınkscape - ınkscape not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.`
4.  Notice: in the chocolatey error message "ınkscape" word is also written with a dotless "I", not "i")

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22000.0
- PowerShell Version: 5.1.22000.282
- Shell:
```

### Chocolatey Log

```shell
https://gist.github.com/hkdemiralp/8943e8bb26d4cd3418de92795f60adf1
```

### Anything else?

I believe the problem is the package naming which exhibits the "[Dotted and dotless I" problem](https://en.wikipedia.org/wiki/Dotted_and_dotless_I). In Turkic languages, Dotted "İ i" and dotless "I ı" are distinct letters. If the name of the package would have been written in lovercase letters like "inkscape", instead of "InkScape", it would work just fine. Installing inkscape works but upgrading all packages gives the error message.

**Comment by AdmiringWorm** [comment]
This sounds more like a problem in the choco codebase at the moment than a problem with the package itself.

> If the name of the package would have been written in lovercase letters like "inkscape", instead of "InkScape", it would work just fine. Installing inkscape works but upgrading all packages gives the error message.

While that would possibly fix this issue, it, unfortunately, wouldn't be right to do that right now either.
The identifier `InkScape` is used on purpose now due to historical reasons.
The first time the package was introduced to CCR that was the casing that was in use, and because of a bug that is believed to be in the underlying framework used by choco, we need to continue to use the same casing that the first version submitted used.
See https://github.com/chocolatey/choco/issues/1040

**Comment by AdmiringWorm** [comment]
As it is a problem with the conversion between upper case and lower case characters done by Chocolatey, can you please open up an issue about that over at https://github.com/chocolatey/choco/issues so it can be looked into?

**Comment by hkdemiralp** [comment]
> As it is a problem with the conversion between upper case and lower case characters done by Chocolatey, can you please open up an issue about that over at https://github.com/chocolatey/choco/issues so it can be looked into?

Thanks. I opened up an issue as you said at https://github.com/chocolatey/choco/issues/2601
I don't know if I should close the issue here. Please feel free to close, if it is the way it shoul be.

**Comment by pauby** [comment]
Thanks @hkdemiralp. I'll go ahead and close this now.
