### ISSUE TITLE
(mumble) Package is failing Verification

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#1818]
### Chocolatey Version

0.11.2

### Package Version

1.4.230

### Current Behaviour

Package is failing Packager Verifier. I've pushed it back through again, but it's still [failing](https://gist.github.com/choco-bot/5a37917d948dcecbc5317d02ec3ecc3e#file-install-txt-L480-L497) with:

```
ERROR: Path doesn't exist: C:\Program Files\Mumble\mumble.exe
```

Running in a Windows 10 Sandbox, with Chocolatey CLI 0.12.1, gives the same error:

```
PS C:\Users\WDAGUtilityAccount> choco install mumble --version 1.4.230
Chocolatey v0.12.1
Installing the following packages:
mumble
By installing, you accept licenses for the packages.
Progress: Downloading mumble 1.4.230... 100%

chocolatey-core.extension v1.3.5.1
chocolatey-core.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-core extensions.
 The install of chocolatey-core.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-core'

mumble v1.4.230 - Possibly broken
mumble package files install completed. Performing other installation steps.
Installing mumble...
mumble has been installed.
mumble installed to 'C:\Program Files\Mumble'
ERROR: Path doesn't exist: C:\Program Files\Mumble\mumble.exe
  mumble may be able to be automatically uninstalled.
The install of mumble was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\mumble\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - mumble (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\mumble\tools\chocolateyInstall.ps1'.
 See log for details.
```

### Expected Behaviour

The package installs without error.

### Steps To Reproduce

1. `choco install mumble --version 1.4.230` (I'm assuming - this is from Package Verifier)

### Environment

```markdown
- Operating System: Server 2012R2
- PowerShell Version: 4.0 (from memory).
- Shell: PowerShell
```

### Chocolatey Log

See the [entire gist](https://gist.github.com/choco-bot/5a37917d948dcecbc5317d02ec3ecc3e#file-install-txt) and the [relevant text](https://gist.github.com/choco-bot/5a37917d948dcecbc5317d02ec3ecc3e#file-install-txt-L480-L497).

**Comment by AdmiringWorm** [comment]
This has been fixed in the repository, and a push has been scheduled for pushing it to CCR.
