### ISSUE TITLE
(python3) Incomplete permission lockdown

### ISSUE THREAD

**Issue by yan12125** [chocolatey-community/chocolatey-packages#1840]
### Chocolatey Version

Other (note in the comments)

### Package Version

3.9.12, 3.10.4 and likely other 3.x versions

### Current Behaviour

Installing python3 without arguments locks down permissions of C:\Python3X folder. Most sub-folders are still writable by authenticated users. For example, here are permissions of `C:\Python310\*`: https://pastebin.com/0hg7x2LB

### Expected Behaviour

All sub-folders under C:\Python3X are also locked down. Otherwise installed Python libraries can be injected.

### Steps To Reproduce

1. `choco install python3`
2. `icacls C:\Python310\*`

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19044.0
- PowerShell Version: 5.1.19041.1320
- Shell: PowerShell
- Chocolatey version: 1.1.0
```

### Chocolatey Log

```shell
https://gist.github.com/yan12125/6d7a920adec215a77f70af92d2f24cee
```

### Anything else?

At first I thought it's a security issue as the issue that introduced lockdown (https://github.com/chocolatey-community/chocolatey-packages/issues/1547) is a security issue, so I reported via "Report Abuse". Later, Paul Broadwith suggests me to report here instead.

**Comment by pauby** [comment]
As there has been no update on this issue, and nobody has picked it up, I'm going to go ahead and close it. We can always re-open it later.

**Comment by yan12125** [comment]
The issue still persists, but I may not be able to fix the issue by myself due to lack of knowledge about PowerShell scripts.
