### ISSUE TITLE
(brave) Fails to install when it tries to parse the version number

### ISSUE THREAD

**Issue by Larswa** [chocolatey-community/chocolatey-packages#1848]
### Chocolatey Version

0.12.1

### Package Version

1.37.111

### Current Behaviour

Brave installation fails when it tries to parse a version number with the .net type System.Version.  This is because the string fishing for a version number fails as Chrome has bumped their version from 2 to 3 digits  (99 to 100)

 I can see that the Brave version number everywhere in my Registry is prefixed with 100  (the upstream chrome version)   And we recently hit version 100  (3 digits instead of two)     The code that fishes for the clean Brave version looks like this     
`$key.Version[3..($key.Version.length - 1)]`

When it tries to parse the version number being  100.1.37.113  ...
That will return `.1.37.111`    ... and not `1.37.111` as intended

The string fishing needs to happen from the 4th character now that Chrome went from 99 to 100   Like this:
`$key.Version[4..($key.Version.length - 1)]` 

This should be good until Chrome hits 1000  😂

Could the maintainers please fix that in the helpers.ps1 file?

### Steps To Reproduce

Upgrade an existing Brave package where the browser already self updated with 100.1.37.113 or later.  

### Environment

```markdown
- Operating System: Windows 10/11
- PowerShell Version: 7.2.2
- Shell: Windows Terminal
```

### Chocolatey Log

```shell
Running 'ChocolateyScriptRunner' for brave v1.37.111 with packageScript 'C:\ProgramData\chocolatey\lib\brave\tools\chocolateyInstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\brave', installArguments: '', packageParameters: '',
2022-04-12 22:39:27,633 10464 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\brave\tools\chocolateyInstall.ps1'
2022-04-12 22:39:27,638 10464 [INFO ] - Checking already installed version...
2022-04-12 22:39:27,651 10464 [DEBUG] - Running 'Get-UninstallRegistryKey' for 'brave' with SoftwareName:'Brave*'
2022-04-12 22:39:27,652 10464 [INFO ] - VERBOSE: Retrieving all uninstall registry keys
2022-04-12 22:39:27,972 10464 [DEBUG] - Registry uninstall keys on system: 748
2022-04-12 22:39:27,973 10464 [DEBUG] - Error handling check: 'Get-ItemProperty' fails if a registry key is encoded incorrectly.
2022-04-12 22:39:28,244 10464 [DEBUG] - Found 1 uninstall registry key(s) with SoftwareName:'Brave*'
2022-04-12 22:39:28,259 10464 [ERROR] - ERROR: Cannot convert value ".1.37.111" to type "System.Version". Error: "Input string was not in a correct format."
```

**Comment by RedBaron2** [comment]
@Larswa 
Might I make a suggestion that the code be changed to be
`$installedVersion = $key.Version[0..($key.Version.length - 1)]`
This way no matter how large the version gets in the future the code will continue to function.

@chtof 
If you want to replace the code using a regex might I suggest `(\d+\.{0,1})`
This will also not limit the version number to any predetermined size.

**Comment by chtof** [comment]
Hello @RedBaron2,
Sorry, I didn't understand. My regex "\d+\.(.*)" only excludes the major version. My regex will not work if a day, the complete Brave version is "123" without minor version but is it really the problem?
Or maybe, your suggestion is to use your regex to use the complete version of Brave. Yes, I don't why why there was a choice to exclude the major version. But, in that case, perhaps we do not longer need your suggestions and we should use directly  $key.Version?

**Comment by RedBaron2** [comment]
@chtof 
I must have misunderstood the line of code from your PR. I made the assumption that the version from the registry was the same as the version of the package.
My suggestion wasn't mean to cause any harm.

**Comment by slycordinator** [comment]
I think we can close this, since the pull request that fixes the issue was merged.

**Comment by AdmiringWorm** [comment]
> I think we can close this, since the pull request that fixes the issue was merged.

We haven't pushed up the fix to the community website yet, so until we plan to push up a fix version or when there is a new release of brave available let us keep this open.

**Comment by AdmiringWorm** [comment]
A package fix version that includes the changes for this issue has been pushed to CCR. THere will be some time before it completes moderation.

I'll be closing this issue now.
