### ISSUE TITLE
(musicbee) download hash error

### ISSUE THREAD

**Issue by zhengda-skinny** [chocolatey-community/chocolatey-packages#1855]
### Chocolatey Version

1.1.0

### Package Version

3.4.7805

### Current Behaviour

Here is the error. 

PS C:\WINDOWS\system32> choco install musicbee
Chocolatey v1.1.0
Installing the following packages:
musicbee
By installing, you accept licenses for the packages.
Progress: Downloading musicbee 3.4.7805... 100%

musicbee v3.4.7805 [Approved]
musicbee package files install completed. Performing other installation steps.
The package musicbee wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was '7E27686A6EC6B4447846B58397CD19062F333EF89DD50CB310DD49682E9C17FD'.
Downloading musicbee
  from 'https://www.mediafire.com/file/a2bnughg9i2sv4u/MusicBeeSetup_3_4_Update1.zip'
WARNING: C:\Users\goalo\AppData\Local\Temp\chocolatey\musicbee\3.4.7805\file is of content type text/html; charset=UTF-8

Download of file (-1 B) completed.
Error - hashes do not match. Actual value was '8A1E8934BDC25F7F1B3CEF14130EF7E182E2DD9A6B205C87AF685A351659EEF5'.
ERROR: Checksum for 'C:\Users\goalo\AppData\Local\Temp\chocolatey\musicbee\3.4.7805\file' did not meet '405010d8a387e20aa5754b14732f37008a7733e646aa9c4290cf8dcb53e4003f' for checksum type 'sha
256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessar
y.
The install of musicbee was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - musicbee (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1'.
 See log for details.

### Steps To Reproduce

Run "choco install musicbee"

### Environment

```markdown
- Operating System: Win10
- PowerShell Version: 1
- Shell:
```

### Chocolatey Log

```shell
https://gist.github.com/zhengda-skinny/041bf6909c6e025d6a36f95130f5d7e8
```

**Comment by AdmiringWorm** [comment]
The package musicbee is not maintained by us in this repository, you'll need to contact the actual maintainer of the package to get the package fixed.

You can do that using `Contact Maintainers` or using the listed Package Source on the details page for this package.

Because we are not maintaining the package, I will be closing this issue now.
