### ISSUE TITLE
(NodeJs) Update to V18.0.0

### ISSUE THREAD

**Issue by destroyAUniverse** [chocolatey-community/chocolatey-packages#1864]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

18.0.0

### Download location

https://nodejs.org/en/download/current/

### Package Page

https://community.chocolatey.org/packages/nodejs

**Comment by AdmiringWorm** [comment]
I had a quick look into it, and it seems it is because the the x86 binary they are linking to on the website doesn't exist.

As we support both 64bit and 32bit, we need to wait until that binary exist, or until there are official notice from the developers that 32bit is no longer supported before we can push any changes.

**Comment by argrath** [comment]
I think this blog is official.

https://nodejs.org/en/blog/release/v18.0.0/

> Prebuilt binaries for 32-bit Windows will initially not be available due to issues building the V8 dependency in Node.js.  
We hope to restore 32-bit Windows binaries for Node.js 18 with a future V8 update.

**Comment by AdmiringWorm** [comment]
Unfortunately, that does not change anything.

As mentioned in the blog post, it won't be initially available but may be brought back in a future version.

If we drop 32bit support, that will be a permanent change, and it won't be brought back at a later date.
We also have a history of not dropping 32bit or 64bit support until it is officially dropped permanently by the software authors (except in rare cases, for instance, if one of the executables have a lot of positives for anti-virus scans on virustotal).

**Comment by TheCakeIsNaOH** [comment]
Nodejs 18.3.0 is now available on the community repository:
![image](https://user-images.githubusercontent.com/38865330/172953642-2d11203c-3972-433b-a1cc-cc6277aded1a.png)

It looks like they got their 32 bit build issues worked out.
