### ISSUE TITLE
(vlc) latest update of package throws a warning about source(s).

### ISSUE THREAD

**Issue by hchorey** [chocolatey-community/chocolatey-packages#1866]
### Chocolatey Version

1.1.0

### Package Version

upgrading to 3.0.17.4

### Current Behaviour

As of the most recent upgrade of the vlc package to 3.0.17.4 (released on 20-Apr-2022 | https://community.chocolatey.org/packages/vlc), upgrading either via "choco upgrade vlc" or "choco upgrade all" throws the following warning upon upgrade:

```
vlc.install was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://chocolatey.org/api/v2/"
```

Verbose logs give the following additional information:
 
```
Warnings:
 - vlc.install - vlc.install was not found with the source(s) listed.
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 0 
```
The package appears to have been installed just fine, but subsequently running "choco upgrade all" will continue to throw this warning.  For the record, I did not specify a particular version, just the usual "choco upgrade vlc" / "choco upgrade all".

### Expected Behaviour

vlc package would upgrade with no warning, and subsequent attempt to upgrade after successful install without a new package version would also not continue to throw a warning.

### Steps To Reproduce

1.) on Windows 10 (tested on Home and Professional), load an elevated terminal / PowerShell / Cmdr window.
2.) If not yet installed, run "choco install vlc"; if already installed, run "choco upgrade vlc" or "choco upgrade all".
3.) see warning of the following at the end of the upgrade process:

```
vlc.install was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "https://chocolatey.org/api/v2/"
```

### Environment

```markdown
- Operating System: Windows 10 Home 21H2; Windows 10 Professional latest version
- PowerShell Version: 7.2.3
- Shell: Terminal / PowerShell; same behavior in Cmdr
```

### Chocolatey Log

```shell
https://gist.github.com/hchorey/8b369d8155c7b72dde405a922fc3867a
```

### Anything else?

I initially made a discussion here, but converted it to an issue.  :)

https://github.com/chocolatey-community/chocolatey-packages/discussions/1865

**Comment by AdmiringWorm** [comment]
Unfortunately, this is something that is out of our hands in this case.

The problem here is that the `vlc` package is approved, however this is just a meta package which depends on the package [`vlc.install`](https://community.chocolatey.org/packages/vlc.install/3.0.17.4), and until this package is approved there is unfortunately not much we can do.

Also, please refrain from converting a discussion into an issue in the future. Leave that up to us to do when it is necessary. I will be closing this issue, but leave the discussion open (to which I'll add the same response).
