### ISSUE TITLE
Winrar 6.11 has wrong (possibly old) checksums

### ISSUE THREAD

**Issue by pitsi** [chocolatey-community/chocolatey-packages#1873]
### Chocolatey Version

1.1.0

### Package Version

6.11

### Current Behaviour

As seen in the log below, the checksum for winrar are different, so choco has to be issued with the --ignore-checksums parameter to continue the installation.

### Expected Behaviour

The chocolatey package should have the correct checksums for winrar and their verification should pass.

### Steps To Reproduce

1. Just run `choco install winrar`.
2. Notice the output that is similar to the log below.

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19044.0
- PowerShell Version: 5.1.19041.1682
- Shell: Powershell
```

### Chocolatey Log

```shell
Downloading winrar 64 bit
  from 'https://www.rarlab.com/rar/winrar-x64-611el.exe'
Progress: 100% - Completed download of C:\Users\user\AppData\Local\Temp\chocolatey\winrar\6.11\winrar-x64-611el.exe (3.38 MB).
Download of winrar-x64-611el.exe (3.38 MB) completed.
Error - hashes do not match. Actual value was '31DAA9F63B084D70EA66A578BBD590ED646EB39ED17E899F0808DDD19B741988'.
ERROR: Checksum for 'C:\Users\user\AppData\Local\Temp\chocolatey\winrar\6.11\winrar-x64-611el.exe' did not meet '2b66d5eefe3c9ec9139f74f569ea8f863dfc2f81381baa1a6fda1e755ae39810' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
  winrar may be able to be automatically uninstalled.
The install of winrar was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winrar\tools\chocolateyInstall.ps1'.
```

### Anything else?

Something must have changed in winrar's setup files, although their version remained the same.
I had downloaded and stored the forementioned installation file locally when v6.11 was released and its checksum was indeed the one that comes with the chocolatey package.

**Comment by TheCakeIsNaOH** [comment]
@pitsi winrar is not maintained by the `chocolatey-community` user, so this is not the correct repository.

See the package page for a link to contact the maintainers, and a link to the correct package source repository:
https://community.chocolatey.org/packages/winrar

**Comment by pitsi** [comment]
You are right. Although I did check if there are other issues related to winrar, I did not read their context.
