### ISSUE TITLE
(filezilla) File links are invalid

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#1881]
### Discussed in https://github.com/chocolatey-community/chocolatey-packages/discussions/1880

<div type='discussions-op-text'>

<sup>Originally posted by **uwemolnar** May  9, 2022</sup>
As requested by the maintainer of filezilla: the installer-links for filezilla seem to be outdated. Can you please check and fix them:
https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/filezilla/legal/VERIFICATION.txt

Would be great - thanks!</div>

**Comment by pauby** [comment]
@AdmiringWorm As the author seems to be going out of their way to make this difficult to package (assuming I understand this correctly) if this is a package we want to stop maintaining here? I'm happy to raise an RFM request for it.

**Comment by pauby** [comment]
Submitted PR #2166 to fix this.

**Comment by pauby** [comment]
Sure.

**Comment by michael-franck** [comment]
Submitted PR #2316 to fix this.
