### ISSUE TITLE
(sysinternals) - `procexp` - Upgrade Fail When Open

### ISSUE THREAD

**Issue by mattcargile** [chocolatey-community/chocolatey-packages#1884]
### Chocolatey Version

1.1.0

### Package Version

2022.5.11

### Current Behaviour

Application includes feature to replace _Task Manager_ with `procexp`. `choco upgrade sysinternals` doesn't close the application and fails.

```powershell
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path 'procexp.exe' is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'procexp.exe' is denied.
Maximum tries of 3 reached. Throwing error.
Attempted to remove 'C:\ProgramData\chocolatey\lib-bkp\sysinternals' but had an error::
 Access to the path 'procexp.exe' is denied.
 The upgrade of sysinternals was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\sysinternals\tools'
```

P.S. It would be nice if the upgrade would kill any `exe` within `sysinternals`. I think `procexp` is more important because it has a feature to remain open and replace _Task Manager_ while other applications would typically be closed ( maybe ).

### Expected Behaviour

It would be ideal if `choco` would kill the `procexp` before upgrade.

### Steps To Reproduce

1. Environment doesn't appear to be relevant
2. Open `procexp` 
3. Run `choco upgrade sysinternals`

### Environment

```markdown
- Operating System:Microsoft Windows NT 10.0.19043.0
- PowerShell Version:
[32;1mName                           Value[0m
[32;1m----                           -----[0m
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
- Shell:pwsh
```

### Chocolatey Log

```shell
N/A
```

### Anything else?

N/A

**Comment by AdmiringWorm** [comment]
This issue should have been opened as an enhancement to the package instead of a bug so that it could be a discussion around the implementation or need for the enhancement first.

However, I believe this is a worthwhile addition to the package.
I have marked it as `up for grabs` for anyone interested in adding this functionality to the package (Likely through a `chocolateyBeforeModify.ps1` script).
