### ISSUE TITLE
virtualbox

### ISSUE THREAD

**Issue by Smakke1** [chocolatey-community/chocolatey-packages#1889]
### Chocolatey Version

Other (note in the comments)

### Package Version

6.1.34

### Current Behaviour

Virtualbox failed during installation:

VirtualBox-6.1.34-150636-Win.exe: error: Installation failed! **Error: Fatal error during installation.**
Microsoft.PowerShell.Commands.WriteErrorException
Command ["C:\Users\username\AppData\Local\Temp\chocolatey\virtualbox\6.1.34\VirtualBox-6.1.34-150636-Win.exe" -s -l -msiparams REBOOT=ReallySuppress ALLUSERS=1 ] exited with '1'.
ERROR: Running ["C:\Users\username\AppData\Local\Temp\chocolatey\virtualbox\6.1.34\VirtualBox-6.1.34-150636-Win.exe" -s -l -msiparams REBOOT=ReallySuppress ALLUSERS=1 ] was not successful. Exit code was '1'. See log for possible error messages.
Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '1'.
Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'
Capturing package files in 'C:\ProgramData\chocolatey\lib\virtualbox'
...

### Expected Behaviour

Succesfull install

### Steps To Reproduce

1. Envirnoment: Windows 10
2. Run: choco.exe install virtualbox -y
3. VirtualBox-6.1.34-150636-Win.exe: error: Installation failed! **Error: Fatal error during installation.**
Microsoft.PowerShell.Commands.WriteErrorException
Command ["C:\Users\username\AppData\Local\Temp\chocolatey\virtualbox\6.1.34\VirtualBox-6.1.34-150636-Win.exe" -s -l -msiparams REBOOT=ReallySuppress ALLUSERS=1 ] exited with '1'.
ERROR: Running ["C:\Users\username\AppData\Local\Temp\chocolatey\virtualbox\6.1.34\VirtualBox-6.1.34-150636-Win.exe" -s -l -msiparams REBOOT=ReallySuppress ALLUSERS=1 ] was not successful. Exit code was '1'. See log for possible error messages.
Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '1'.
Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'
Capturing package files in 'C:\ProgramData\chocolatey\lib\virtualbox'
...

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19044.0
- PowerShell Version: 5.1.19041.1682
- Shell:CMD
```

### Chocolatey Log

```shell
https://gist.github.com/Smakke1/877fbb333a20460b274380e6662e1d81
```

### Anything else?

Chocolatey version v0.10.15

**Comment by AdmiringWorm** [comment]
@Smakke1 Are you still seeing this problem?

This issue had unfortunately gone unnoticed until now, but it is a issue that can be impossible to fix due to the only information given is that it exits with a code of `1`.
From my experience though, almost all failures I have seen with the virtual box installer is related to your own environment, and the only thing I can recommend to try is to install the package as not silent.

That is call: `choco install virtualbox --not-silent`

**Comment by slycordinator** [comment]
> @Smakke1 Are you still seeing this problem?
> 
> This issue had unfortunately gone unnoticed until now, but it is a issue that can be impossible to fix due to the only information given is that it exits with a code of `1`. From my experience though, almost all failures I have seen with the virtual box installer is related to your own environment, and the only thing I can recommend to try is to install the package as not silent.
> 
> That is call: `choco install virtualbox --not-silent`

I was having the same problem with attempting to upgrade virtualbox from 6.1.34 -> 6.1.36 with the same error.

When I ran choco upgrade virtualbox --not-silent, I got a repair/uninstall dialog because 6.1.36 was actually already installed.

And then after clicking forward to run a repair, the normal gui asked if I wanted to download/install guest additions, and after those additions were upgraded I got a "Installation failed! Error: Fatal error during installation." popup.

Also, running "choco uninstall virtualbox" came up with the same error (and with virtualbox not uninstalled).

After uninstalling the existing install manually, it could be installed through choco.

**Comment by gthieleb** [comment]
This issue still exists with VirtualBox-7.0.4:

This issue still exists with VirtualBox-7.0.4:

```
Downloading virtualbox 64 bit
  from 'https://download.virtualbox.org/virtualbox/7.0.4/VirtualBox-7.0.4-154605-Win.exe'
Progress: 100% - Completed download of C:\Users\user\AppData\Local\Temp\chocolatey\virtualbox\7.0.4\VirtualBox-7.0.4-154605-Win.exe (105.18 MB).
Download of VirtualBox-7.0.4-154605-Win.exe (105.18 MB) completed.
Hashes match.
Installing virtualbox...
Microsoft.PowerShell.Commands.WriteErrorException
VirtualBox-7.0.4-154605-Win.exe: error: Installation failed! Error: Fatal error during installation.
ERROR: Running ["C:\Users\user\AppData\Local\Temp\chocolatey\virtualbox\7.0.4\VirtualBox-7.0.4-154605-Win.exe" -s -l -msiparams REBOOT=ReallySuppress ALLUSERS=1 ] was not successful. Exit code was '1'. See log for possible error messages.
The install of virtualbox was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.
 See log for details.
```

**Comment by CodingAlphaWolf** [comment]
I've got the same issue mentioned above.

-----------------------------------------------
VirtualBox-7.0.6-155176-Win.exe: error: Installation failed! Error: Fatal error during installation.
Microsoft.PowerShell.Commands.WriteErrorException
ERROR: Running ["C:\Users\Administrator\AppData\Local\Temp\chocolatey\virtualbox\7.0.6.20230201\VirtualBox-7.0.6-155176-Win.exe" -s -l -msiparams REBOOT=ReallySuppress ALLUSERS=1 ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of virtualbox was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by pauby** [comment]
This issue is closed. Please raise a new issue if you need to report a problem. Thanks.
