### ISSUE TITLE
(smartftp) vcredist2015 exemption no longer required

### ISSUE THREAD

**Issue by matbech** [chocolatey-community/chocolatey-packages#1891]
### Chocolatey Version

1.1.0

### Package Version

All

### Current Behaviour

The exemption:
Verification Testing Exemption:
vcredist2015 need Update KB2919355 installed first.
is no longer required as the package no longer depends on vcredist.

### Expected Behaviour

No exemption.

### Steps To Reproduce

Not required.

### Environment

```markdown
Irrelevant
```

### Chocolatey Log

```shell
Irrelevant
```

**Comment by gep13** [comment]
@matbech That is a good point.  I have removed the package-verifier testing exemption from this package.
