### ISSUE TITLE
(lockhunter) checksum error

### ISSUE THREAD

**Issue by JVimes** [chocolatey-community/chocolatey-packages#1892]
### Chocolatey Version

1.1.0

### Package Version

3.4.3.147

### Current Behaviour

`cinst lockhunter` gives:

    Download of lockhuntersetup_3-4-3.exe (3.22 MB) completed.
    Error - hashes do not match. Actual value was '982DDA5EEC52DD54FF6B0B04FD9BA8F4C566534B78F6A46DADA624AF0316044E'.

### Expected Behaviour

Package installs

### Steps To Reproduce

Run `cinst lockhunter`.

### Environment

```markdown
- Operating System: Version 21H2 (OS Build 19044.1706)
- PowerShell Version: 5.1.19041.1682
- Shell: PowerShell
```

### Chocolatey Log

```shell
https://gist.github.com/JVimes/582b3c47429f53865f7a1b72b4e074b2
```

### Anything else?

Other's have this issue in the Disqus comments at:
https://community.chocolatey.org/packages/lockhunter

**Comment by AdmiringWorm** [comment]
A new version of lockhunter is being queued to be pushed to the Chocolatey Community Repository.
There will be a few hours until it is available for normal consumption.
