### ISSUE TITLE
(smartftp) Verification testing fails on unsupported OS

### ISSUE THREAD

**Issue by matbech** [chocolatey-community/chocolatey-packages#1893]
### Chocolatey Version

1.1.0

### Package Version

10.0.2973.0

### Current Behaviour

The verification test fails:
Verification Testing Failed
https://community.chocolatey.org/packages/smartftp/10.0.2973.0

The problem is that the validation runs on Windows Server 2012:
Tested against win2012r2x64 (Windows Server 2012 R2 x64)

However, SmartFTP requires Windows 10 Build 14393 or higher:
https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/smartftp/tools/chocolateyInstall.ps1#L3T

From this page it seems the package verifier uses
Windows Server 2012 R2 x64
https://docs.chocolatey.org/en-us/community-repository/moderation/package-verifier

Could you add back an exemption, bypassing the Verifier?

### Expected Behaviour

Verification Testing should not fail

### Steps To Reproduce

na

### Environment

```markdown
na
```

### Chocolatey Log

```shell
na
```

**Comment by pauby** [comment]
This isn't an issue with the package, but of the Package Verifier. I've added an exemption.
