### ISSUE TITLE
(libreoffice-fresh) Outdated

### ISSUE THREAD

**Issue by slycordinator** [chocolatey-community/chocolatey-packages#1917]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

7.3.4

### Download location

https://www.libreoffice.org/download/download/

### Package Page

https://community.chocolatey.org/packages/libreoffice-fresh

**Comment by AdmiringWorm** [comment]
Please see the Notes section of the package to know why there is no version:

> This package relies on the update service provided by The Document Foundation to determine new updates. As their policy is to distribute to their website immediately and to the update service after 1 to 2 weeks, there will be a delay between a new software update and a new version release of the package.

It will be updated as soon as the developers update their own update service (the same used by LibreOffice itself when determining updates being available).

I'll be closing this issue, as it is currently out of our hands. We can always open the issue again at a later date.
