### ISSUE TITLE
(Nuget.CommandLine) Outdated

### ISSUE THREAD

**Issue by miketimofeev** [chocolatey-community/chocolatey-packages#1921]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

6.2.1

### Download location

https://dist.nuget.org/win-x86-commandline/v6.2.1/nuget.exe

### Package Page

https://community.chocolatey.org/packages/NuGet.CommandLine

**Comment by AdmiringWorm** [comment]
THank you for creating this issue, I had a look to see what was happening.

Seems that when we tried to push this version, it had failed to push but other versions had successfully been pushed instead, so it thought it had been successful and never tried again.

I'll get the version reset so it will try pushing the 6.2.1 version again.

**Comment by AdmiringWorm** [comment]
v6.2.1 was just pushed to Chocolatey Community Repository now, and should be available for normal consumption in a few hours:

https://community.chocolatey.org/packages/NuGet.CommandLine/6.2.1
