### ISSUE TITLE
(freecad) auto update appears broken

### ISSUE THREAD

**Issue by adrianinsaval** [chocolatey-community/chocolatey-packages#1922]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

0.20

### Download location

https://github.com/FreeCAD/FreeCAD/releases/download/0.20/FreeCAD-0.20.0-WIN-x64-installer-1.exe

### Package Page

https://community.chocolatey.org/packages/freecad

**Comment by adrianinsaval** [comment]
auto update seems broken, it doesn't pickup the dev releases either:
https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds
possible due to some naming scheme change?

**Comment by RedBaron2** [comment]
@adrianinsaval 
Thanks for bringing this to our attention. I'll look more into this issue this week. Hopefully it is just a speed bump.

**Comment by adrianinsaval** [comment]
I'm still not seeing the new versions of the package in the chocolatey page, is this actually fixed? @RedBaron2 
how often is the auto update supposed to run? I'd like to know so I know how long to wait in the future before assuming something broke

**Comment by RedBaron2** [comment]
@adrianinsaval 
According to the appveyor schedule for the chocolatey packages. The script is ran every 6 hours. The problem is due to a limitation of chocolatey not allowing the push for the package. I'm hoping that @AdmiringWorm, or @gep13 might know what is causing the fault. There have been changes to the description since the last update but the character count is well below 4,000.
Hopefully we all will know something soon.
