### ISSUE TITLE
(waterfox) No Windows integration, it behaves like a .portable package

### ISSUE THREAD

**Issue by NWCR** [chocolatey-community/chocolatey-packages#1934]
### Chocolatey Version

1.1.0

### Package Version

22024.0.7 -> 22064.1.3.1

### Current Behaviour

Since version 22024.0.7 clean installation of the waterfox package does not integrate with the Windows system. It behaves like a '.portable' package. For example when I press `⊞ Win`+`R` , type `waterfox` and press `Enter` this message will appear:

> Windows cannot find 'waterfox'. Make sure you typed the name correctly, and then try again.

However after running following commands:
```
choco uninstall waterfox 
choco install waterfox --version 22024.0.6
choco upgrade waterfox
```
`⊞ Win`+`R` , `waterfox` and `Enter` works as expected -> opening waterfox browser.

### Steps To Reproduce

1. If the waterfox package is already installed then run: `choco uninstall waterfox`
2. Run `choco install waterfox`
3. After installation there is no system integration
4. Bellow commands fix the problem: 
5. `choco uninstall waterfox`
6. `choco install waterfox --version 22024.0.6`
7. `choco upgrade waterfox`

### Possible Solution

I think that the previous behavior of `choco install waterfox` was changed by this commit: https://github.com/chocolatey-community/chocolatey-packages/commit/edfb72aa469600b2bb08257cf22a8e2abd5b3746#diff-e191877d81c80a1912cfc1b17693f047f0b6a0ac89323818bdb6c78ba95ef9ab

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22000.0
- PowerShell Version: 5.1.22000.653
```

### Chocolatey Log

```shell
https://gist.github.com/NWCR/dccf4148e9af06bd961cdc957b450b43
```

**Comment by AdmiringWorm** [comment]
Thank you for reporting this, looks to be an oversight when waterfox update script was last updated and it picked up the wrong version of the application.

I'll look into getting this fixed.
