### ISSUE TITLE
(git.install) Terminate gpg-agent as part of install?

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-packages#1938]
### Discussed in https://github.com/chocolatey-community/chocolatey-packages/discussions/1924

<div type='discussions-op-text'>

<sup>Originally posted by **brogers5** June 21, 2022</sup>
I originally raised this issue in the form of a [comment in #1451](https://github.com/chocolatey-community/chocolatey-packages/issues/1451#issuecomment-1159620838), but spinning off into a discussion per @TheCakeIsNaOH's request.

TL;DR: the `git.install` package has had a recurring issue with Git for Windows installations that have enabled signing commits with a GPG key. This spawns a background process (`gpg-agent.exe`) that must be manually closed by the user in order to upgrade the software. The package contains a `chocolateyBeforeModify.ps1` script to handle stopping this process, but this script only runs when `git.install` is upgraded directly. [If indirectly upgraded via the metapackage (i.e `git`), the script does not run](https://github.com/chocolatey/choco/issues/1092), and consequently the package fails to upgrade.

As a fix for the upstream issue does not appear to be planned for release soon, I'd like to propose we extract the `gpg-agent` termination code from `chocolateyBeforeModify.ps1`, encapsulate it within a function defined in `helpers.ps1`, and call the function from both `chocolateyBeforeModify.ps1` (to handle direct upgrades/uninstalls) and `chocolateyInstall.ps1` (as a workaround for indirect upgrades) to facilitate a smoother upgrade experience.

Thoughts?

**EDIT:** I'm also willing to own pull request creation if approved.</div>

**Comment by brogers5** [comment]
👋
