### ISSUE TITLE
(freecad) Package is too large to be pushed to Community Repository 

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-packages#1941]
### Chocolatey Version

1.1.0

### Package Version

0.20.0.29393-dev

### Current Behaviour

When trying to update the package through our updater, it downloads and tries to embed a file that is `662 MB` in file. This causes pushing the package to community.chocolatey.org to fail with a message that the `Request Entity Too Large` due to Chocolatey Community Repository have a 200MB limit.
Looking at the code, it seems to be a mistake that the file is embedded inside the package.

### Expected Behaviour

The package should be pushed to Chocolatey Community Repository successfully.

### Steps To Reproduce

1. Run `.\update.ps freecad`
2. Look in the `automatic/freecad/tools` folder and notice the size of the executable.

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A
```

### Anything else?

I will temporarily disable the freecad updater until this issue is fixed.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Working on it

**Comment by RedBaron2** [comment]
@AdmiringWorm 
The PR is ready for you to review
