### ISSUE TITLE
(calibre) 6.0 is out

### ISSUE THREAD

**Issue by cam1170** [chocolatey-community/chocolatey-packages#1949]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

6.0.0

### Download location

https://github.com/kovidgoyal/calibre/releases/download/v6.0.0/calibre-64bit-6.0.0.msi

### Package Page

https://community.chocolatey.org/packages/calibre

**Comment by cam1170** [comment]
6.1 is out now. Also, even though this is an automatic package, it is out of date, so something must be broken. I don't know how to fix these things.

**Comment by gep13** [comment]
@cam1170 there is an open PR to update Calibre to the latest version:

https://github.com/chocolatey-community/chocolatey-packages/pull/1947

There was a change in the way that Calibre is published, which meant it wasn't picked up automatically.

**Comment by cam1170** [comment]
I wish I knew how chocolatey's automatic packaging worked, geez. Relevant blockage here https://github.com/chocolatey-community/chocolatey-packages/pull/1947#pullrequestreview-1033954306

**Comment by cam1170** [comment]
Oh, seems to be up to AdmiringWorm to review the PR again after the fixes
