### ISSUE TITLE
(brackets) is outdated (current release 2.1.2), not maintained by Adobe anymore, github repo changed

### ISSUE THREAD

**Issue by 360path** [chocolatey-community/chocolatey-packages#1950]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

2.1.2

### Download location

https://github.com/brackets-cont/brackets/releases

### Package Page

https://community.chocolatey.org/packages/Brackets

**Comment by AdmiringWorm** [comment]
Since there is no official handover from what I can see, this would need to be a completely new package, with the existing package becoming deprecated (possibly to depend on the new package).
