### ISSUE TITLE
VirtualBox install causes crash/BSOD

### ISSUE THREAD

**Issue by Leif-W** [chocolatey-community/chocolatey-packages#1951]
### Chocolatey Version

1.1.0

### Package Version

6.1.34 -> 6.1.36

### Current Behaviour

System crash, BSOD and reboot, log file has some related lines, then many NUL characters afterwards, until after reboot.  Corrupted chocolatey says 'Unable to read package from path 'virtualbox-guest-additions-guest.install/virtualbox-guest-additions-guest.install.nupkg'` when trying to install or remove `virtualbox` or `virtualbox-guest-additions-guest.install`.  Unable to install or uninstall virtualbox.  Error message appears with almost every command run, e.g. `outdated`.

### Expected Behaviour

Not a system crash, no BSOD, possibly no reboot.  If a crash, no corrupted chocolatey state that prevents installation or removal.

### Steps To Reproduce

1. VirtualBox 6.1.34 installed.
2. VirtualBox Guest Additions 6.1.34 installed.
3. `choco outdated` shows 6.1.36 available for both.
4. `choco upgrade all -y` begins downloads and upgrades.
5. After some installation, system suddenly crashes, BSOD comes up, system reboots.
6. `chocolatey.log` has some NUL characters after final textual log message.
7. Can't install or uninstall VirtualBox using Chocolatey.

### Environment

```markdown
- Operating System: Windows 10 64-bit (10.0.19043.1826)
- PowerShell Version: 5.1.19041.1682
- Shell: Command Prompt
```

### Chocolatey Log

```shell
https://gist.github.com/Leif-W/249c743f8224a180094dd935f1a27026
```

### Anything else?

![Chocolatey VirtualBox Missing nupkg](https://user-images.githubusercontent.com/979392/180077838-2c0a70dd-53d1-499e-8ddd-9821cd197ce3.png)

**Comment by TheCakeIsNaOH** [comment]
@Leif-W the `virtualbox` package is maintained in this repository, but the error you are showing shows `virtualbox-guest-additions-guest.install` as being the package that is corrupted, and presumably caused the BSOD. You should be able to fix Chocolatey by deleting the `$env:ChocolateyInstall\lib\virtualbox-guest-additions-guest.install` directory.

The `virtualbox-guest-additions-guest.install` package is not maintained in this repository, it is maintained over here: https://github.com/pauby/ChocoPackages

It looks like it is a known issue with the software installer that it can BSOD the operating system during install:
https://forums.virtualbox.org/viewtopic.php?f=7&t=106533
https://www.reddit.com/r/virtualbox/comments/w25yep/guest_bsod_while_installing_windows_10_linux_host/

So it is an issue with upstream virtualbox project, not an issue with the Chocolatey package.

**Comment by Leif-W** [comment]
Both forum links are unrelated.  Those are for VirtualBox running on Linux, crashing when running Windows as a Guest.  Maybe related, but maybe not, definitely not the same scenario.  I am running on Windows as a Host, trying to install Guest Additions on windows, for other guest OSes.  But even if related, they show the cause as VirtualBox crashing, not just the guest additions.  The post also indicates that 6.1.36 likely resolved the issue mentioned in those other posts, which is not the case in this scenario.  So it is ambiguous, whether it is the upstream VirtualBox, this virtualbox package, or the upstream VirtualBox Guest Additions, or the virtualbox-guest-additions-guest.install package.

**Comment by TheCakeIsNaOH** [comment]
@Leif-W ah, that is part of your problem. The Virtualbox Guest Additions should only be installed on Guest OSes.
