### ISSUE TITLE
(rockbox) update available

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-packages#1959]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

version 1.5.1

### Download location

https://www.rockbox.org/wiki/RockboxUtility#Download

### Package Page

https://community.chocolatey.org/packages/rockbox

**Comment by RedBaron2** [comment]
@mstick99 
This package is not maintained here, but by mlt.

**Comment by AdmiringWorm** [comment]
As @RedBaron2 mentioned, this package is not maintained in this repository. To get it updated or fixed you will need to contact the maintainer of the package.

You can do that by using the `Contact Maintainers` on the package details package.

I will be closing this issue as it is not relevant for this repository.
