### ISSUE TITLE
(ccleaner) Installing 5.92.9652 vs 6.02.9938

### ISSUE THREAD

**Issue by moklinowski** [chocolatey-community/chocolatey-packages#1964]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

6.02.9938

### Download location

https://www.ccleaner.com/ccleaner/download/standard

### Package Page

https://community.chocolatey.org/packages/ccleaner

**Comment by pauby** [comment]
This will be fixed by https://github.com/chocolatey-community/chocolatey-packages/issues/1960.
