### ISSUE TITLE
(ccleaner) Is: 5.92.9652 available: 6.02.9938

### ISSUE THREAD

**Issue by forenta** [chocolatey-community/chocolatey-packages#1968]
A message just dropped from CCleaner that 3 updates have already been missed and the installed version is significantly out of date.

### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

6.02.9938

### Download location

https://www.ccleaner.com/de-de/ccleaner/update?v=5.92.9652

### Package Page

https://community.chocolatey.org/packages/ccleaner

**Comment by brogers5** [comment]
This is outdated because the auto-update script for CCleaner is currently broken (see #1960). I have a pull request currently awaiting review to resolve this. Once a fix is merged in, this should be resolved after the next scheduled update run.

**Comment by TheCakeIsNaOH** [comment]
@forenta an updated CCleaner package, version `6.02.9938`, has been pushed and is approved thanks to the PR from @brogers5.
