### ISSUE TITLE
(libreoffice-still) Showing the same as the Fresh version

### ISSUE THREAD

**Issue by PaulWalkerUK** [chocolatey-community/chocolatey-packages#1969]
### Chocolatey Version

1.1.0

### Package Version

7.3.5

### Current Behaviour

The community repository is showing the current version of "libreoffice-still" as 7.3.5 - the same as "libreoffice-fresh". According to https://www.libreoffice.org/download/release-notes/ "libreoffice-still" should still be on 7.2.7

### Expected Behaviour

According to https://www.libreoffice.org/download/release-notes/ "libreoffice-still" should still be on 7.2.7

### Steps To Reproduce

1. Check the current version being offered at https://community.chocolatey.org/packages/libreoffice-still
2. Compare against the "still" version at https://www.libreoffice.org/download/release-notes/

### Environment

```markdown
- Operating System:
- PowerShell Version:
- Shell:
```

### Chocolatey Log

```shell
N/A
```

**Comment by RedBaron2** [comment]
Please, reference issue #1937
