### ISSUE TITLE
owncloud-client 

### ISSUE THREAD

**Issue by IMWS-User** [chocolatey-community/chocolatey-packages#1985]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

2.11.1

### Download location

https://owncloud.com/desktop-app/

### Package Page

https://community.chocolatey.org/packages/owncloud-client

**Comment by brogers5** [comment]
This package is outdated because the update script is broken. I'm seeing two issues with it locally:

* The pipeline that builds `$url` (and by extension, `$Latest.URL64`) is returning two strings (since there are two links matching the defined regex pattern), and this causes `Update-Package`'s URL check to fail:
  ```shell
  owncloud-client - checking updates using AU version 2021.7.18

  URL check
  Exception: D:\Cloud\Dropbox\Documents\PowerShell\Modules\AU\2021.7.18\Public\Update-Package.ps1:110
  Line |
   110 |  … heck_url $url -Options $Latest.Options) { throw "${res}:$url" } else  …
       |                                              ~~~~~~~~~~~~~~~~~~~
       | URL syntax is invalid:https://download.owncloud.com/desktop/ownCloud/stable/2.11.1.8438/win/ownCloud-2.11.1.8438.x64.msi
       | https://download.owncloud.com/desktop/ownCloud/stable/2.10.1.7187/win/ownCloud-2.10.1.7187.x64.msi
  ```
* Even if we were to pass `-NoCheckUrl` to `Update-Package`, this same issue also causes `$Latest.Version`'s pipeline to return an incorrect version value. The resulting value just so happens to be the latest available package version. 

I should mention OwnCloud also supports querying an endpoint for update checking, which returns an XML string that we could parse more easily and reliably. I'll see if I can get a PR implementing it sometime this weekend.

**Comment by IMWS-User** [comment]
May I ask for the progress of downloading the most recent ownclient-client to the chocolatey depot?

Von: brogers5 ***@***.***>
Gesendet: Freitag, 16. September 2022 06:02
An: chocolatey-community/chocolatey-packages ***@***.***>
Cc: Lohner, Martin ***@***.***>; Author ***@***.***>
Betreff: Re: [chocolatey-community/chocolatey-packages] owncloud-client (Issue #1985)


This package is outdated because the update script is broken. I'm seeing two issues with it locally:

  *   The pipeline that builds $url (and by extension, $Latest.URL64) is returning two strings (since there are two links matching the defined regex pattern), and this causes Update-Package's URL check to fail:

·         owncloud-client - checking updates using AU version 2021.7.18

·

·

·

·         URL check

·

·         Exception: D:\Cloud\Dropbox\Documents\PowerShell\Modules\AU\2021.7.18\Public\Update-Package.ps1:110

·

·         Line |

·

·          110 |  … heck_url $url -Options $Latest.Options) { throw "${res}:$url" } else  …

·

·              |                                              ~~~~~~~~~~~~~~~~~~~

·

·              | URL syntax is invalid:https://download.owncloud.com/desktop/ownCloud/stable/2.11.1.8438/win/ownCloud-2.11.1.8438.x64.msi

·

     | https://download.owncloud.com/desktop/ownCloud/stable/2.10.1.7187/win/ownCloud-2.10.1.7187.x64.msi

  *   Even if we were to pass -NoCheckUrl to Update-Package, this same issue also causes $Latest.Version's pipeline to return an incorrect version value. The resulting value just so happens to be the latest available package version.

I should mention OwnCloud also supports querying an endpoint for update checking, which returns an XML string that we could parse more easily and reliably. I'll see if I can get a PR implementing it sometime this weekend.

**Comment by pauby** [comment]
There is a [pull request](https://github.com/chocolatey-community/chocolatey-packages/pull/1986) currently waiting for review.

**Comment by IMWS-User** [comment]
Does nobody feel responsible for the review of the pull request?
I do not have the rights for reviewing.
Please....could someone take care off this?

**Comment by brogers5** [comment]
@IMWS-User, please keep in mind that this repository is staffed on a volunteer basis. Nobody here is being paid to ensure packages and updates are working, issues are being triaged or resolved, PRs are being reviewed, etc. There's a substantial time investment that comes with all of this, and some of us have difficulty with carving time out of our days to pick a task up, especially for a contribution we may not personally benefit from. I don't even use ownCloud for myself.

During particularly busy periods, volunteer contributions and maintenance could unfortunately be deprioritized, and any issues/PRs that are raised could be left sitting for a while as a consequence.  It just comes with the territory of a project that is being offered free-of-charge to its users and isn't bringing in the revenue required to staff someone to do this professionally, so expectations need to be managed accordingly.

With that said, the project's core maintainers are aware of the PR's existence, and someone will pick up the review when their schedule allows.

If this is a blocker and you can't wait any longer for an updated package, feel free to clone my branch and run the modified update script for yourself. It should produce a functionally identical package that you can consume locally.
