### ISSUE TITLE
(Audacity) Audacity package is outdated since 3.2.0

### ISSUE THREAD

**Issue by cam1170** [chocolatey-community/chocolatey-packages#1996]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

3.2.1

### Download location

https://www.audacityteam.org/download/windows/

### Package Page

https://community.chocolatey.org/packages/audacity

**Comment by cam1170** [comment]
Current status is "waiting for maintainer", because there is some issue brought up by the auto moderation.

**Comment by JPRuskin** [comment]
Looks like the packages are there, as you say, but the docs URL has been changed to 'https://support.audacityteam.org/' instead of 'https://www.audacityteam.org/help/documentation'

**Comment by JPRuskin** [comment]
Beat me to it, and I think I prefer the URL you picked! Thanks @eclairevoyant
