### ISSUE TITLE
(vim)  downlading two x86, x64 both architecture zip files. which is unnessasary.

### ISSUE THREAD

**Issue by sk0x1234** [chocolatey-community/chocolatey-packages#1998]
### Chocolatey Version

1.1.0

### Package Version

vim v9.0.0701

### Current Behaviour

Downloadin bith architecture zip files.

### Expected Behaviour

should download only one architecture either one.

### Steps To Reproduce

choco install vim 

C:\ProgramData\chocolatey\lib\vim\tools

verify the both files

### Environment

```markdown
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Chocolatey Log

```shell
None
```

**Comment by pauby** [comment]
The package doesn't download the installation Zip's. They are embedded in the package. 

See https://community.chocolatey.org/packages/vim#files

![image](https://user-images.githubusercontent.com/12760779/197845969-df03212e-d76e-45a3-969c-450ee8f316be.png)

As the package supports both architectures, and therefore they need to be embedded in the package, they are required.

I'm going to go ahead and close this, but we can reopen it if necessary.
