### ISSUE TITLE
(k9s) outdated

### ISSUE THREAD

**Issue by aserraric** [chocolatey-community/chocolatey-packages#1999]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

0.26.6

### Download location

https://github.com/derailed/k9s/releases/tag/v0.26.6

### Package Page

https://community.chocolatey.org/packages/k9s

**Comment by brogers5** [comment]
Related: #2007

**Comment by derailed** [comment]
@brogers5 Any update on this? K9s is several revs out now and my users are not too happy about it. 
Not sure what I can do to help since I did not commit the original recipe. Thank you!!

**Comment by brogers5** [comment]
@derailed, to be clear, I'm not a core maintainer of this repository. I simply wanted to call attention to the fact that this package is simply one among many others that were affected by a breaking change introduced by GitHub.

If you're willing to take a crack at it, you could refer to PRs for the packages that have already been fixed to get an idea of what needs to be done.

**Comment by danielkoek** [comment]
Created a new PR to fix this issue since the original one was closed due to lack of updates. Which can be found here: https://github.com/chocolatey-community/chocolatey-packages/pull/2170
