### ISSUE TITLE
(notepadplusplus) Outdated

### ISSUE THREAD

**Issue by dsan0815** [chocolatey-community/chocolatey-packages#2000]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

8.4.6

### Download location

https://notepad-plus-plus.org/downloads/v8.4.6/

### Package Page

https://community.chocolatey.org/packages/notepadplusplus

**Comment by RedBaron2** [comment]
@dsan0815 
I'm sure that we all appreciate the effort, but might it be more interesting to know the reason that this package is listed in the ignored [list](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#ignored) on the update status page.

**Comment by chimmmpie** [comment]
I found this https://github.com/chocolatey-community/chocolatey-packages/issues/2007 while i was looking for the cause.
