### ISSUE TITLE
(libreoffice-fresh) (407) Proxy Authentication Required

### ISSUE THREAD

**Issue by tomie15** [chocolatey-community/chocolatey-packages#2002]
### Chocolatey Version

1.1.0

### Package Version

7.4.1

### Current Behaviour

Trying to install this package but every time I try I see error message:

```
ERROR: Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (407) Proxy Authentication Required."
The install of libreoffice-fresh was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\libreoffice-fresh\tools\chocolateyInstall.ps1'.
See log for details.
```

### Expected Behaviour

Successful installation as usual.

### Steps To Reproduce

choco install libreoffice-fresh

### Environment

```markdown
- Operating System: Windows 10 Pro
- PowerShell Version:
- Shell: CMD
```

### Chocolatey Log

```shell
https://github.com/tomie15/share/blob/d1819322ebe9826e05e435fd4bc93d9c51bb6b2f/chocolatey-libre-office-log.txt
```

**Comment by pauby** [comment]
I'm not able to reproduce this. On the surface, it looks like you are going through a Proxy that requires authentication? Do you use a proxy? Do other packages install?

**Comment by tomie15** [comment]
I have found solution here https://github.com/chocolatey/choco/issues/2229 - Within Fiddler, enable the option Rules → Automatically Authenticate.
So I see, that I'm not the only one to have this problem. All other packages are working well for me.

**Comment by pauby** [comment]
As this looks to be a Chocolatey CLI issue, I'm going to go ahead and close this, but we can reopen it if necessary.
