### ISSUE TITLE
(virtualbox) Missing new dependency on vcredist140 v14.20.27508.1 or later

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-packages#2005]
### Chocolatey Version

1.1.0

### Package Version

6.1.38 ->7.0.0

### Current Behaviour

A recently attempted upgrade operation to the latest version (7.0.0) caused the installer to fail with exit code 1.

Re-running with the `--not-silent` switch yielded the following error dialog:
![VirtualBox install failure](https://user-images.githubusercontent.com/6869577/195232944-aab1d433-408b-4733-9357-a460f70ca894.png)

### Expected Behaviour

The package should attempt installation of the prerequisite software dependency (Microsoft Visual C++ 2015-2019 Redistributable v14.20.27508.1 or later) before attempting installation of VirtualBox. Installation should not be failing due to a missing dependency that is currently available as a community Chocolatey package.

### Steps To Reproduce

1. In an environment without Microsoft Visual C++ 2015-2019 Redistributable installed, `choco install virtualbox --version=6.1.38`.
2. Once installation succeeds, `choco upgrade virtualbox`

### Environment

```markdown
- Operating System: Microsoft Windows NT 6.3.9600.0
- PowerShell Version: 4.0
- Shell: Windows PowerShell

NOTE: This is really just the standard Chocolatey Testing Environment v2.0.0. I encountered this while documenting and attempting reproduction of a separate issue I noticed with this package.
```

### Chocolatey Log

```shell
https://gist.github.com/brogers5/4fc69d4858f3a6683f15bba20110c83d
```

### Anything else?

This package is currently exempt from Package Verifier testing, so this issue was able to slip through undetected.

Core maintainers: feel free to assign this one to me.

**Comment by pauby** [comment]
> Core maintainers: feel free to assign this one to me.

Done. Thanks for picking it up.
