### ISSUE TITLE
(virtualbox) Valid Exit Codes does not include ERROR_SUCCESS_REBOOT_REQUIRED (3010)

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-packages#2006]
### Chocolatey Version

1.1.0

### Package Version

6.1.38 -> 7.0.0

### Current Behaviour

A recently attempted upgrade operation to the latest version (7.0.0) caused the installer to "fail" with exit code 3010.

This prints a misleading error message, although due to the script's current implementation (namely, lacking a declared `ErrorActionPreference` of `Stop`), this had no apparent effect on the package upgrade operation's success. As far as I can tell, the installation for the updated version has succeeded.

### Expected Behaviour

3010 should be included in the install script's array of Valid Exit Codes.

We should avoid suggesting an error condition occurred when no apparent problem exists.

### Steps To Reproduce

1. Produce any condition with the installer that will require a reboot to successfully complete installation.
2. `choco upgrade virtualbox`

NOTE: It's unclear to me what specifically triggered this behavior in my case. I was not actively using VirtualBox or any of its components before starting the attempted upgrade. The registry value `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations` includes references to `C:\Windows\System32`'s copy of `VBoxSup.sys`, which leads me to believe the installer may have had issues with cleanly stopping/restarting the VirtualBox Support Driver and its related service.

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22000.0
- PowerShell Version: 5.1.22000.832
- Shell: Windows PowerShell, Windows Terminal v1.15.2713.0

NOTE: Regardless of environment, this will also require Microsoft Visual C++ 2015-2019 Redistributable v14.20.27508.1 or later to be installed to ensure an unrelated failure does not happen (see #2005).
```

### Chocolatey Log

```shell
https://gist.github.com/brogers5/f62238bc50dab9e71e09784d57cc46cf
```

### Anything else?

Core maintainers: feel free to assign this one to me.

**Comment by pauby** [comment]
> Core maintainers: feel free to assign this one to me.

Done. Thanks for picking it up!

**Comment by brogers5** [comment]
For future reference log generated by the installer itself:
https://gist.github.com/brogers5/079db2582d8ee813aad07bea0aa63d0c
