### ISSUE TITLE
(audacity) Failing validator due to invalid docsUrl

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#2010]
### Chocolatey Version

1.1.0

### Package Version

3.2.1

### Current Behaviour

Package is failing validator due to invalid docsUrl. Package is 'Waiting on maintainer'.

### Expected Behaviour

Package passes.

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A
```

**Comment by TheNavyBear** [comment]
The "Documentation" button on the Audacity homepage takes you to: https://support.audacityteam.org/
Not sure that counts as documentation, but also not sure what other link could be provided either.

**Comment by pauby** [comment]
The latest version has [been approved](https://community.chocolatey.org/packages/audacity/3.2.1).
