### ISSUE TITLE
Conan does not work properly and does not find python modules

### ISSUE THREAD

**Issue by Sil3ntStorm** [chocolatey-community/chocolatey-packages#2012]
### Chocolatey Version

1.1.0

### Package Version

1.53.0

### Current Behaviour

Have a conan recipe that requires a specific conan version (say `required_conan_version = '>= 1.50'`) and conan from chocolatey will report that the version is incorrect for the recipe processed.
If you remove that, then it will complain about not finding python packages that have been installed through pip, despite python itself (also installed through choco) is perfectly happy to find them.

Installing conan from pip (again python has been installed using choco) the original recipe works just fine (as in the version check works and it finds the installed python packages).

### Expected Behaviour

conan installed from choco behaves exactly the same as the one installed through pip.

### Steps To Reproduce

install python and conan from choco
attempt to install a package that requires modules that have been installed through pip (e.g. pprintpp) or require a specific conan version (older than installed).
See it fail

### Environment

```markdown
- Operating System: Windows Server Core 2019 20H2
- PowerShell Version: 5.3
- Shell: PowerShell
```

### Chocolatey Log

```shell
N/A
```

**Comment by pauby** [comment]
You mentioned python, so I wanted to confirm this issue is for the [Conan package](https://community.chocolatey.org/packages/conan)?

If so, isn't maintained in this repository. Can you go to the package page and click on 'Package Source' or click 'Message Maintainers' and report it to them?

**Comment by Sil3ntStorm** [comment]
https://github.com/Xav83/chocolatey-packages/issues/18
