### ISSUE TITLE
(cygwin) updates cygwin, but does not update cygwin's packages

### ISSUE THREAD

**Issue by TTimo** [chocolatey-community/chocolatey-packages#2037]
### Chocolatey Version

1.1.0

### Package Version

3.3.6

### Current Behaviour

chocolatey updates cygwin, but does not update cygwin's installed packages

### Expected Behaviour

I'm not sure this is intended behavior. Personally I would expect the installed packages to get updated along.

The workaround is to download and run setup-x86_64.exe yourself. Defeats the purpose of chocolatey a little.

### Steps To Reproduce

update cygwin

### Environment

```markdown
- Operating System: Windows 10
- PowerShell Version: 7.2.7
- Shell: powershell
```

### Chocolatey Log

```shell
N/A
```

**Comment by pauby** [comment]
> chocolatey updates cygwin, but does not update cygwin's installed packages

Can you be clearer by what you mean here by `cygwin's installed packages`? 

Do you mean the Chocolatey cygwin package or the packages that you installed inside the cygwin shell?

**Comment by TTimo** [comment]
I mean the packages installed inside cygwin (shell, compilers, libraries etc.). I can confirm the chocolatey cygwin package updates just fine.

Seems this has been the case for a long time, as it's mentioned on the site: http://disq.us/p/28y7q21

I'm just a little more motivated than others and submitted an issue..

**Comment by TTimo** [comment]
Thanks, I understand choco's point of view on this.

**Comment by TTimo** [comment]
fwiw msys2 (https://community.chocolatey.org/packages/msys2) updates it's packages

**Comment by gep13** [comment]
> @TTimo said...
fwiw msys2 (https://community.chocolatey.org/packages/msys2) updates it's packages

Can you elaborate on exactly what you mean here?  Simply pointing at a package page doesn't help with anyone trying to understand what you are trying to say on this issue.

**Comment by TTimo** [comment]
Ok .. to state it more clearly: when running `choco upgrade all`, if `msys2` gets updated, then as part of the choco update all of msys2's installed packages get updated as well (which looks to be a multi-phase `pacman -Syu` type of operation).

It seems the packagers of msys2 made a different decision regarding how msys2's installed packages should be kept up to date than cygwin's packagers did.
