### ISSUE TITLE
(Calibre) System restarted at end of installation

### ISSUE THREAD

**Issue by PaulWalkerUK** [chocolatey-community/chocolatey-packages#2043]
### Chocolatey Version

0.11.3

### Package Version

5.32.0 -> 6.7.1

### Current Behaviour

When it got to the end of installing the new version, my system rebooted automatically.

### Expected Behaviour

The system should not reboot

### Steps To Reproduce

I don't know how reproducible it is, but I guess just install the latest version

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19044.0
- PowerShell Version: 5.1.19041.1682
- Shell: PowerShell
```

### Chocolatey Log

```shell
https://gist.github.com/PaulWalkerUK/937fda55ca53c4d023b0bf8cc9c31677
```

**Comment by AdmiringWorm** [comment]
I haven't seen this happen, but it could be that a different MSI or something else had a pending reboot initiated when the calibre installer was executed (or since it was an upgrade, calibre was running and forced a reboot since that was required to finish the installation).

I'll have a look to see if there are any parameters we can pass to the installer to prevent it from trying to reboot.

**Comment by pauby** [comment]
I recently installed calibre, and it didn't restart, prompt for restart or mention anything about it. I appreciate that's a 'it works on my machine' but I wanted to add it here anyway.

**Comment by pauby** [comment]
@AdmiringWorm is there an update on this?>

**Comment by AdmiringWorm** [comment]
> @AdmiringWorm is there an update on this?

Unfortunately not, I have not had the chance to look into what is going on here.
In theory, Chocolatey CLI is meant to cancel any reboots, and I haven't seen any reboots happen for the calibre installations myself.

I'll mark this issue as an up for grabs and unassign myself in case someone else is able to look into the problem before I have the time.

**Comment by sboukortt** [comment]
Could we reopen this? It still happens. As far as I can tell, the trigger is if a Calibre program (either the main one, or e.g. `ebook-viewer`) happens to be open during an upgrade.

It seems `msiexec` accepts a `/norestart` argument. Maybe that would fix it?
