### ISSUE TITLE
(gitextensions) outdated

### ISSUE THREAD

**Issue by webartoli** [chocolatey-community/chocolatey-packages#2055]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

4.0

### Download location

https://github.com/gitextensions/gitextensions/releases/latest

### Package Page

https://community.chocolatey.org/packages/gitextensions

**Comment by AdmiringWorm** [comment]
@BlythMeister can you please comment on this issue so we can assign it to you (since you opened a PR).

**Comment by BlythMeister** [comment]
Commenting on this issue as I raised PR to fix it 🙂
