### ISSUE TITLE
(winamp) Update Package to 5.9.0

### ISSUE THREAD

**Issue by stefan-muc** [chocolatey-community/chocolatey-packages#2068]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

5.9.0

### Download location

https://download.nullsoft.com/winamp/misc/Winamp590_9999_final_full_en-us.exe

### Package Page

https://community.chocolatey.org/packages/winamp

**Comment by stefan-muc** [comment]
As with issue #1130 Winamp 5.8 was skipped, but now Winamp 5.90 (5.90.0.9999) is out (file name says `final`), it would be great to see the Winamp package updated ... finally ;)
Version can be downloaded from https://www.winamp.com/player/downloads/ and redirects to the link above.

**Comment by AdmiringWorm** [comment]
Since it seems like it is no longer a beta/rc build I'll open it up.

Do note it would only be updated if someone is willing to pick it up, and move it to be an automatic updatable package.

**Comment by JPRuskin** [comment]
I'll happily pick this up.

**Comment by pauby** [comment]
@JPRuskin Any update on this?

**Comment by pauby** [comment]
I'm going to unassign this and put it back up for grabs.

**Comment by stefan-muc** [comment]
still relevant

**Comment by pauby** [comment]
@stefan-muc This may still be relevant, but if nobody is willing to pick up and fix the package, we need to close the issue. It cannot stay open indefinitely.
