### ISSUE TITLE
(gom-player) Package has > 5 AV detections

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#2069]
### Chocolatey Version

1.2.0

### Package Version

2.3.81.5346

### Current Behaviour

Package is failing Package Scanner with [6 AV detections](https://community.chocolatey.org/packages/gom-player/2.3.81.5346#virus).

### Expected Behaviour

Package should either have < 5 AV detections or include a note in the description with why it would be expected to have > 5 AV detections.

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A
```

### Anything else?

I checked the Gom Player website to see if there was anything on this and I couldn't find it.

**Comment by AdmiringWorm** [comment]
It seems it was only that specific version that was detected with viruses, a later version that was pushed didn't trigger anything. So I'll say it is not anything to worry about, so I'll be closing the issue now.
