### ISSUE TITLE
speedtest

### ISSUE THREAD

**Issue by dsan0815** [chocolatey-community/chocolatey-packages#2071]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.2.0

### Download location

https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-win64.zip

### Package Page

https://community.chocolatey.org/packages/speedtest

**Comment by RedBaron2** [comment]
@dsan0815 
This package is not maintained in this repository. 
The correct maintainer is @xmha97 and having mentioned it is now aware of the out-dated issue.
