### ISSUE TITLE
qBittorrent 4.4.5

### ISSUE THREAD

**Issue by nikkehtine** [chocolatey-community/chocolatey-packages#2073]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

4.5.0

### Download location

https://www.fosshub.com/qBittorrent.html?dwl=qbittorrent_4.5.0_x64_setup.exe

### Package Page

https://community.chocolatey.org/packages/qbittorrent

**Comment by JPRuskin** [comment]
There is a PR open for this, here: #2070

**Comment by gobalius** [comment]
Hi, I am in the process of updating the files to allow for qBittorrent to update to version 4.5.0 now that only 64-bit version will be provided starting with that version.
