### ISSUE TITLE
(kubelogin) binary is incorrectly named

### ISSUE THREAD

**Issue by JaZo** [chocolatey-community/chocolatey-packages#2074]
### Chocolatey Version

1.2.0

### Chocolatey License

None

### Package Version

1.25.4

### Current Behaviour

This package is installed with binary `kubelogin.exe`, but that should be named `kubectl-oidc_login.exe` in order to work as kubectl plugin.

### Expected Behaviour

I'd expect the package to be installed (or aliased) with binary `kubectl-oidc_login.exe`. As per comments on https://community.chocolatey.org/packages/kubelogin.

### Steps To Reproduce

1. Setup `~/.kube/config` (you can find an example in the package description);
2. Install kubernetes-cli and kubelogin;
3. Try to access the cluster with `kubectl get pods`;
4. See it fails;
5. Rename (of symlink) `kubelogin.exe` to `kubectl-oidc_login.exe`;
6. Try to access the cluster with `kubectl get pods`;
7. See it works.

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19045.0 (Windows 10, 22H2)
- PowerShell Version: 5.1.19041.1682
- Shell: Windows PowerShell
```

### Chocolatey Log

```shell
N/A
```

**Comment by pauby** [comment]
This package doesn't do anything except extract the kubelogin Zip file which contains kubelogin.exe. The description of the package is:

```
kubelogin is a small command-line utility that allows you to easily login into your kubernetes cluster using OpenID Connect (OIDC).
```

It doesn't mention anything about being a plugin, so the package is behaving as expected. If you want it to have a different name then my suggestion would be to rename it manually, copy it and rename it manually or create another package that is specifically to be used as a plugin.

**Comment by JaZo** [comment]
I see there's also an issue in the kubelogin repo about this problem that has more information: https://github.com/int128/kubelogin/issues/688

**Comment by JaZo** [comment]
What's your view on this @jetersen? As the author of the PR that added kubelogin.

**Comment by jetersen** [comment]
This package simply follows the maintainer's zip so the file should not be renamed imho. At the time I used it to install kubelogin.exe on path to use in our kubeconfig for Windows.

If you want to shim it, this could be a package parameter, potentially it could also be an opt out parameter.

I know krew and kubectl plugin excepts the name to be oidc_login nowadays.

**Comment by AdmiringWorm** [comment]
As we are using the name that comes along with what the software maintainers provide, there isn't something that we should be changing.

And since this isn't a bug or an outdated issue, I will be closing this issue, please open up an enhancement request, and we can take this into a vote of whether the package should be enhanced to provide an alias or not, and which method should be used.
