### ISSUE TITLE
(vscode) - outdated; cannot update vscode.install due to missing vscode pkg of same version

### ISSUE THREAD

**Issue by slycordinator** [chocolatey-community/chocolatey-packages#2078]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.74.1

### Download location

https://az764295.vo.msecnd.net/stable/1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a/VSCodeSetup-x64-1.74.1.exe

### Package Page

https://community.chocolatey.org/packages/vscode

**Comment by slycordinator** [comment]
vscode.install package was updated to 1.74.1 and is available for install/upgrade.

But it cannot be upgraded due to no available/existing 1.74.1 version for the "vscode" virtual package.

**Comment by pauby** [comment]
Version 1.74.1 of the `vscode` package was submitted about 6 hours ago and is now [approved](https://community.chocolatey.org/packages/vscode#versionhistory) about 4 hours ago.

**Comment by 1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP** [comment]
This is happening again, now with version 1.75.

**Comment by pauby** [comment]
@1EDExg0ffyXfTEqdIUAYNZGnCeajIxMWd2vaQeP Please have some patience. If the issue persists then please raise another issue as this one is closed.

![image](https://user-images.githubusercontent.com/12760779/218083608-5d299271-3787-4b38-8754-b6ae995af16e.png)
