### ISSUE TITLE
(tor-browser) Outdated

### ISSUE THREAD

**Issue by yannpub** [chocolatey-community/chocolatey-packages#2098]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

12.0.1

### Download location

https://www.torproject.org/dist/torbrowser/12.0.1/torbrowser-install-win64-12.0.1_ALL.exe

### Package Page

https://community.chocolatey.org/packages/tor-browser

**Comment by TheCakeIsNaOH** [comment]
The automatic updater script is broken for this package, the reason is that there are no longer individual language installers. Instead there is a single installer for all languages as per https://www.torproject.org/download/languages/
