### ISSUE TITLE
(winpcap) dependencies of package in chocolatey are incorrect and are different from the same package in this repo

### ISSUE THREAD

**Issue by slycordinator** [chocolatey-community/chocolatey-packages#2106]
### Chocolatey Version

1.2.1

### Chocolatey License

None

### Package Version

4.1.3.20161116

### Current Behaviour

WinPcap package in chocolatey depends on "autohotkey.portable" (with no version number).
winpcap.nuspec: `<dependency id="autohotkey.portable" />`

And the latest available autohotkey.portable is 2.0.2, but the AHK script the package uses is not compatible with version 2+.
So, when I install the winpcap, I get a popup of autohotkey complaining of invalid syntax. The only option to continue is to click "exitapp", which exits autohotkey and allows the package to finish installing, but it seems to not finish correctly.

And uninstalling the package causes the same to happen.

And then here in this repository, WinPcap instead depends on autohotkey.portable version 1.1.26.01
winpcap.nuspec: `<dependency id="autohotkey.portable" version="1.1.26.01" />`

Which seems to be a version that would work.

### Expected Behaviour

Package to install/install without failures of attached scripts.

### Steps To Reproduce

0) If autohotkey.portable is installed, updated it to version 2.
1) run choco install winpcap
2) see popup of AHK scripts

And later...
1) run choco uninstall winpcap
2) see popups of failures of AHK scripts

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19045.0
- PowerShell Version: 5.1.19041.2364
- Shell:
```

### Chocolatey Log

```shell
https://gist.github.com/slycordinator/962866027916ff1df9ce0c96779a2360
```

**Comment by pauby** [comment]
As the last version of winpcap is 4.1.3 a package fix version could be released, that includes the version range for `autohotkey.portable` that is in this repository.

@AdmiringWorm does that sounds like the right course of action, and if so, how do we do that?

**Comment by gbloice** [comment]
Somewhat off-topic, is there any reason to continue using the obsolete WinPcap which is no longer maintained (since 2016)?

How does Chocolatey handle obsolete and unmaintained packages (WinPcap not the choco package)?

**Comment by pauby** [comment]
Somebody may have a reason still to use it. If it's a valid package then I don't see a reason to remove it?

> How does Chocolatey handle obsolete and unmaintained packages (WinPcap not the choco package)?

Obsolete (as in no longer working) packages can be unlisted. Packages that have been replaced can be deprecated in favour of another package. Unmaintained packages have a [process that can be followed](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process) so they can be picked up and maintained again.

**Comment by AdmiringWorm** [comment]
> As the last version of winpcap is 4.1.3 a package fix version could be released, that includes the version range for `autohotkey.portable` that is in this repository.
> 
> @AdmiringWorm does that sounds like the right course of action, and if so, how do we do that?

That is one way we can do, a different way that is probably more appropriate is to try upgrading the scripts to be compatible with autohotkey v2, but that is probably something that will take more time as it means we would need to do that for all of the packages in the repository that uses autohotkey

**Comment by slycordinator** [comment]
Another way to solve it would be to have a way to specify which autohotkey executable to run in a package.

Because you can have both autohotkey.install (which is in the v1 range) and autohotkey.portable (in the v2 range) installed simultaneously.

But if I install both of them, pkgs that use v1 scripts that depend on the v1 .install pkg can still run the v2 executable from the .portable pkg, because it's in choco's PATH.

Most packages that use authohotkey do something like
`Start-Process $ahkExe $ahkFile`
with ahkExe set to 'AutoHotKey'

But 'AutoHotKey' matches both executables so it just runs the first one that it finds along its PATH.

So, we would need some way to ensure that a package that depends on .portable run the .portable exe and that one that depends on .install use it. Or similarly ensure that something that needs v1 exe's run those and something that needs v2 exe's to use them instead.

Doing that the second way could be handled by having the version-numbered links to the executables.

Though, it would mean that you'd have to ensure that when packages that currently use AHK v1 are upgraded, that AHK gets upgraded after the old version of the dependent pkg gets uninstalled.

Because in the case of winpcap, its uninstall also uses the scripts that need AHK v1. So when you upgrade it to a version using AHK v2, if the AHK v2 upgrade gets triggered early, the installed version won't uninstall properly.

**Comment by pauby** [comment]
That is a way to do it, but it seems overly complex for this issue and a lot of work to maintain and revert.

The easiest way may be to upgrade the script to be Autohotkey 2 compatible. Given you determined the problem, @slycordinator, I'm assuming you know about this. Is it something you could pick up and submit a PR for?

**Comment by slycordinator** [comment]
I can work on it, though when I used a script for changing from v1 to v2,
the resulting new one didn't work. I'll have to try again and see what
happens.

But the reason I suggested making changes to ensure which version of AHK
gets run is to make a more general fix or for something that allows for a
transition to using the new version.

**Comment by slycordinator** [comment]
I was able to fix the package to work with the newer AHK. The PR is pending review.
