### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by AmirPour-PGGM** [chocolatey-community/chocolatey-packages#2110]
### Chocolatey Version

Other (note in the comments)

### Chocolatey License

None

### Package Version

108.0.5359.123

### Current Behaviour

Chrome not installing.

![image](https://user-images.githubusercontent.com/122539361/212080786-6cc265df-4f16-4fa4-bb2c-438bca346f30.png)

### Expected Behaviour

Successful installation

### Steps To Reproduce

1. Go to Chocolatey
2. find Google Chrome
3. Install

### Environment

```markdown
- Operating System: windows 10
```

### Chocolatey Log

```shell
Could not find
```

**Comment by pauby** [comment]
Does it work when installing from the command line?

**Comment by AmirPour-PGGM** [comment]
Hi Pauby,

The installation must be done through Chocolaty. The error in the screen shot comes also from Chocolaty

**Comment by TheCakeIsNaOH** [comment]
@AmirPour-PGGM the command line mean using `choco.exe`, instead of using ChocolateyGUI. This would mean opening an admin cmd/powershell window and running `choco install googlechrome`

**Comment by AmirPour-PGGM** [comment]
@TheCakeIsNaOH 

Same problem:

![image](https://user-images.githubusercontent.com/122539361/212103987-d4c800d4-6a5b-4075-bf02-b90b5cc0f711.png)

**Comment by pauby** [comment]
@AmirPour-PGGM What is the output of `choco source list` (make sure to remove any sensitive information).

**Comment by pauby** [comment]
Version 109.0.5414.75 was approved and available on January 11. Closing this issue.

**Comment by AmirPour-PGGM** [comment]
Tried to reinstall Chrome using Chocolatey UI, same problem with licence configuration.

Tried to install using cmd (as admin). Succeeded.
