### ISSUE TITLE
(Paint.net) A Possible Dependency on .NET 4.7.1 and/or +4.8

### ISSUE THREAD

**Issue by MrkGameDev** [chocolatey-community/chocolatey-packages#2116]
### Chocolatey Version

1.2.1

### Chocolatey License

None

### Package Version

4.3.12 -> 5.0

### Current Behaviour

when running `choco upgrade all -y` in admin privileges, it works everytime like a charm, but today, upgrading `paint.net` failed with no clear reason, Probably the Checksum failed, but no, it very much is the exact `.exe` file from `paintdotnet` repo.

after digging in the `chocolety.log` file, I've noticed these lines:
```
2023-01-16 07:55:32,428 11364 [DEBUG] - Elevating permissions and running ["C:\ProgramData\chocolatey\lib\paint.net\tools\paint.net.5.0.install.x64.exe" /auto ]. This may take a while, depending on the statements.
2023-01-16 07:55:45,714 11364 [DEBUG] - Command ["C:\ProgramData\chocolatey\lib\paint.net\tools\paint.net.5.0.install.x64.exe" /auto ] exited with '-532462766'.
```

when trying to upgrade the package with the notice below apply:

![image](https://user-images.githubusercontent.com/70659536/212610565-d84e42d0-7e94-46a3-a22b-aade4c0fb9a2.png)

(Their some dependency on `.NET 4.7.1` for `paint.net ver. 5.0`)
------
Solution I've found:
Did a `choco install dotnet4.7.1` then a `choco upgrade paint.net` (_Both commands in admin of course_)
and somehow... it fixed it?

if there's a real dependency on it, then we should add `dotnetfx +4.7.1` as a Dependency in the package

### Expected Behaviour

The package `paint.net` upgrades successfully when running `choco upgrade paint.net`

### Steps To Reproduce

**Note:** This is done on Windows 10!

1. install chocolatey following their guide on https://chocolatey.org/install
2. install paint.net by running the following command in any shell you use _With Admin Privileges_ `choco install paint.net -y`
3. if you got an error when installing paint.net, _then it's most likely what I went through_, double check the exit code with mine and see if it's `-532462766`.

### Environment

```markdown
- Operating System: Windows 10 22H2 (build number 19045.2364)
- PowerShell Version: 7.3.1
- Shell: CMD
```

### Chocolatey Log

```shell
https://gist.github.com/MrkGameDev/567977b19d24f9c949d586430f8f2512#file-log_for_choco-upgrade-all-txt

https://gist.github.com/MrkGameDev/567977b19d24f9c949d586430f8f2512#file-log_for_choco-upgrade-paint-net-txt
```

### Anything else?

* Removed some info, `PC-NAME`, `USER-NAME` and `PUB-TOKEN`, they're _of course_ not real info.
* Yes, I use `choco-cleaner` which removes unnecessary files that choco keep, and I don't think it got anything to do with `paint.net 5.0` not installing correctly.
* If anyone who know a lot more in Chocolatey packages, how they're built and so on, and needs more info, feel free to ask and I'll send them as fast as I can 👍

**Comment by pauby** [comment]
`paint.net` requires Windows 10 1809 as a minimum (I tried to install it on Windows Server 2012 R2 to test your issue and that was the popup during install).

According to this [doc](https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-472), Windows 10 1809 ships with .NET 4.7.2, so the prerequisites should already be met. I'm assuming I'm missing something as you are running Windows 22H2 which should be .NET 4.8.

**Comment by MrkGameDev** [comment]
I do agree the weirdness of the issue, since the .NET 4.8 is already installed on my system Well before `paint.net` stopped upgrading correctly.

But I did notice the Status/Progress window showup when upgrading `paint.net`
+ the extracting window:
![image](https://user-images.githubusercontent.com/70659536/212680296-155e4016-302d-4f7d-b8fd-bbac64f258df.png)

isn't the `/auto` flag with `.exe`  install file makes it a completely silent/unattended installation?
if so, then isn't it a bug or an expected behavior from paint.net to show it (i.e. the progress window)?

**Comment by pauby** [comment]
`paint.net` has always shown the extraction box. The install is non-interactive, but not silent.

**Comment by pauby** [comment]
Looking back at [this](https://github.com/chocolatey-community/chocolatey-packages/issues/2116#issuecomment-1383902858), I think all that is done here is to add a check, into the `chocolateyInstall.ps1` script to check for Windows 10 1809 as a minimum.

> paint.net requires Windows 10 1809 as a minimum (I tried to install it on Windows Server 2012 R2 to test your issue and that was the popup during install).
