### ISSUE TITLE
(InkScape) inkscape-1.2.2_2022-12-01_b0a8486541-x64.msi is defect, please upgrade to the fixed package from 2022-12-09.

### ISSUE THREAD

**Issue by beppo-dd** [chocolatey-community/chocolatey-packages#2118]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

The Windows package inkscape-1.2.22022-12-01b0a8486541-x86.msi is defect, see [Release Notes](https://inkscape.org/release/inkscape-1.2.2/#left-column).

The Windows package was fixed in:

### New Software Version

1.2.2 (2022-12-09, 732a01da63)

### Download location

https://media.inkscape.org/dl/resources/file/inkscape-1.2.2_2022-12-09_732a01da63-x64.msi

Please update to this package.

### Package Page

https://community.chocolatey.org/packages/InkScape

Thanks.
Beppo

**Comment by pauby** [comment]
Sounds like this may be a forced AU update that would create a package fix version, @AdmiringWorm?

**Comment by pauby** [comment]
[New version has been pushed](https://community.chocolatey.org/packages/InkScape/1.2.2.20230220).
