### ISSUE TITLE
(git) Update to Version 2.39.1 from 18th of january 2023 to address 3 critical/high CVEs

### ISSUE THREAD

**Issue by ickk** [chocolatey-community/chocolatey-packages#2120]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

v2.39.1.windows.1

### Download location

https://github.com/git-for-windows/git/releases/tag/v2.39.1.windows.1

### Package Page

https://community.chocolatey.org/packages/git

**Comment by gep13** [comment]
@ickk this package version has already been pushed, and is working its way through the moderation process.
