### ISSUE TITLE
(tor-browser) v12.0.3 checksums are incorrect

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-packages#2146]
### Chocolatey Version

1.3.0

### Chocolatey License

None

### Package Version

12.0.3

### Current Behaviour

v12.0.3 is checking against incorrect (possibly outdated) checksums.

32-bit: 8cf1dafe65efe4a9a732191ab5fa962ae75513694cc802b462abf0ae40f64a3a
64-bit: 94c66cde8a8f6744971553deba450b3e2bf2ad17f0d3129853591a050801a58c

### Expected Behaviour

Package should check against current checksums.

32-bit: A880112BF2927FE02DFCB7550FB1780DFEC8AA5E332D2CD9897C503A018EE02F
64-bit: 8F9E526DA7D1ADAA5C6C7BE88412E9E6C7EAB9AF1B5F080B0D674F5B35F5C4BF

### Steps To Reproduce

`choco install tor-browser --version=12.0.3`

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22621.0
- PowerShell Version: 5.1.22621.963
- Shell: PowerShell
```

### Chocolatey Log

```shell
https://gist.github.com/brogers5/c1f225d02e2837486cc8e008c7bc71d9
```

**Comment by superbonaci** [comment]
Same for me.

**Comment by pauby** [comment]
I've added the label 'Up For Grabs'. As a remidner this is a community maintained repository so community PR's are very welcome.

**Comment by superbonaci** [comment]
Confirmed it works!
