### ISSUE TITLE
(nodejs) nodejs dependencies stop upgrading to latest 19.6.1 version

### ISSUE THREAD

**Issue by Leif-W** [chocolatey-community/chocolatey-packages#2149]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

19.6.1

### Download location

https://nodejs.org/en/download/current/

### Package Page

https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/nodejs

**Comment by pauby** [comment]
@Leif-W You've used the outdated template which doesn't capture the information needed. I have updated it however.

The workaround would be to uninstall `nodejs` and select No when asked to uninstall `nodejs.install` and then upgrade `nodejs.install`.

**Comment by Leif-W** [comment]
Regarding outdated template issue, missing information, there was no other option presented when filing an "outdated" issue, so it wasn't me using an outdated template.

Regarding the workaround, I am aware.  But the purpose of filing an issue is to notify of a problem, not use workarounds.

Indeed, though nodejs wasn't in the queue, as far as I could see (the queue is shown in random order, not sortable or searchable, spanning several months), for several days, it wasn't too long after submitting the issue that nodejs was updated, and thus the workaround obviated.

I don't know if both were in queue but asynchronously upproved, but if so, there should be a tighter coupling in review between a stub package and its stub.install package.  Maybe there was some other ommission from human error, or a problem seen offline that lead to non-submission, thus no error appeared in the automated logs.  Maybe some process hung or died without triggering logs.

Who knows?  In any case, this is now resolved.  Gratitude to any who silently fixed this.
