### ISSUE TITLE
(inkscape) `choco upgrade` will not run the installer when the same version is being installed

### ISSUE THREAD

**Issue by jedfrechette** [chocolatey-community/chocolatey-packages#2157]
### Chocolatey Version

1.3.0

### Chocolatey License

None

### Package Version

>1.2.2 tested

### Current Behaviour

`choco upgrade inkscape`   reports success, but does not update the installed version of the application. I tested the 1.2.2 to 1.2.2.20230220 upgrade but do not know if this bug affects prior versions.

### Expected Behaviour

The upgrade between versions should be performed.

### Steps To Reproduce

1. `choco install inkscape --version 1.2.2`
2. Check currently installed version: `"C:\Program Files\Inkscape\bin\inkscape.com" -V`
or launch the application from the Start Menu and check the build version in the help menu. The installed build should be from 1 December with hash b0a8486541.
3. `choco upgrade inkscape` This does not raise any errors and reports that the package was successfully upgraded to version 1.2.2.20230220.
4. Check the installed version again from the gui or via the command line as above. The application should have been upgraded to the build dated 9 December with hash 732a01da63, but you'll notice that it is still the 1 December build.
5. `choco uninstall inkscape` This also appears to complete successfully, however, the application is still installed as can be seen by running: `"C:\Program Files\Inkscape\bin\inkscape.com" -V` and must be manually uninstalled using Programs and Features.
6. Running `choco uninstall inkscape` between steps 2 and 3 followed by `choco install inkscape` works as expected and results in the correct version being installed so the failure in step 5 seems to be a side effect of the failed upgrade in step 3.

### Environment

```markdown
The described behavior was observed on multiple machines that likely have slightly different environments, but one example is:
- Operating System: Microsoft Windows NT 10.0.19044.0
- PowerShell Version: 5.1.19041.2364
- Shell: CMD/Powershell
```

### Chocolatey Log

```shell
NA
```

**Comment by pauby** [comment]
A version number like 1.2.2.20230220 is a [package fix version](https://docs.chocolatey.org/en-us/create/create-packages#package-fix-version-notation). 

The version of inkscape installed with package version 1.2.2.20230220 will be version 1.2.2.

**Comment by jedfrechette** [comment]
With `b0a8486541` installed, manually running the `732a01da63` msi  correctly performs the upgrade so I believe this is an issue with this packaage and/or choco.

`autoUninstaller` is enabled in my environment.

**Comment by pauby** [comment]
If you can provide evidence that this is a Chocolatey issue then that should be raised as an issue. But from what I've seen at far, it's not.

The package simply runs the installer. It's the installers job to install the software. If Chocolatey runs the installer and the installer is not upgrading the software, that's an installer issue.

When trying to reproduce this you need to run the installer in the same way Chocolatey CLI does.

**Comment by jedfrechette** [comment]
I'm not familiar enough with choco's internals to ensure that I'm manually running the installer in the same way the cli does so I'm afraid all I can provide is what I've already written, that upgrading the package via choco doesn't update the software, while uninstalling then installing with choco or manually updating it outside of choco both work as expected.

**Comment by pauby** [comment]
Are you installing it silently using the same command line switches that the package uses?

**Comment by jedfrechette** [comment]
The following steps result in the installed version of the software being correctly upgraded:

1. choco install inkscape --version 1.2.2
2. msiexec.exe /i inkscape-1.2.2_2022-12-09_732a01da63-x64.msi /qn /norestart

**Comment by pauby** [comment]
Now that I'm back on my desktop, I've had a look at the package code. I think [these lines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/inkscape/tools/chocolateyInstall.ps1#L19-L21) are causing the installer not to be run again.

Going to check.

**Comment by pauby** [comment]
That is exactly the problem. 

![image](https://user-images.githubusercontent.com/12760779/221429230-a66d21bb-803a-42f4-9a31-6a75d52e4a3b.png)

Even installing it with `--force` doesn't install the software. I'd suggest this is a bug that needs fixed. If the user wants the current version reinstalled, then I'd suggest it is reinstalled.

This software may have issues installing over a current version, or there may be good reasons as to why the current version isn't simply installed again.

@AdmiringWorm @facorread you both have updated the package in the past. Any suggestions on this issue?

**Comment by AdmiringWorm** [comment]
This is not a bug. Unfortunately, the software authors report the installed and new versions as the same.

Due to this, the installation is skipped. While we could always revert this check for the installed version, that would mean we would always download/reinstall the software every time, which will fail when the same version is installed.
