### ISSUE TITLE
(git.install) please update to 2.39.2.0 on github

### ISSUE THREAD

**Issue by umol-unibas** [chocolatey-community/chocolatey-packages#2165]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

2.39.2.0

### Download location

https://github.com/git-for-windows/git/releases/download/v2.39.2.windows.1/Git-2.39.2-64-bit.exe

### Package Page

https://community.chocolatey.org/packages/git.install

**Comment by umol-unibas** [comment]
Yes, you are perfectly right for the chocolatey page. Just the github sources seems to be outdated:
 https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/git.install/tools/chocolateyInstall.ps1

**Comment by pauby** [comment]
The versions in the nuspec files in the repository are he's of an issue. The next time there is an update, the package will build correctly regardless though.

As there isn't anything for us to do here, I'll go ahead and close this issue.

Thanks for raising it though. Much appreciated!
