### ISSUE TITLE
Create Selenium PowerShell Module package

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-packages#2179]
This Is split off from the main issue of to its own separate issue.

As the PowerShell module is something we use ourself, we need to create and own a package for this module.

**Comment by pauby** [comment]
@AdmiringWorm is there an update on this?

**Comment by AdmiringWorm** [comment]
@pauby The last thing I heard was that @JPRuskin was looking at getting the package created. I am not sure if it is still being worked on though.

**Comment by JPRuskin** [comment]
There's a branch with this in, I'm just discussing which tags to apply to it before pushing it into PR.

**Comment by AdmiringWorm** [comment]
@JPRuskin despite the tags hasn't been agreed on, let us get a PR created at least and we can come back to the tags before it gets merged in.

**Comment by AdmiringWorm** [comment]
I'm keeping this open until the package has been approved on CCR.
