### ISSUE TITLE
(codelite) Package upgrades/uninstalls are not silent

### ISSUE THREAD

**Issue by brogers5** [chocolatey-community/chocolatey-packages#2181]
### Chocolatey Version

1.3.1

### Chocolatey License

None

### Package Version

8.0.0+

### Current Behaviour

During both package upgrades and uninstalls, the user is prompted to either keep or remove their current user settings, and requires manual user input to proceed:

![Codelite Uninstall Prompt](https://user-images.githubusercontent.com/6869577/226115469-937ca52c-47d8-4c29-9cf9-79ad03282c69.png)

The uninstall instances in particular are causing CI validation failures, due to the process timing out during testing.

### Expected Behaviour

Package upgrades/uninstalls should complete successfully without requiring manual user input.

This will likely require a `chocolateyuninstall.ps1` script to be added to the package, ideally to pass the required arguments to implement a silent uninstallation, or alternatively, utilize an AutoHotkey script to at least make the process unattended.

A similar approach may be required for software upgrades.

#### Upgrade
1. Install a previous version of `codelite` (e.g. `choco install codelite --version=15.0.0`).
2. Upgrade to a later package version (i.e. `choco upgrade codelite`).

#### Uninstall
1. Install an affected version of `codelite` (e.g. `choco install codelite --version=16.0.0`).
2. Uninstall the previously installed package (i.e. `choco uninstall codelite`).

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22621.0
- PowerShell Version: 5.1.22621.963
- Shell: Windows PowerShell
```

### Chocolatey Log

```shell
Upgrade: https://gist.github.com/brogers5/81a84356fd0e4d482033ab20ec679a3d
Uninstall: https://gist.github.com/brogers5/54590a34a371269530d4de03d6041bea
```

**Comment by brogers5** [comment]
Yes, this is still an issue. Lack of time and interest in fixing this is the primary blocker.

Core maintainers, I'd recommend marking this one as Up for Grabs.

**Comment by pauby** [comment]
@brogers5 Every issue is up for grabs by default as this is a community maintained repository, but I have added the label. Maybe we add this by default ...
