### ISSUE TITLE
(tixati) Failed Package Verifier and rejected 

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#2182]
### Chocolatey Version

Other (note in the comments)

### Chocolatey License

None

### Package Version

3.16

### Current Behaviour

The [package has failed Package Verifier](https://community.chocolatey.org/packages/tixati/3.16). The [gist](https://gist.github.com/choco-bot/9696c0fd775fbf9b3297888e01d132f2) will provide more details.

It looks like the installation has timed out. As the package uses AutoHotkey something may have changed to break it.

### Steps To Reproduce

N/A

### Environment

```markdown
Package Verifier / Chocolatey Test Environment.
```

### Chocolatey Log

```shell
https://gist.github.com/choco-bot/9696c0fd775fbf9b3297888e01d132f2
```

### Anything else?

As the package has been rejected, if submitting the same version again it will need to be put back to Submitted.

**Comment by vampiricwulf** [comment]
My guess the hang up is caused by Tixati running during installation, the AHK script does not account for it.
If possible adding a check and kill at the beginning might solve the issue.
Something like
```ahk
Process, Exist, tixati.exe
if ErrorLevel
Process, Close, tixati.exe
```
at the beginning of the script might help.

**Comment by pauby** [comment]
PR #2424 is associated with this so I'm reopening the issue

**Comment by TheCakeIsNaOH** [comment]
PR waiting for review, issue still relevant.
