### ISSUE TITLE
(kubescape) Migrate package

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-packages#2190]
### Discussed in https://github.com/orgs/chocolatey-community/discussions/2186

<div type='discussions-op-text'>

<sup>Originally posted by **HollowMan6** March 25, 2023</sup>
I would like to request migrating the [kubescape](https://community.chocolatey.org/packages/kubescape) package to here.

- Why it should be migrated to this repository: As [kubescape upstream](https://github.com/kubescape/kubescape) have pre-built binaries in their release page and they release new versions frequently.
- A link to both the package and the repository the source code is located in (if it exists): 
  - https://community.chocolatey.org/packages/kubescape
  - https://github.com/HollowMan6/chocolatey-packages/tree/master/automatic/kubescape (It's ready for a PR at branch [submit](https://github.com/HollowMan6/chocolatey-packages/tree/submit/automatic/kubescape))

- Who will be responsible for fixing issues, reviewing changes, and making sure it is kept up to date (ie, fix the updater when it fails): Me as well as members from the kubescape org

</div>

**Comment by HollowMan6** [comment]
Hi! I would like to get assigned to this issue.

**Comment by AdmiringWorm** [comment]
This package has now been migrated to this repository.
