### ISSUE TITLE
(PartitionMasterFree) Version 17.8 install version 17.6

### ISSUE THREAD

**Issue by fraynaud33** [chocolatey-community/chocolatey-packages#2206]
### Chocolatey Version

1.3.1

### Chocolatey License

None

### Package Version

17.8

### Current Behaviour

Hello, 
maybe there is a mistake.
It talk about version 17.8 but in reality it's version 17.6 installed.
https://community.chocolatey.org/packages/PartitionMasterFree#install

In the chocolateyInstall.ps1 (C:\ProgramData\chocolatey\lib\PartitionMasterFree\tools)
$packageArgs = @{
packageName = $Env:ChocolateyPackageName
fileType = 'exe'
file = "$toolsPath\epm_free_ob_17.6_b40.exe"
silentArgs = '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-'
validExitCodes = @(0, 3010)
softwareName = 'EaseUS Partition Master*'
}

### Expected Behaviour

Version 17.8 installed.

### Steps To Reproduce

Install package PartitionMasterFree https://community.chocolatey.org/packages/PartitionMasterFree#install

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19045.0
- PowerShell Version: 5.1.19041.2673
```

### Chocolatey Log

```shell
none
```

**Comment by pauby** [comment]
According to the EXE in the package, it is 17.8.

![image](https://user-images.githubusercontent.com/12760779/229139798-f6180bfb-474d-4c96-af62-1af08fc05591.png)

This [line in the update script](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/partitionmasterfree/update.ps1#L33) takes the version that is stamped on the EXE and uses that as the version. As this is stamped with 17.8, this is the version that was used.

Given that when the software is lunched you see this:

![image](https://user-images.githubusercontent.com/12760779/229140852-9ba2e313-933c-4ca3-8185-d129c544fa7f.png)

I'm going to say the mistake was the EXE being stamped 17.8.

The update script doesn't run on my system, so somebody else will need to take that for a spin to see if there is a new 17.8 version available and push a fixed package.
