### ISSUE TITLE
(python3) Outdated

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-packages#2212]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

3.11.3

### Download location

N/A, virtual package

### Package Page

https://community.chocolatey.org/packages/python3

**Comment by TheCakeIsNaOH** [comment]
Seems like it was updated here but was not pushed: https://github.com/chocolatey-community/chocolatey-packages/commit/516d39437cba1f889470f09baada3cb885ebc72f

Similar to #2141

**Comment by superbonaci** [comment]
same here

**Comment by AdmiringWorm** [comment]
The streams have been reset so the package can be pushed again. It is unfortunately a bug in AU that is causing the problem, so nothing we can actually do in this repository other than act on it when it is reported.

**Comment by superbonaci** [comment]
Works now.
