### ISSUE TITLE
(ungoogled-chromium) Migrate package

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-packages#2213]
### Discussed in https://github.com/orgs/chocolatey-community/discussions/2119

<div type='discussions-op-text'>

<sup>Originally posted by **TakataSanshiro** January 17, 2023</sup>

* Why it should be migrated to this repository: There are many times failed when pushing embedded packages from my pc.
It's very stressful since ungoogled-chromium is updated frequently.
* A link to both the package and the repository the source code is located in (if it exists): https://github.com/TakataSanshiro/Chocolatey-Packages/tree/master/automatic/ungoogled-chromium
* Who will be responsible for fixing issues, reviewing changes, and making sure it is kept up to date (ie, fix the updater when it fails): I'm going to update one.

</div>

@TakataSanshiro please leave a comment on this issue so you can be assigned.

**Comment by TakataSanshiro** [comment]
I will pay attention to the package.

**Comment by pauby** [comment]
@TakataSanshiro Are you migrating this package over to this repository or are you maintaining it yourself? 

If you are going to maintain it yourself, please remove the `chocolatey-community` account as a maintainer of the package.

If you still intend to migrate it can you raise another PR as #2113 has been closed?

**Comment by TakataSanshiro** [comment]
I'm maintaining it myself.
I've removed the chocolatey-community account.
