### ISSUE TITLE
(wixtoolset) Deprecate / Finalize package

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#2217]
## Expected Behavior

N/A

## Current Behavior
The [Wix Toolset now ships as a .NET global tool](https://wixtoolset.org/docs/releasenotes/#update-the-wix-net-tool). Therefore, the v3.x will be the last packages we can ship.

## Possible Solution
We should created a final package, and update the package page to confirm why this is the case.

**Comment by AdmiringWorm** [comment]
I don't think we need to deprecate / Finalize the package.

Rather I think we should look to see if we can install call the `dotnet tool` in the package to install wix 4.x instead (since the tool can be installed globally) so the package can continue to be supported.

We might want to extract at the same time the current package to a new package using with the name `wixtoolset3` as well.

**Comment by AdmiringWorm** [comment]
To achieve this, we probably want to create a new extension package at https://github.com/chocolatey-community/chocolatey-extensions to make maintenance easier.

**Comment by pauby** [comment]
> I don't think we need to deprecate / Finalize the package.
> 
> Rather I think we should look to see if we can install call the `dotnet tool` in the package to install wix 4.x instead (since the tool can be installed globally) so the package can continue to be supported.
> 
> We might want to extract at the same time the current package to a new package using with the name `wixtoolset3` as well.

The `dotnet` tool is another package manager, and we have recent precedent of us not doing that. We are looking to add support for the `dotnet` tool as an alternative source, and it can then be used to install packages that way.

**Comment by ellerytbp** [comment]
Can we at least update this to Wix 3.14?

It's available here: https://wixtoolset.org/downloads/v3.14.0.4118/wix314.exe

The current commandline for silent install is: "wix314.exe /install /quiet /norestart"

There are comments on the package asking for it to also be added to the path. And it should be tested with Visual Studio to ensure that Visual Studio detects it correctly for builds.

**Comment by pauby** [comment]
@ellerytbp We are open to PR's.
