### ISSUE TITLE
(selenium-chromium-edge-driver) Outdated

### ISSUE THREAD

**Issue by pascalberger** [chocolatey-community/chocolatey-packages#2241]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

115.0.1860.0:

### Download location

https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

### Package Page

https://community.chocolatey.org/packages/selenium-chromium-edge-driver

**Comment by pascalberger** [comment]
The issues is that the AU update script checks for available Edge package versions which are available on the community feed, where `114.0.1823.55` is the latest version, which does not exist on the download page (https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/)

**Comment by pascalberger** [comment]
@AdmiringWorm Does it still make sense to only update Selenium driver to available Edge versions? At the moment it won't update, since none of the 114.x versions for which an Edge package exists are available on the Selenium driver page, and for none of the available Selenium driver versions exists a Edge package.

**Comment by patest-dev** [comment]
@pascalberger I created an alternative solution in #2247 

My solution doesn't depend on the version of the `microsoft-edge` browser version.

**Comment by patest-dev** [comment]
@AdmiringWorm Could you please review this. 😊
 The current state for the selenium-chromium-edge-driver package is really not optimal and many package versions are already missing.

My proposed fix can be found in PR #2247
