### ISSUE TITLE
(opera) Silent uninstall not working

### ISSUE THREAD

**Issue by DasThomy** [chocolatey-community/chocolatey-packages#2249]
### Chocolatey Version

2.0.0

### Chocolatey License

None

### Package Version

100.0.4815.21

### Current Behaviour

I am trying to uninstall opera silently, but it does not seem to work. I always pop ups the Uninstall window from opera.

### Expected Behaviour

Should uninstall opera silently without required user input

### Steps To Reproduce

After installing opera with:
choco install opera -y

I tried to uninstall it with the following command:
choco uninstall opera -y

### Environment

```markdown
- Operating System: Windows 11
- PowerShell Version: 5.1.22621.1778
```

### Chocolatey Log

```shell
https://gist.github.com/DasThomy/ddad550cae55a6f12f0eefd12ea68f8d
```

### Anything else?

Either I missunderstood the silently uninstall or something seems to be wrong with it.

**Comment by brogers5** [comment]
According to [this thread on Opera's forums](https://forums.opera.com/post/266906), the `/silent` switch was intentionally disabled in the uninstaller a while ago. I can confirm this is reproducible both with the latest version (100.0.4815.47) and as far back as v80.0.4170.72.

[A more recent thread](https://forums.opera.com/topic/54466/silent-uninstall-switch) suggests Opera doesn't have any near-term plans to reenable it. This may need to be made unattended with an AutoHotkey script instead.

**Comment by pauby** [comment]
@DasThomy Based on the comments from @brogers5 above, are you in a position to submit a PR to fix this?

**Comment by brogers5** [comment]
I'll pick this one up.
