### ISSUE TITLE
(skype) The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by alexschomb** [chocolatey-community/chocolatey-packages#2251]
### Chocolatey Version

2.1.0

### Chocolatey License

None

### Package Version

8.99.0.202

### Current Behaviour

Skype is not installed or updated because of download issues.

### Expected Behaviour

The latest version of Skype should be installed.

### Steps To Reproduce

Run ``choco install skype``.

### Environment

```markdown
- Operating System: Microsoft Windows 11 Pro
- PowerShell Version: 7.3.5
- Shell: PowerShell
```

### Chocolatey Log

```shell
Chocolatey v2.1.0
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.

Installing the following packages:
skype
By installing, you accept licenses for the packages.
Progress: Downloading skype 8.99.0.202... 100%

skype v8.99.0.202 [Approved]
skype package files install completed. Performing other installation steps.
Attempt to get headers for https://download.skype.com/s4l/download/win/Skype-8.99.0.202.msi failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.skype.com/s4l/download/win/Skype-8.99.0.202.msi'. Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
Downloading skype
  from 'https://download.skype.com/s4l/download/win/Skype-8.99.0.202.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.skype.com/s4l/download/win/Skype-8.99.0.202.msi'. Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
The install of skype was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\skype\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - skype (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\skype\tools\chocolateyInstall.ps1'.
 See log for details.
```

### Anything else?

Other users have this problem as well and commented in the Chocolatey Community discussion about it: https://community.chocolatey.org/packages/skype#discussion

The reason for the issue might be that direct download of the MSI package is not allowed anymore and requires opening https://go.skype.com/msi-download from the same IP address first.

**Comment by brogers5** [comment]
I can reproduce this with the latest package version (8.99.0.403).

This appears to be a TLS 1.3 handshaking failure. Chocolatey v2.0.0+ will use whatever default security protocol is configured by the OS. In Windows 11 (and Windows Server 2022), [this should be TLS 1.3](https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-#tls-protocol-version-support).

Looks like the server requires a cipher that is [disabled by default](https://learn.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-11):
```shell
PS C:\Users\brian> nmap --script ssl-enum-ciphers -p 443 download.skype.com
Starting Nmap 7.93 ( https://nmap.org ) at 2023-07-05 01:33 Eastern Daylight Time
NSOCK ERROR [0.0390s] ssl_init_helper(): OpenSSL legacy provider failed to load.

Nmap scan report for download.skype.com (23.47.64.141)
Host is up (0.0041s latency).
rDNS record for 23.47.64.141: a23-47-64-141.deploy.static.akamaitechnologies.com

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A
|     compressors:
|       NULL
|     cipher preference: server
|   TLSv1.3:
|     ciphers:
|       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (secp256r1) - A
|     cipher preference: indeterminate
|     cipher preference error: Too few ciphers supported
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 1.01 seconds
```

Workarounds:

1. Enable the required cipher suite:
```powershell
Enable-TlsCipherSuite -Name TLS_CHACHA20_POLY1305_SHA256
```

2. Temporarily disable TLS 1.3 in the registry to force TLS 1.2 negotiation:
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client]
"Enabled"=dword:00000000
```

**Comment by alexschomb** [comment]
Thank you for the detailed analysis and workaround. Unfortunately that is no viable solution for me. Let's hope Microsoft does maintenance to make their webserver compatible with their own OS soon.

**Comment by pauby** [comment]
I know this issue is closed, but I wanted to confirm that I can reproduce this on Windows 11 Pro 22H2 and @brogers5 solution fixes this.

So as @alexschomb suggests, this is a Skype website issue that they would need to fix, or we all need to enable that cipher (which would seem a little unreasonable).

**Comment by aetonsi** [comment]
> Workarounds:
> 
> 1. Enable the required cipher suite:
> 
> ```powershell
> Enable-TlsCipherSuite -Name TLS_CHACHA20_POLY1305_SHA256
> ```
> 


dammit this worked.. can't this simply be added to the package install script and immediately reverted afterwards? @pauby @choco-bot

**Comment by pauby** [comment]
This is an operating system issue. Not a package one.

**Comment by fromSmolsoft** [comment]
@pauby  
> This is an operating system issue. Not a package one.

That is kinda "it works on my machine" reply. Not really useful for end user.   

I know it was closed but it still happens consistently. Maybe it's time to do something with package itself.

**Comment by pauby** [comment]
I disagree with it being "it works on my machine". It's important to fix the issue where it lies.

If the expectation is to fix operating system issues in the package, that is going to end up being a huge time sink for the maintainers, and end up with a complicated and difficult to maintain package. That's not something that should be done here.

This issue lies in the operating system which dictates the TLS version used. This has nothing to do with the package.

If you need a custom package that incorporates operating system level changes, you can easily create your own package. But it's not something that belongs here.
