### ISSUE TITLE
(datagrip) When installing a new Datagrip minor version (e.g. 2023.2.0), an empty directory under `Program Files (x86)\JetBrains\DataGrip 2023.2.0` is created

### ISSUE THREAD

**Issue by 9numbernine9** [chocolatey-community/chocolatey-packages#2257]
### Chocolatey Version

2.1.0

### Chocolatey License

None

### Package Version

2023.2.0

### Current Behaviour

Hello! 👋 

When installing the latest version of DataGrip (`2023.2.0`), line 9 sets the `$installDir` variable to `$programFiles\JetBrains\DataGrip $env:ChocolateyPackageVersion`. Unfortunately, this value is not quite correct for new DataGrip minor versions: when a DataGrip version number ends in `.0`, the directory that the DataGrip installer will install itself into will _omit_ the `.0` patch version.

The end result of this is that we end up with two directories under `Program Files (x86)`:
- `Program Files (x86)\JetBrains\DataGrip 2023.2`, where the installer installed itself and placed all the code.
- `Program Files (x86)\JetBrains\DataGrip 2023.2.0`, an empty directory created by the `ChocolateyInstall.ps1` script.

Although this doesn't cause any errors, it is slightly confusing.

### Expected Behaviour

Only one directory for a DataGrip install should be created, not two.

### Steps To Reproduce

- Install DataGrip `2023.2.0` via Chocolatey.
- In Windows Explorer, go to `C:\Program Files (x86)\JetBrains`
- Observe that there are two similar directories: `DataGrip 2023.2` ✅ and `DataGrip 2023.2.0` ❌

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19045.0
- PowerShell Version: 5.1.19041.3031
- Shell: cmd
```

### Chocolatey Log

```shell
N/A
```

**Comment by pauby** [comment]
I've raised #2258 to fix this.

**Comment by 9numbernine9** [comment]
@pauby Is it too late to expand the scope of this issue? I just noticed that the exact same thing is happening with the WebStorm `2023.2.0` package - it stands to reason the packages for the other JetBrains products are likely affected as well.

**Comment by pauby** [comment]
@9numbernine9 We prefer one PR per package but I think in this case it would make sense to have the same change, for multiple packages, in one PR.

If you want to amend the title, and the original comment on this issue, and add checkboxes for the problematic packages, I can look at amending the PR. In the meantime I'll put #2258 in draft.

**Comment by 9numbernine9** [comment]
Still relevant - PR was raised so I'm not sure why this issue was closed.
