### ISSUE TITLE
(ruby)(ruby.install) Packages rejected after failing verification

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#2260]
## Current Behavior
Both the `ruby` and `ruby.install` packages are currently failing package verification with the last 4 versions having been rejected.

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/01dd242d-aeaf-4e83-aa9d-1660d62e5980)

This needs to be investigated and the issues resolved.

**Comment by chadlwilson** [comment]
Sadly this issue continues, including with 3.3. Seems we have a package stuck on 3.1.x which is a bit problematic. @TheCakeIsNaOH @AdmiringWorm perhaps you can advise on what is best to be done here to unblock these, or any help needed?

Currently all three packages are complaining about an invalid `ProjectSourceUrl` which seems to be spurious (although I recall the error on `3.2` earlier was something different).

Regarding the immediate issue, perhaps `ruby-lang.org` is blocking the automation, and we can switch to the GitHub mirror at https://github.com/ruby/ruby ?

https://github.com/chocolatey-community/chocolatey-packages/blob/e553951ffb1f0574c696a5508f1070213770a47c/automatic/ruby/ruby.nuspec#L30-L30
https://github.com/chocolatey-community/chocolatey-packages/blob/e553951ffb1f0574c696a5508f1070213770a47c/automatic/ruby.install/ruby.install.nuspec#L29

https://community.chocolatey.org/packages/ruby.portable/3.3.0.1
https://community.chocolatey.org/packages/ruby.install/3.3.0.1
https://community.chocolatey.org/packages/ruby/3.3.0.1

**Comment by AdmiringWorm** [comment]
@chadlwilson thanks for investigating, and yes, as a temporary solution it sounds like switching to the GitHub mirror would be appropriate in this case (at least for now).

Could you put up a PR to update the `projectSourceUrl` for these packages? (can be done in this case for all three packages in the same PR).

I can then schedule a build to push a version up to replace the one in the failing queue.

If you put up a PR, just reference me as well, so I am aware of it.
