### ISSUE TITLE
(packageName) 

### ISSUE THREAD

**Issue by hms54** [chocolatey-community/chocolatey-packages#2265]
### Chocolatey Version

2.2.0

### Chocolatey License

None

### Package Version

3.19.0 and v3.21.0

### Current Behaviour

The Description page in Chocolaty GUI for Mp3tag v3.19.0 has a link to Version History that does not work.   Clicking that link throws a system error message.   I updated Mp3tag to v3.21.0 and it has the same issue with the Version History link.   The other links on that page work as expected.  

### Expected Behaviour

I would expect it to bring up a web page showing the version history of Mp3tag.   

### Steps To Reproduce

1. Launch Chocolatey GUI and open previously installed Mp3tag icon.
2. Click on Version History in the Note section.
3. Unhandled Exception window will pop up.  [Unhandled Exception.pdf](https://github.com/chocolatey-community/chocolatey-packages/files/12210247/Unhandled.Exception.pdf)
4. Click OK to close exception window and Chocolatey GUI window closes as well. 

### Environment

```markdown
- Operating System: Windows 10
- PowerShell Version:  5.1.19041.3031
- Shell:
```

### Chocolatey Log

```shell
Not sure how to do this.   If you can't reproduce the error, let me know and I'll figure out how to post this.
```

**Comment by corbob** [comment]
This is a chocolatey Gui issue: https://github.com/chocolatey/ChocolateyGUI/issues/772

Effectively chocolatey Gui doesn't handle the link not being a valid url, and so it causes an error.
