### ISSUE TITLE
(webstorm) When installing a new WebStorm minor version (e.g. 2023.2.0), an empty directory under `Program Files (x86)\JetBrains\WebStorm 2023.2.0` is created

### ISSUE THREAD

**Issue by 9numbernine9** [chocolatey-community/chocolatey-packages#2266]
### Chocolatey Version

2.2.0

### Chocolatey License

None

### Package Version

2023.2.0

### Current Behaviour

Hello! 

When installing the latest version of WebStorm (`2023.2.0`), line 9 sets the `$installDir` variable to `$programFiles\JetBrains\WebStorm $env:ChocolateyPackageVersion`. Unfortunately, this value is not quite correct for new WebStorm minor versions: when a WebStorm version number ends in `.0`, the directory that the WebStorm installer will install itself into will _omit_ the `.0` patch version.

The end result of this is that we end up with two directories under `Program Files (x86)`:
- `Program Files (x86)\JetBrains\WebStorm 2023.2`, where the installer installed itself and placed all the code.
- `Program Files (x86)\JetBrains\WebStorm 2023.2.0`, an empty directory created by the `ChocolateyInstall.ps1` script.

Although this doesn't cause any errors, it is slightly confusing.

### Expected Behaviour

Only one directory for a WebStorm install should be created, not two.

### Steps To Reproduce

- Install WebStorm `2023.2.0` via Chocolatey.
- In Windows Explorer, go to `C:\Program Files (x86)\JetBrains`
- Observe that there are two similar directories: `WebStorm 2023.2` ✅ and `WebStorm 2023.2.0` ❌

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19045.0
- PowerShell Version: 5.1.19041.3031
- Shell: cmd
```

### Chocolatey Log

```shell
N/A
```

### Anything else?

This is essentially the same issue that appears in version `2023.2.0` of the `DataGrip` package discussed here:
https://github.com/chocolatey-community/chocolatey-packages/issues/2257

**Comment by 9numbernine9** [comment]
Still relevant.

**Comment by pauby** [comment]
@9numbernine9 is your intention to put a PR in to fix this?

**Comment by 9numbernine9** [comment]
Still relevant - PR was raised so I'm not sure why this issue was closed.
