### ISSUE TITLE
graphviz 8.1.0

### ISSUE THREAD

**Issue by wernsdoerfer** [chocolatey-community/chocolatey-packages#2268]
### Chocolatey Version

Other (note in the comments)

### Chocolatey License

None

### Package Version

graphviz 8.1.0

### Current Behaviour

**choco install graphviz --version 8.1.0 -y**
returns
Chocolatey v0.12.1
Installing the following packages:
graphviz
By installing, you accept licenses for the packages.
Progress: Downloading Graphviz 8.1.0... 100%

Graphviz v8.1.0 [Approved]
graphviz package files install completed. Performing other installation steps.
Attempt to use original download file name failed for 'C:\ProgramData\chocolatey\lib\Graphviz\tools\graphviz-8.1.0 (64-bit) EXE installer.exe'.
Copying graphviz
  from 'C:\ProgramData\chocolatey\lib\Graphviz\tools\graphviz-8.1.0 (64-bit) EXE installer.exe'
Cannot find path 'C:\ProgramData\chocolatey\lib\Graphviz\tools\graphviz-8.1.0 (64-bit) EXE installer.exe' because it does not exist.
ERROR: Chocolatey expected a file to be downloaded to 'C:\Users\thoma\AppData\Local\Temp\chocolatey\Graphviz\8.1.0\graphvizInstall.exe' but nothing exists at that location.
The install of graphviz was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\Graphviz\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - graphviz (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\Graphviz\tools\chocolateyInstall.ps1'.
 See log for details.

### Expected Behaviour

choco install graphviz --version 8.1.0 -y
...
Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

The installation of choco install graphviz --version 8.0.5 -y always succeeds.

### Steps To Reproduce

open windows powershell as admin
run choco install graphviz --version 8.1.0 -y

### Environment

```markdown
- Operating System: Windows 10
- PowerShell Version: 5.1.19041.3031
- Shell:
```

### Chocolatey Log

```shell
https://gist.github.com/wernsdoerfer/3dff5b16336cdbb93392fc061c7b8a32
```

### Anything else?

I am using chocolatey for some other programs, they make no problems, only graphviz 8.1.0.

**Comment by pauby** [comment]
> Chocolatey v0.12.1

We don't support that version of Chocolatey CLI. Can you upgrade to the latest version and re-try?

**Comment by wernsdoerfer** [comment]
thanks for the tip. I have upgraded chocolatey to v2.2.0 and everything is working fine.
