### ISSUE TITLE
(vscode) Outdated

### ISSUE THREAD

**Issue by chimmmpie** [chocolatey-community/chocolatey-packages#2269]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.81.0

### Download location

https://az764295.vo.msecnd.net/stable/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/VSCodeUserSetup-x64-1.81.0.exe

### Package Page

https://community.chocolatey.org/packages/vscode

**Comment by mwtrigg** [comment]
Simply updating the download URL for 64-bit isn't sufficient.  The core issue is that the URLs used to check for newer version availability is out of date in [automatic/vscode.install/update.ps1](https://github.com/chocolatey-community/chocolatey-packages/blob/be95cd767c3ae438f5734e791b22f5323c70d729/automatic/vscode.install/update.ps1).  The versions can easily be scraped from [https://api.github.com/repos/microsoft/vscode/releases/latest](https://api.github.com/repos/microsoft/vscode/releases/latest); however, the download URLs are not present in the return.

More investigation is needed to determine where the setup files can be found (in an automated fashion going forward).

**Comment by chimmmpie** [comment]
One option is to monitor github releases or
https://code.visualstudio.com/updates redirects to latest version (version is not in the same format)

Download url seems to be 
https://update.code.visualstudio.com/1.81.0/win32-x64/stable

So download url https://update.code.visualstudio.com/{{ release_version }}/win32-x64/stable should work.


In the update check of visual studio i find the following code:
```
	) -> Result<Release, AnyError> {
		let update_endpoint =
			VSCODE_CLI_UPDATE_ENDPOINT.ok_or_else(UpdatesNotConfigured::no_url)?;
		let download_segment = target
			.download_segment(platform)
			.ok_or_else(|| CodeError::UnsupportedPlatform(platform.to_string()))?;
		let download_url = format!(
			"{}/api/versions/{}/{}/{}",
			update_endpoint,
			version,
			download_segment,
			quality_download_segment(quality),
		);
```
https://github.com/microsoft/vscode/blob/85daa35afb86202badbee79532537bf226961f25/cli/src/update_service.rs#L68
But so far i have been unable to find VSCODE_CLI_UPDATE_ENDPOINT

**Comment by chimmmpie** [comment]
The download url is documented here https://code.visualstudio.com/docs/supporting/faq#_how-do-i-do-an-offline-installation-of-vs-code

**Comment by chimmmpie** [comment]
https://update.code.visualstudio.com/api/versions/1.81.0/win32-x64/stable

source: https://stackoverflow.com/a/69810842

So workflow would be monitor gitlab. Check above url for release data of the binary. If not yet there try again after 1 day.

**Comment by chimmmpie** [comment]
https://github.com/chocolatey-community/chocolatey-packages/pull/2264

**Comment by Roemer** [comment]
> One option is to monitor github releases or https://code.visualstudio.com/updates redirects to latest version (version is not in the same format)
> 
> Download url seems to be https://update.code.visualstudio.com/1.81.0/win32-x64/stable
> 
> So download url [https://update.code.visualstudio.com/{{](https://update.code.visualstudio.com/%7B%7B) release_version }}/win32-x64/stable should work.
> 
> In the update check of visual studio i find the following code:
> 
> ```
> 	) -> Result<Release, AnyError> {
> 		let update_endpoint =
> 			VSCODE_CLI_UPDATE_ENDPOINT.ok_or_else(UpdatesNotConfigured::no_url)?;
> 		let download_segment = target
> 			.download_segment(platform)
> 			.ok_or_else(|| CodeError::UnsupportedPlatform(platform.to_string()))?;
> 		let download_url = format!(
> 			"{}/api/versions/{}/{}/{}",
> 			update_endpoint,
> 			version,
> 			download_segment,
> 			quality_download_segment(quality),
> 		);
> ```
> 
> https://github.com/microsoft/vscode/blob/85daa35afb86202badbee79532537bf226961f25/cli/src/update_service.rs#L68 But so far i have been unable to find VSCODE_CLI_UPDATE_ENDPOINT

I investigated in this as well.

The update URL is build in [`src/vs/platform/update/electron-main/abstractUpdateService.ts`](https://github.com/microsoft/vscode/blob/b6b13f96709f3685d8688d79d7b44609a52c5f3c/src/vs/platform/update/electron-main/abstractUpdateService.ts#L18C2-L18C2) and the placeholders in there come from `product.json` which is only completed on an installation (the one from the repo itself is incomplete and missing this placeholders).

So with the placeholders replaced from an installation (1.80.1), I get the following url:
https://update.code.visualstudio.com/api/update/win32/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771
which indeed does point to the newest version.

So as you see, the URL is built with the commit from the currently installed version. What we could do is also store that commit hash somewhere and use that for checking for updates in in case of an update, also update the commit hash beside the version number.

**Comment by pauby** [comment]
As I mentioned over [here](https://github.com/chocolatey-community/chocolatey-packages/pull/2264#issuecomment-1674976355), we should GitHub releases unless there is a reason not to. This would be preferable to an undocumented API call.

**Comment by chimmmpie** [comment]
Thanks @Roemer and @pauby
