### ISSUE TITLE
cmake: uninstalling cmake package remove the VS Code

### ISSUE THREAD

**Issue by jozefizso** [chocolatey-community/chocolatey-packages#2270]
### Chocolatey Version

1.4.0

### Chocolatey License

None

### Package Version

v3.27.1

### Current Behaviour

I wanted to uninstall the `cmake` package (because for whatever reason choco does not install it correctly and I cannot use `cmake` after installing it with `choco install cmake -y`).

I ran the uninstall command `choco uninstall cmake -y` using Admin prompt.

As cmake was being uninstalled it asked my to close VS Code (which was running at the moment). After I closed VS Code the uninstaller removed VS Code.

### Expected Behaviour

Do uninstall only requested package.

### Steps To Reproduce

```
choco uninstall cmake -y
```

### Environment

```markdown
- Operating System: Windows 11
- PowerShell Version: 7.2
- Shell: Windows Terminal
```

### Chocolatey Log

```shell
https://gist.github.com/jozefizso/ad791d35a3ce01380b26d0ef7c27530f
```

**Comment by pauby** [comment]
@jozefizso For open-source users, [you should run the latest version of Chocolatey CLI](https://docs.chocolatey.org/en-us/chocolatey-components-dependencies-and-support-lifecycle#product-support-lifecycle). Can you reproduce this on the latest version?

I started a Windows 11 VM here and installed VS Code manually (as it looks like you did this as the `vscode` package wasn't installed), launched it, installed `cmake` and then uninstalled `cmake` and VS Code was still installed (and open). So I can't reproduce this, issue. Note that I'm running 2.2.0.
