### ISSUE TITLE
(kubelogin) Not available as kubectl plugin

### ISSUE THREAD

**Issue by Nyami** [chocolatey-community/chocolatey-packages#2282]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

 1.28.0

### Current Behaviour

After installing the package the plugin is not available to kubectl as expect, running `kubectl plugin list` yields no results.

The [kubectl plugin mechanism](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) expects the kubelogin binary to be on your path under the name kubectl-oidc_login.

### Expected Behaviour

`kubectl plugin list` should list kubelogin

### Steps To Reproduce

1. Run `choco install kubectl`
2. Run `choco install kubelogin`
3. Run `kubectl plugin list`

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22621.0
- PowerShell Version: 5.1.22621.1778
- Shell: Windows PowerShell
```

### Chocolatey Log

```shell
NA
```

### Anything else?

The original package author @jetersen is of the opinion that the the file should not be renamed, and is/was using `kubelogin.exe` on path to use in the kubeconfig for Windows, see https://github.com/chocolatey-community/chocolatey-packages/issues/2074

It is my expectation that by installing kubelogin, which is a kubectl plugin, it should 'just work' as a plugin without additional steps, perhaps things evolved over time that it doesnt fully work as expected, and given it maybe used as per the original package author, I think adding an alternative shim with the expect kubectl plugin name format would work?

**Comment by jetersen** [comment]
Resolved in
https://github.com/chocolatey-community/chocolatey-packages/pull/2283

**Comment by gep13** [comment]
@jetersen thanks for the reminder!  I will go ahead and close out this issue!
