### ISSUE TITLE
(firefox) Match upstream versioning

### ISSUE THREAD

**Issue by opoplawski** [chocolatey-community/chocolatey-packages#2290]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

117.0.0

### Current Behaviour

The Chocolatey packages for Firefox and Thunderbird add an extra `.0` for the initial releases, e.g `117.0.0` while upstream just uses a single one: `117.0`, see https://www.mozilla.org/en-US/firefox/117.0/releasenotes/.  It would be helpful if the versions matched.

### Expected Behaviour

Chocolatey firefox version would be `117.0`.

### Steps To Reproduce

choco list firefox

### Environment

```markdown
- Operating System:
- PowerShell Version:
- Shell:
```

### Chocolatey Log

```shell
Not needed.
```

**Comment by pauby** [comment]
SemVer v2, which Chocolatey products follow, requires a three part version number as a minimum with the 'missing parts' being added as 0. As Firefox only has a two part version number, a '0' is added as the third part.

I'll go ahead and close this as there is nothing to do for the package here, or Chocolatey. 117.0 and 117.0.0 are the same version.
