### ISSUE TITLE
AU is not updating package scripts in the repository

### ISSUE THREAD

**Issue by umol-unibas** [chocolatey-community/chocolatey-packages#2291]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

116.0.5845.141

### Download location

https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise64.msi

### Package Page

https://community.chocolatey.org/packages/GoogleChrome

**Comment by umol-unibas** [comment]
Could be please update the github-repo considering googlechrome? We depend on the latest chocolateyinstall.ps1 script. Are there any circumstances preventing you from updating this? Would be great! Thanks

**Comment by pauby** [comment]
A change was made that inadvertently stopped AU from updating the commits here on the repository. That's been fixed a couple of hours ago, and I'll check that the commits are being pushed once there are new packages updated (so far there haven't been any updates).

**Comment by pauby** [comment]
Just to be clear, the package wasn't outdated and all packages updated were pushed to the Chocolatey Community Repository as normal. The only par that didn't work was updating the scripts in this repository with those updates.

**Comment by pauby** [comment]
We have our [first commit from AU](https://github.com/chocolatey-community/chocolatey-packages/commit/b6f357b89b5be41dfd32634707ef146fece3d697), so this appears to be resolved. I will leave it open for a little while until there are more commits.

**Comment by umol-unibas** [comment]
Great! Thanks for answering and explaining. We'll then just wait. You can close the issue from my point of view then.
