### ISSUE TITLE
GoogleChrome 116.0.5845.141 - checksum did not meet

### ISSUE THREAD

**Issue by relaxx22** [chocolatey-community/chocolatey-packages#2294]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

116.0.5845.141

### Current Behaviour

Running 'choco install googlechrome' produces this error:

Download of googlechromestandaloneenterprise64.msi (95.47 MB) completed.
Error - hashes do not match. Actual value was 'C0AE0990EF93B4DDB4C056C062D60B1CDFCF0DC48D9702089372E90432F5BFC5'.
ERROR: Checksum for 'C:\Users\USERNAME\AppData\Local\Temp\chocolatey\GoogleChrome\116.0.5845.141\googlechromestandaloneenterprise64.msi' did not meet 'c38c81f95bb295567fe5b68904fb4e0d771cdcf636993dc22fdc4564d8d990b8' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of GoogleChrome was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\GoogleChrome\tools\chocolateyInstall.ps1'.
 See log for details.

### Steps To Reproduce

Running a simple command 'choco install googlechrome'

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19045.0
- PowerShell Version: 5.1.19041.3031
- Shell: Powershell
```

### Chocolatey Log

```shell
https://gist.github.com/relaxx22/c99742a5930a767c2bbdf1dd9e2d01ef
```

**Comment by pauby** [comment]
This is addressed in the [Notes section of the Package Page Description](https://community.chocolatey.org/packages/googlechrome#description).

I'll go ahead and close this, as there is nothing for us to do.
