### ISSUE TITLE
(libreoffice-help) package "LibreOffice Help Pack 5.2.0" outdated by far, seems unmaintained for long time

### ISSUE THREAD

**Issue by zWhdmB5T** [chocolatey-community/chocolatey-packages#2310]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

7.5.6

### Download location

https://download.documentfoundation.org/libreoffice/stable/7.5.6/win/x86_64/

### Package Page

https://github.com/chocolatey-community/chocolatey-packages/tree/master/manual/libreoffice-help

**Comment by zWhdmB5T** [comment]
please, have a look here…

https://github.com/orgs/chocolatey-community/discussions/2311#discussioncomment-7010236

**Comment by pauby** [comment]
This is a manually updated package. See the [README](https://github.com/chocolatey-community/chocolatey-packages/blob/master/manual/libreoffice-help/README.md) and [this issue that it points to](https://github.com/chocolatey-community/chocolatey-packages/issues/762).

**Comment by zWhdmB5T** [comment]
I followed both links.

[README](https://github.com/chocolatey-community/chocolatey-packages/blob/master/manual/libreoffice-help/README.md) explains the language specific settings, and it says that this package is unmaintained (yes, it is, indeed!) and refers to [this issue that it points to](https://github.com/chocolatey-community/chocolatey-packages/issues/762). There, I (personally don't get why this package can't turned into AU.

But, what is obvious: the package, being a manual update package, is unmaintained for a long time. It is outdated by far. I seriously wonder what is the problem with this package? I just don't get it. I don't want to troll. I am really interested why this package cannot be turned into AU, is hard to maintained, is currently unmaintained. (I personally would like to use it.)

**Comment by pauby** [comment]
My suggestion would therefore be to submit a PR to have the package automatically updated.

**Comment by zWhdmB5T** [comment]
I'm not familiar with that, don't know how to provide all necessary details for an appropriate PR. Can you @pauby  do this perhaps?

**Comment by pauby** [comment]
@zWhdmB5T you're frustrated that the package is not being maintained and that it should be automatic.

This repository is a community maintained repository. If you need a package to be something that it isn't, it's expected you get involved and do the work.

The best way for this package to be updated is for somebody who has a need for it to be updated and submit a pull request.

**Comment by zWhdmB5T** [comment]
@pauby well yes, you're right, I am frustrated by this situation. But I want want to make clear that I do not demand anything but just kindly ask for. I appreciate and I value OpenSourceSoftware and related projects. I have donated quite some money to several authors and projects. But I cannot directly help here, because I am not into programming and coding at all. I am just a humble user. Sometimes writing a bug report. And sometime posting a request like in this case.  That's all I have GH for. Sorry, if my post was somewhat offensive. I didn't want to be rude.

**Comment by pauby** [comment]
Your post wasn't offensive or rude. I was just trying to make it clear how this repository runs and what the best and quickest way for the package to be updated, is.

There are ~400 packages in here and a small team of active maintainers.

**Comment by zWhdmB5T** [comment]
OK, understood now. Then, thank you.

By the way, I feel always sad that I am not into programming or coding. There have been many occasions where it would have been helpful. I am very sorry.
