### ISSUE TITLE
(JabRef) request new version: JabRef 5.10 (not --pre i.e. 6.0-dev)

### ISSUE THREAD

**Issue by zWhdmB5T** [chocolatey-community/chocolatey-packages#2313]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

5.10

### Download location

https://github.com/JabRef/jabref/releases/download/v5.10/JabRef-5.10.msi

### Package Page

https://github.com/OlafHaag/chocolatey-packages/tree/master/automatic/jabref

**Comment by AdmiringWorm** [comment]
This is not a package maintained by this repository. Please contact the proper package maintainer for this package.
