### ISSUE TITLE
(Spotify) Package fails to finish if Spotify does not launch as expected

### ISSUE THREAD

**Issue by endy-y** [chocolatey-community/chocolatey-packages#2314]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

1.2.20.1218

### Current Behaviour

the latest package is "acting up" again, I mean not running `.exe` file as it should. However, if I run it manually from the downloaded location: `..\AppData\Local\Temp\chocolatey\spotify\`  it updates successfully

### Expected Behaviour

the package update smoothly on its own

### Steps To Reproduce

1. Run: choco upgrade spotify
2. Wait for it to get stack on: **_SUCCESS: The scheduled task "spotify" was successfully deleted._**
3. Upgrade newer finishes if you do not run .exe manually

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19045.0
- PowerShell Version: 7.3.7
```

### Chocolatey Log

```shell
spotify v1.2.20.1218 (forced) [Approved]
spotify package files install completed. Performing other installation steps.
Downloading spotify
  from 'https://download.scdn.co/SpotifySetup.exe'
Progress: 100% - Completed download of C:\Users\user\AppData\Local\Temp\chocolatey\spotify\1.2.20.1218\SpotifyFullSetup.exe (992.97 KB).
Download of SpotifyFullSetup.exe (992.97 KB) completed.
Hashes match.
SUCCESS: The scheduled task "spotify" has successfully been created.
SUCCESS: Attempted to run the scheduled task "spotify".
SUCCESS: The scheduled task "spotify" was successfully deleted.
```

**Comment by JPRuskin** [comment]
It looks like the package is waiting for Spotify.exe to run, in order to kill it - we should possibly add logic to timeout after ~30-60 seconds (or some other agreed, reasonable time).

**Comment by endy-y** [comment]
Thanks for the reply, I tried to replicate it myself, but for some reason both the version mentioned here and a new one, installed just fine today. So my guess is, it was either timeout as you suggested, or some other not-persistent issue

**Comment by Quack6765** [comment]
Issue seems to be when you already have Spotify installed but without using Chocolatey. I uninstalled the Spotify package from Chocolatey, located the already installed instance of Spotify on my PC and uninstalled it too. Can install correctly with Chocolatey after that.

**Comment by pauby** [comment]
There is a [PR](https://github.com/chocolatey-community/chocolatey-packages/pull/2263) up to fix that.

**Comment by JPRuskin** [comment]
Given all of the above, I think we can close this issue for now. If we find that it rears up again, we can add a timeout - but as the issue seems rather rare, I'd not say it's at all urgent.
