### ISSUE TITLE
VScode Version 1.83.0 needs a Validation Re-run

### ISSUE THREAD

**Issue by og-mrk** [chocolatey-community/chocolatey-packages#2323]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

1.83.0

### Current Behaviour

The package validation for `vscode` failed Because it depends on `vscode.install` package, [at the time that test was ran](https://gist.github.com/choco-bot/11d5d7b23cf6ce7e34983bdc65abf0ed), `vscode.install` hadn't had a version labeled `1.83.0`, [displayed in this line of install.txt log](https://gist.github.com/choco-bot/11d5d7b23cf6ce7e34983bdc65abf0ed#file-install-txt-L225).

### Expected Behaviour

The validation test for `vscode` version `1.83.0` runs with no error(s).

### Steps To Reproduce

1. In powershell environment running as admin
2. Run `choco install vscode --version=1.83.0`
3. See the error displayed (if any), When [the validation test was ran](https://gist.github.com/choco-bot/11d5d7b23cf6ce7e34983bdc65abf0ed), if you don't see any error(s), then this issue is fixed

### Environment

```markdown
- Operating System: win2012r2x64 (Windows Server 2012 R2 x64)
- PowerShell Version: choco-bot's Powershell Default Powershell version ([at the time of test](https://gist.github.com/choco-bot/11d5d7b23cf6ce7e34983bdc65abf0ed))
- Shell: choco-bot's Default Shell
```

### Chocolatey Log

```shell
https://gist.github.com/choco-bot/11d5d7b23cf6ce7e34983bdc65abf0ed#file-install-txt
```

**Comment by pauby** [comment]
This was rerun by @AdmiringWorm earlier.

**Comment by og-mrk** [comment]
ok thanks 🤍
