### ISSUE TITLE
(vlc) is outdated

### ISSUE THREAD

**Issue by og-mrk** [chocolatey-community/chocolatey-packages#2341]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

3.0.20

### Download location

https://www.videolan.org/vlc/download-windows.html

### Package Page

https://community.chocolatey.org/packages/vlc/

**Comment by pauby** [comment]
The package was submitted yesterday to the Chocolatey Community Repository. It's not outdated. It needs to be exempted as it's failing validation.

Please leave some time between a new version being released and it being available on the Community Repository.

**Comment by og-mrk** [comment]
My bad @pauby , didn't know that and thanks for your reply, appreciate the time you've taken to inform my mistake 🤍
