### ISSUE TITLE
(vscode.install) outdated - now 1.84.1

### ISSUE THREAD

**Issue by DanielRose** [chocolatey-community/chocolatey-packages#2344]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.84.1

### Package Page

https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/vscode.install

**Comment by pauby** [comment]
When was 1.84.1 released? GitHub releases page makes it difficult to determine.

**Comment by pauby** [comment]
@roemer [you were last to look at this](https://github.com/chocolatey-community/chocolatey-packages/pull/2276). Can you pick this up?

**Comment by DanielRose** [comment]
<https://update.code.visualstudio.com/1.84.1/win32-x64/stable> works, but <https://update.code.visualstudio.com/1.84.1/win32/stable> does not

**Comment by pauby** [comment]
@DanielRose are you able to raise a PR for this?

**Comment by DanielRose** [comment]
I'm working on it. I am not able to get the automatic update check running locally, but I only removed the 32-bit checks. I hope that is ok.

**Comment by pauby** [comment]
[That appeared to fix it](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#vscodeinstall) and the [package has been pushed](https://community.chocolatey.org/packages/vscode.install/1.84.1). Thanks for the fix @DanielRose. 

I wonder if it's the same issue with `vscode.insiders`.

I'll go ahead and close this now.
