### ISSUE TITLE
git, git.install - Unhelpful feedback when failing

### ISSUE THREAD

**Issue by velle** [chocolatey-community/chocolatey-packages#2346]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

2.42.0

### Current Behaviour

Git needed to be updated:

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/4488298/cb0b9a1b-6b6d-45bc-bf22-b9da25d0b489)

I could not update git, but got no helpful feedback. 

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/4488298/143620af-c113-4d4c-8bbe-366abddab1c9)

If I instead explicitly ask it to install git.install, the output is slightly more helpful:

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/4488298/a03bef99-db07-4364-9768-2e43fe9d57b0)

I looked inside the log, and I only found these two lines:

    2023-11-10 11:09:34,104 15860 [DEBUG] - Command ["C:\ProgramData\chocolatey\lib\git.install\tools\Git-2.42.0-64-bit.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOCANCEL /SP- /LOG /COMPONENTS="icons,assoc,assoc_sh,ext,ext\shellhere,ext\guihere,gitlfs,icons\quicklaunch" ] exited with '1'.
    2023-11-10 11:09:34,128 15860 [ERROR] - ERROR: Running ["C:\ProgramData\chocolatey\lib\git.install\tools\Git-2.42.0-64-bit.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOCANCEL /SP- /LOG /COMPONENTS="icons,assoc,assoc_sh,ext,ext\shellhere,ext\guihere,gitlfs,icons\quicklaunch" ] was not successful. Exit code was '1'. See log for possible error messages.

I believe there is nothing in the log about why it failed. Maybe because `/VERYSILENT` suppresses every kind of output, even errors? 

### Expected Behaviour

When calling `choco install git` I would expect both an error and useful feedback, instead of just "0 out of 1 upgraded". 

When calling `choco install git.install` at least I get an error (in red font), but I would expect to also get some helpful feedback. 

In this particular case, the installer returned status 1 because git version 2.42.0 was already installed; but it was far from obvious and it took some time to figure out, since no feedback was provided. 

### Steps To Reproduce

I'm not sure how I ended up having git 2.42.0 installed while choco believed I only had version 2.41.0. Maybe I simply installed it manually some time ago, and then I forgot about it?

### Environment

```markdown
- Operating System: [System.Environment]::OSVersion.ToString()
Microsoft Windows NT 10.0.19045.0
- PowerShell Version: 
    Name                           Value
    ----                           -----
    PSVersion                      5.1.19041.3636
    PSEdition                      Desktop
    PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
    BuildVersion                   10.0.19041.3636
    CLRVersion                     4.0.30319.42000
    WSManStackVersion              3.0
    PSRemotingProtocolVersion      2.3
    SerializationVersion           1.1.0.1
```

### Chocolatey Log

```shell
https://gist.github.com/velle/404987db7dfe629054eb11672df90fcb
```

**Comment by pauby** [comment]
The issue is that you didn't upgraded `git.install`. You upgraded `git`.


You had the latest version of the `git` package so when upgrading it, nothing was done. The message shown indicates that nothing was done so no error could be shown (as nothing was done to cause an error).
![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/0c064fff-5c81-458a-889a-a4bc0e7508a4)
2. The `git.install` package has an issue so the error was shown

**Comment by velle** [comment]
I actually did try to read about the `git` vs `git.install` before posting. I read that it was first a meta package, and in later versions of choco a virtual package. I got the understanding that using the identifier `git` in the command would upgrade `git.install`.

If simply considering them two different packages, and if the `git` package was indeed upgraded to 2.42.0, then I see now, that the output when I tried to upgrade `git` was exactly what it should be. 

Oops. And thanks.

**Comment by velle** [comment]
> > I got the understanding that using the identifier git in the command would upgrade git.install.
> 
> It will, but only if the `git` package is installed / upgraded. If that doesn't happen then it does nothing.

So it seems that somehow `git` was version 2.42.0 while `git.install` was version 2.41.0. Is that an invalid/corrupted state? Is that the real crime here; that this was never supposed to happen? :)

**Comment by velle** [comment]
Have I understood you correctly, that it would still be appropriate/meaningful if I create a separate issue on how `choco install git.install` failed to provide any helpful feedback? If I leave out everything about `choco install git`.

**Comment by pauby** [comment]
> So it seems that somehow `git` was version 2.42.0 while `git.install` was version 2.41.0. Is that an invalid/corrupted state? Is that the real crime here; that this was never supposed to happen? :)

It's possible to happen. I cna't say why it happened on your system. Both packages are at version 2.42.0 in the Chocolatey COmmunity Repository and were approved on 22 August.

> Have I understood you correctly, that it would still be appropriate/meaningful if I create a separate issue on how choco install git.install failed to provide any helpful feedback? 

You said above the output was helpful. That is simply the output from the normal git installer. 

https://user-images.githubusercontent.com/4488298/282051341-a03bef99-db07-4364-9768-2e43fe9d57b0.png

What output are you looking for?

**Comment by velle** [comment]
> You said above the output was helpful. That is simply the output from the normal git installer.

I have tried to make it clear below. Let me know if you understand my intention. Even if you (and/or the choco community) disagree :)

### `choco install git` - Output is correct and as expected  (but could be even more clear)

Initially I thought the output was outright wrong, because it did not produce an error message. I realize now that the output is exactly as intended. So no bugs or anything. 

However, the choco tool could be even more helpful to the user. The message does give the most recent available version of the package, but it does not state which version is installed, or that the version installed is the same as the most recent in the sources. Here is a crude illustration. 

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/4488298/dc320f93-9566-4c25-b153-1cda70d42842)

### `choco install git.install` - Git-2.42.0-64-bit.exe failed, but where is its output?

I believe the update.ps1 is responsible for executing Git-2.42.0-64-bit.exe. Im guessing that under normal circumstances when calling Git-2.42.0-64-bit.exe, it will print some feedback about why it exits with a non-zero status. But because update.ps1 tells Git-2.42.0-64-bit.exe to be quite, using /VERYSILENT, this feedback is lost, and does not even end up in the log. 

Personally I would have preferred that any error output from Git-2.42.0-64-bit.exe would also be shown in the terminal, but the choco conventions may disagree. 

But the error output of Git-2.42.0-64-bit.exe is not even in the log file. That seems really wrong. Does it not?

I have never written a PowerShell script, but I'm guessing its possible to run Git-2.42.0-64-bit.exe without /VERYSILENT, and then simply redirect all the output to the log, so it wont clutter the screen.
