### ISSUE TITLE
(calibre) Outdated

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-packages#2355]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

7.0.0

### Download location

https://download.calibre-ebook.com/7.0.0/calibre-64bit-7.0.0.msi

### Package Page

https://community.chocolatey.org/packages/calibre

**Comment by WillScarlettOhara** [comment]
Newer version
https://github.com/kovidgoyal/calibre/releases/download/v7.1.0/calibre-64bit-7.1.0.msi

**Comment by Kroesss** [comment]
7.2 is released.
https://github.com/kovidgoyal/calibre/releases/tag/v7.2.0

**Comment by gep13** [comment]
A [PR](https://github.com/chocolatey-community/chocolatey-packages/pull/2356) for this has been made, and merged.  An updated version of Calibre should be available soon once all the automated checks as complete.

Thanks to @TheCakeIsNaOH for doing this PR.
