### ISSUE TITLE
(googlechrome) Outdated

### ISSUE THREAD

**Issue by KWattie97** [chocolatey-community/chocolatey-packages#2380]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

120.0.6099.110

### Download location

https://www.google.com/intl/en_ca/chrome/next-steps.html?statcb=1&installdataindex=empty&defaultbrowser=0#

### Package Page

https://community.chocolatey.org/packages/GoogleChrome

**Comment by TheCakeIsNaOH** [comment]
There is a PR here: https://github.com/chocolatey-community/chocolatey-packages/pull/2369

**Comment by AdmiringWorm** [comment]
The PR to resolve this issue has been merged, and a new version is being queued to be pushed to the Community Repository now.

If all goes well, it should become available in a few hours. Meanwhile, I'll be closing this issue now, but we can always re-open it if something goes wrong.
