### ISSUE TITLE
(k9s) outdated

### ISSUE THREAD

**Issue by horvaro** [chocolatey-community/chocolatey-packages#2383]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

0.29.1

### Download location

https://github.com/derailed/k9s/releases/tag/v0.29.1

### Package Page

https://github.com/derailed/k9s

**Comment by horvaro** [comment]
Checksum file name has changed from `checksums.txt` to `checksums.sha256`

https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/k9s/update.ps1#L27

**Comment by pauby** [comment]
There is a [PR for this already created](https://github.com/chocolatey-community/chocolatey-packages/pull/2343).

**Comment by AdmiringWorm** [comment]
I will be closing this issue now, as the PR is merged, and it looks like a new version of the package has been pushed.
