### ISSUE TITLE
(libreoffice-fresh) LibreOffice Fresh 7.6.2 to 7.6.3 and 7.6.4: Status still "Waiting for Maintainer" since last update (three weeks)

### ISSUE THREAD

**Issue by zWhdmB5T** [chocolatey-community/chocolatey-packages#2386]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

7.6.2 to 7.6.3 and 7.6.4

### Current Behaviour

Status still "Waiting for Maintainer" since last update

### Expected Behaviour

Status "Approved" (and fully available)

### Steps To Reproduce

doesn't apply

### Environment

```markdown
doesn't apply
```

### Chocolatey Log

```shell
doesn't apply
```

**Comment by pauby** [comment]
Version 7.6.2, 7.6.3 and 7.6.4 are all approved.

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/7bf0393b-148e-468a-a984-e88dcbc36632)
