### ISSUE TITLE
(InkScape) Inkscape 1.3.1 to 1.3.2: Status still "Waiting for Maintainer" since last update (four weeks)

### ISSUE THREAD

**Issue by zWhdmB5T** [chocolatey-community/chocolatey-packages#2387]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

1.3.1 to 1.3.2

### Current Behaviour

Status still "Waiting for Maintainer" since last update

### Expected Behaviour

Status "Approved" (and fully available)

### Steps To Reproduce

doesn't apply

### Environment

```markdown
doesn't apply
```

### Chocolatey Log

```shell
doesn't apply
```

**Comment by pauby** [comment]
Inkscape 1.3.1 and 1.3.2 are approved.

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/adb88e27-889f-4c6e-8c1f-73138014cfd6)
