### ISSUE TITLE
(blender) Project Source is pointing to non-existing location

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-packages#2391]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

4.0.2

### Current Behaviour

The specified project source URL specified in the blender nuspec file is now pointing to a location that does not load, and causes the validation on Chocolatey Community Repository to fail.

### Expected Behaviour

Validation should not fail for URLs, and we need to update this specified URL to the correct location.

### Steps To Reproduce

1. Go to https://community.chocolatey.org/packages/blender/4.0.2
2. Attempt to go to the Software Source
3. Notice the page never fully load, or times out

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A
```

**Comment by slizgi** [comment]
Hi can someone please fix this. it is still not working. I tried to look in to whole submiting package but for now it is a bit overwhelming...

**Comment by TheCakeIsNaOH** [comment]
@slizgi I have a PR open to fix this, see #2401 
It is waiting on a committer to this repository to review before it could be merged to fix the package.
