### ISSUE TITLE
(inkscape) Outdated - important bugfix-release 1.3.2

### ISSUE THREAD

**Issue by mgmax** [chocolatey-community/chocolatey-packages#2392]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.3.2

### Download location

https://inkscape.org/release/inkscape-1.3.2/windows/64-bit/msi/dl/

### Package Page

https://community.chocolatey.org/packages/InkScape

**Comment by mgmax** [comment]
"Inkscape 1.3.2 is an important bugfix release, which fixes a data loss bug in the recently released Inkscape 1.3.1, along with another, smaller issue. We recommend that you update Inkscape from 1.3.1 as soon as possible."

(Source: https://inkscape.org/release/inkscape-1.3.2/)

**Comment by mgmax** [comment]
Strange: In the package source the version is already 1.3.2: https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/inkscape/inkscape.nuspec#L6 

However it the package website says 1.3.1
https://community.chocolatey.org/packages/InkScape

and Inkscape is not in the moderation queue: https://community.chocolatey.org/packages?q=inkscape&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count

Where is it stuck?

**Comment by AdmiringWorm** [comment]
The package had been pushed previously, it seems, but it had failed the automatic validation and eventually rejected.

I'll get a new version pushed out, especially when I can't see any reason it should have failed.

**Comment by AdmiringWorm** [comment]
An updated package for version 1.3.2 has been pushed. I'll leave this issue open for a bit until it has been approved on the Community Repository.

**Comment by AdmiringWorm** [comment]
Just had a look at the status of the package now, and the new version is approved.

As such, I'll be closing this issue now.
