### ISSUE TITLE
(tixati) 1+ year and 5 releases behind

### ISSUE THREAD

**Issue by teknowledgist** [chocolatey-community/chocolatey-packages#2415]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

3.19

### Download location

https://download1.tixati.com/download/tixati-3.19-1.win64-install.exe

### Package Page

https://community.chocolatey.org/packages/tixati

**Comment by AdmiringWorm** [comment]
There is already a bug report regarding tixati #2182. This needs to be fixed before a new version will be available on the Chocolatey Community Repository.

As there is a bug report, I will be closing this issue.
