### ISSUE TITLE
(totalcommander) No Start Menu entries when deploying via Intune

### ISSUE THREAD

**Issue by strausmann** [chocolatey-community/chocolatey-packages#2425]
### Chocolatey Version

2.2.2

### Chocolatey License

Business

### Package Version

11.2.0

### Current Behaviour

After the installation there is no start menu entry, neither globally nor for the user himself.

### Expected Behaviour

After a successful installation, a start menu entry for Total Commander must be found.

### Steps To Reproduce

We install Total Commander for a few users via Microsoft Intune. We use IntuneWin for this.

The PowerShell script ChocoInstall.ps1 can be found in the Gist linked under Chocolatey Log. This is integrated into the IntuneWin file and serves us in this form as a standard package when we run a Chocolatey installation via Intune.

In the Gist you will also find the ChocoInstall.log, which shows a complete output of the ChocoInstall.ps1.

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22631.0
- PowerShell Version: 7.4.1
- Shell: PowerShell 7
```

### Chocolatey Log

```shell
https://gist.github.com/strausmann/e792262af9dc434aef2664405251ad41
```

**Comment by pauby** [comment]
This isn't an issue with the package but an issue on how it's being deployed.

I've just installed Totalcommander here on a Windows Server 2019 virtual machine I was working on and it created the Start Menu entries as expected.

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/03c0c142-2deb-4033-892c-d5cf2b99af45)

I can't see anything for us to do here.

**Comment by pauby** [comment]
As you are a licensed customer, my suggestion is you reach out to Chocolatey Support as they may be able to help you with the deployment via Intune. To do that, run `choco support` from the command line.

Note that packages on the Chocolatey Community Repository, including the ones in this repository, are not supported.
