### ISSUE TITLE
(cdburnerxp) suggest moving the package to manual

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey-community/chocolatey-packages#2427]
### Discussed in https://github.com/orgs/chocolatey-community/discussions/2402

<div type='discussions-op-text'>

<sup>Originally posted by **TheCakeIsNaOH** January  9, 2024</sup>
The cdburnerxp update script is currently failing due to a cerificate error. 
As per https://cdburnerxp.se/impressum the company behind it has shut down, so it is unlikely to be updated in the future. 
Thus, I think moving the package to be manual would make sense.</div>

**Comment by pauby** [comment]
Agreed. Makes sense to me. Would also give us a chance to vet the software for any 'additions' that new companies some times make.
