### ISSUE TITLE
(microsoft-vclibs-140-00) Automatic Validation Failed due to Mis-matched Checksum

### ISSUE THREAD

**Issue by og-mrk** [chocolatey-community/chocolatey-packages#2436]
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

14.0.33321

### Current Behaviour

The `choco-bot` that ran [This Test](https://gist.github.com/choco-bot/51a33f9a9dd4b63c35b45f47d8813fbd) has Errored-out on [This Line](https://gist.github.com/choco-bot/51a33f9a9dd4b63c35b45f47d8813fbd#file-install-txt-L532) for Mis-matched SHA256 Checksum Compare.

> [!NOTE]
> If you take a closer look at the Checksum of the Downloaded File (which's `A7FB9D76E07B36D868179EB53FFD13740C25242176FA363F154798CF34EDD4A9`), and the one being compared to it (`3195DB914BEA1534EE73582CD483C548A929AED2799D305B3BBF7411BA7A6C7D`), you'll see that the Checksum is Valid in reality, and the later one is being used to Verify the downloaded file **From the Previous Version**, you can try it out by downloading the `.appx` using Microsoft's [Official Link](https://aka.ms/Microsoft.VCLibs.x86.14.00.Desktop.appx), and generate a `SHA256` Checksum using a PowerShell Command:
`Get-FileHash .\path\to\downloaded\file\Microsoft.VCLibs.x86.14.00.Desktop.appx -Algorithm SHA256`

### Expected Behaviour

The Verification of the Downloaded `.appx` File is successful, and Choco continues on with the Installation of `microsoft-vclibs` package.

### Steps To Reproduce

1. have `choco` installed on your system
2. Install `microsoft-vclibs-140-00` package using `choco install microsoft-vclibs-140-00` inside of a Terminal running as admin
3. see the output being something like:
`ERROR: Checksum for 'C:\ProgramData\chocolatey\lib\microsoft-vclibs-140-00\tools\Microsoft.VCLibs.x86.14.00.Desktop.appx' did not meet '3195DB914BEA1534EE73582CD483C548A929AED2799D305B3BBF7411BA7A6C7D' for checksum type 'SHA256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.`

### Environment

```markdown
- Operating System: win2012r2x64 (Windows Server 2012 R2 x64)
- PowerShell Version: 5.1.17763.1 (According to `choco-bot` Logs)
- Shell: PowerShell
```

### Chocolatey Log

```shell
https://gist.github.com/choco-bot/51a33f9a9dd4b63c35b45f47d8813fbd
```

**Comment by TheCakeIsNaOH** [comment]
The sources for this package are not maintained in this repository. 
See this FAQ for how to find the package sources: https://docs.chocolatey.org/en-us/community-repository/faq#how-do-i-find-the-package-source

In this case, the correct source repository is here: https://github.com/pauby/chocopackages/tree/master/manual/microsoft-vclibs-140-00

**Comment by og-mrk** [comment]
ok, thanks for the help @TheCakeIsNaOH, my bad for not doing my research before opening this Issue, hope I didn't waste your time, and have a nice day

**Comment by og-mrk** [comment]
Also, for anyone curious about this issue, it's been reported before on [this issue](https://github.com/pauby/ChocoPackages/issues/207), so with some patience, the package will hopefully be approved after the moderation process has finished.
