### ISSUE TITLE
(diskgenius) New version 5.5.1.1508 is available.

### ISSUE THREAD

**Issue by mstick99** [chocolatey-community/chocolatey-packages#2437]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

5.5.1.1508

### Download location

https://www.diskgenius.com/

### Package Page

https://community.chocolatey.org/packages/diskgenius

**Comment by TheCakeIsNaOH** [comment]
The sources for this package are not maintained in this repository. 
See this page for the process if a package is outdated or broken: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process
