### ISSUE TITLE
(nodejs)(nodejs.install) Outdated

### ISSUE THREAD

**Issue by michha** [chocolatey-community/chocolatey-packages#2452]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

20.12.1 and 21.7.2

### Download location

https://nodejs.org/en/download

### Package Page

https://community.chocolatey.org/packages/nodejs

**Comment by michha** [comment]
The [Update-AUPackages.md](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f) lists the error message

> [au_GetLatest failed; The 64bit executable is the same as the 32bit](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#nodejs)

(this is also true for the package _nodejs.install_)

**Comment by michha** [comment]
I did a little analysis of the [nodejs.install/update.ps1](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/nodejs.install/update.ps1)
script:
- the message _The 64bit executable is the same as the 32bit_ is shown when the `$url32` and `$url64` are equal
- they are both empty because parsing of the content from https://nodejs.org/en/download didnt return the expacted result
- nodejs changed their download page in a way that requires to change the `update.ps1`

**Comment by pauby** [comment]
@michha are you in a position to submit a PR to fix this?

**Comment by michha** [comment]
The current website seems to be much harder to parse than it was. My first thought was to reach out to the nodejs team if they have a json file on their website. That would make it much easer to get the correct download links.
