### ISSUE TITLE
(putty.install) 

### ISSUE THREAD

**Issue by Aaron-P** [chocolatey-community/chocolatey-packages#2454]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

0.81

### Download location

https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

### Package Page

https://community.chocolatey.org/packages/putty.install

**Comment by Aaron-P** [comment]
The new version fixes a critical security vulnerability in versions 0.68 to 0.80.

https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/vuln-p521-bias.html

**Comment by TheCakeIsNaOH** [comment]
@Aaron-P v0.81.0 is in moderation:
https://community.chocolatey.org/packages/putty/0.81.0
