### ISSUE TITLE
(notepadplusplus) Notepad++ 8.6.5 -> 8.6.7

### ISSUE THREAD

**Issue by zWhdmB5T** [chocolatey-community/chocolatey-packages#2468]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

8.6.7

### Download location

https://notepad-plus-plus.org/downloads/v8.6.7/

### Package Page

https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/notepadplusplus

**Comment by pauby** [comment]
The Package Page URL needs to point to the package page. Can you correct it?

**Comment by pauby** [comment]
You checked this box but didn't check the queue:

> I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

The package version is awaiting moderation. Please ensue you check this before raising an issue in future. Thanks.
