### ISSUE TITLE
(nexus-repository) Outdated 

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#2474]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

3.68.1

### Download location

Unknown

### Package Page

https://community.chocolatey.org/packages/nexus-repository

**Comment by pauby** [comment]
The reason for the delay in updating this package is that [Sonatype have not published it on their GitHub for OSS users](https://github.com/sonatype/nexus-public/issues/395). This is where the latest version numbers for the package automation are taken from.

Note that there isn't anything that can be done to create a new package until this is published.

**Comment by tunisiano187** [comment]
It's possible to get it there : https://help.sonatype.com/en/download.html
Maybe it should check for the version on that page ?

**Comment by steviecoaster** [comment]
@tunisiano187 I appreciate we could do that, but that would cause a lot of extra work to keep the package maintained as any changes to that webpage would cause the automation to break, as it would be very fragile. It's _much_ more stable to call a known API that doesn't change except very very rarely. 

The side effect of their (being Sonatype's) decision to withold publishing the realise is unfortunate, but now that it is publicly announced there should be no reason for them not too.

I've raised such an issue at https://github.com/sonatype/nexus-public/issues/397 that hopefully they pick up on quickly. We shall see.

**Comment by steviecoaster** [comment]
The latest release, 3.68.1.2 is now available on the Chocolatey Community Repository. I'll go ahead and close this out
