### ISSUE TITLE
(mumble) Mumble 1.5.634 available

### ISSUE THREAD

**Issue by anoymouserver** [chocolatey-community/chocolatey-packages#2476]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

1.5.634

#### Note
Unlike the previous version (1.4.287), there is no longer an x86 release.

### Download location

https://github.com/mumble-voip/mumble/releases/tag/v1.5.634

### Package Page

https://community.chocolatey.org/packages/mumble

**Comment by daerSeebaer** [comment]
Looks like the mumble package update script is broken, I'm currently looking into it

**Comment by TheCakeIsNaOH** [comment]
Fixed by https://github.com/chocolatey-community/chocolatey-packages/pull/2479
Package approved and is available: https://community.chocolatey.org/packages/mumble/1.5.634
