### ISSUE TITLE
(libreoffice-still) 

### ISSUE THREAD

**Issue by zWhdmB5T** [chocolatey-community/chocolatey-packages#2485]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

7.6.7

### Download location

https://downloadarchive.documentfoundation.org/libreoffice/old/7.6.7.2/win/

### Package Page

https://community.chocolatey.org/packages/libreoffice-still

**Comment by TheCakeIsNaOH** [comment]
Package was automatically updated to v24.2.4 and is approved.
