### ISSUE TITLE
(rufus) create start menu shortcut

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#2488]
### Discussed in https://github.com/orgs/chocolatey-community/discussions/2487

<div type='discussions-op-text'>

<sup>Originally posted by **mica** June 12, 2024</sup>
### Before starting, ensure that you have done the following.

- [X] I have verified that there is no other issue or discussion covering the feature or enhancement
- [X] I have verified there is no open pull request for the feature or enhancement
- [X] I have verified the package to improve is located in this repository

### What do you want to add?

It would be nice if a start menu shortcut to rufus.exe were created during installation  

### If the feature or enhancement is approved:

- [X] I am willing to create a pull request to implement the feature or enhancement

### Additional Context

_No response_</div>

**Comment by TheCakeIsNaOH** [comment]
As indicated in the discussion, did you want to be assigned to this issue and create a PR to fix it, @mica
