### ISSUE TITLE
(autohotkey.install) Packages version 2.0.15, 2.0.16 and 2.0.17 are  failing verification

### ISSUE THREAD

**Issue by pauby** [chocolatey-community/chocolatey-packages#2491]
### Checklist

- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
- [X] I have verified that this is happening in the latest available version of the package.

### Chocolatey Version

2.3.0

### Chocolatey License

None

### Package Version

2.0.15 to 2.0.17

### Current Behaviour

Packages are failing Package Verifier.

Installing 2.0.17 it onto a VM showed this box.

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/20f2a503-cd02-4c17-bceb-97d7eb8d7fc3)

### Expected Behaviour

Packages pass Package Verifier.

### Steps To Reproduce

`choco install autohotkey.install --version 2.0.17`.

### Environment

```markdown
- Operating System: Windows 10
- PowerShell Version: 5.1
- Shell: Windows PowerShell
```

### Chocolatey Log

```shell
See the [gist for 2.0.17](https://gist.github.com/choco-bot/8b6298984b1b376f7d69b9e7ef2c6616).
```

**Comment by TheCakeIsNaOH** [comment]
Duplicate of #2472

**Comment by pauby** [comment]
I did search the repository for `autohotkey` before raising the issue and didn't get a result. I must have fat fingered it. Apologies.
