### ISSUE TITLE
(FortiClient VPN) Long awaited update

### ISSUE THREAD

**Issue by amber-m-mvd** [chocolatey-community/chocolatey-packages#2506]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

7.0.9.0493

### Download location

https://filestore.fortinet.com/forticlient/FortiClientSetup_7.0.9.0493_x64.zip

### Package Page

https://community.chocolatey.org/packages/forticlientvpn

**Comment by amber-m-mvd** [comment]
https://github.com/microsoft/winget-pkgs/issues/163137
https://github.com/microsoft/winget-pkgs/commit/4b258fe78e9f0ef1c2994c489ed869a04045bd33

**Comment by pauby** [comment]
This package is not maintained here. Please contact three package maintainer to encourage then to update.
