### ISSUE TITLE
python310

### ISSUE THREAD

**Issue by shawnfunke** [chocolatey-community/chocolatey-packages#2507]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

3.10.14

### Download location

https://www.python.org/ftp/python/3.10.14/Python-3.10.14.tgz

### Package Page

https://community.chocolatey.org/packages/python310

**Comment by TheCakeIsNaOH** [comment]
That is a `.tgz` file, not a windows executable. It looks like v3.10.x no longer has installers available for Windows. 
See https://github.com/chocolatey-community/chocolatey-packages/issues/2232
Closing as invalid.
