### ISSUE TITLE
(sysinternals) Unable to install sysinternals due to checksum error

### ISSUE THREAD

**Issue by cadnot** [chocolatey-community/chocolatey-packages#2509]
### Checklist

- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
- [X] I have verified that this is happening in the latest available version of the package.

### Chocolatey Version

2.3.0

### Chocolatey License

None

### Package Version

2024.6.20

### Current Behaviour

When trying to install sysinternals (without ignoring checksums), installation fails with checksum error:

![image](https://github.com/user-attachments/assets/4c3e626c-9cee-4c88-8e68-572a8caec940)

### Expected Behaviour

Should install without having to skip checksums.

### Steps To Reproduce

In powershell window, run "choco install sysinterals".

### Environment

```markdown
- Operating System: Win10 (Microsoft Windows NT 10.0.17763.0) and WinServer2022
- PowerShell Version: 5.1.17763.3770
- Shell:
```

### Chocolatey Log

```shell
https://gist.github.com/cadnot/7ffeeac4bcb499c5d218607560252502
```

### Anything else?

This was working on the morning of July 23rd 2024 and stopped working sometimes around mid-day EST. Could be related to the work done for the new version 2024.7.23.

**Comment by pauby** [comment]
Please see the note on the [package page](https://community.chocolatey.org/packages/sysinternals):

> This package supports only latest version.

Version 2024.6.20 is no longer supported, as 2024.7.23 has been released. I have tested and 2024.7.23 works.


The Sysinternals download location only has one version of the package (the latest). Trying to install an older version with Chocolatey CLI open-source, will not work. Licensed customers may be able to use the CDN.
