### ISSUE TITLE
(Thunderbird) outdated

### ISSUE THREAD

**Issue by chimmmpie** [chocolatey-community/chocolatey-packages#2515]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

128.1.0esr

### Download location

https://download.mozilla.org/?product=thunderbird-128.1.0esr-SSL&os=win64&lang=en-US

### Package Page

https://community.chocolatey.org/packages/thunderbird

**Comment by chimmmpie** [comment]
I am not sure if the current package Thunderbird should be updated. Or a new one should be created for the ESR releases. As the auto update of Thunderbird now goes to the 128 esr version i think that may be the best thing to update it. But i dislike the idea a bit somehow.

**Comment by TheCakeIsNaOH** [comment]
Issue has linked PR waiting for review, issue should remain open.

**Comment by zWhdmB5T** [comment]
Thank you guys!
