### ISSUE TITLE
(pdfcreator) Installation Fails on Domain Joined Computers using AHK script

### ISSUE THREAD

**Issue by lgreif** [chocolatey-community/chocolatey-packages#2518]
### Checklist

- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
- [X] I have verified that this is happening in the latest available version of the package.

### Chocolatey Version

2.3.0

### Chocolatey License

None

### Package Version

5.2.2

### Current Behaviour

When installing on domain joined computer, the chocolatey package attempts to use AutoHotkey to install the software.  AutoHotkey script was written in AHK V1.1 and does not run under AHK V2.0+.
![image](https://github.com/user-attachments/assets/daee93ce-fb24-4720-b465-a7fa33ad42bf)

### Expected Behaviour

AHK script should run and clock through the installer.

### Steps To Reproduce

1. On a **Domain Joined** windows 10 or 11 PC
2. Run `choco install pdfcreator`
3. AHK error will come up

### Environment

```markdown
- Operating System: Windows 10 x64
- PowerShell Version:
- Shell:
```

### Chocolatey Log

```shell
PDFCreator v5.2.2 (forced) [Approved]
PDFCreator package files install completed. Performing other installation steps.
The package PDFCreator wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

Print Spooler service state:  / Running
Print Spooler service new state: Auto / Running
WARNING: Silent install of PDFCreator is not supported on domain-joined systems like this one.
WARNING: Silent install will be attempted, but is less certain.
Installing PDFCreator...
```

**Comment by lgreif** [comment]
@karlo-mirkovic

**Comment by karlo-mirkovic** [comment]
Hello, 
In the Chocolatey Log, you can find the line:
"WARNING: Silent install of PDFCreator is not supported on domain-joined systems like this one."

In the docs, you can also find the following:
"Apart from several features, PDFCreator Free can not be installed silently on machines that are part of a Windows domain." 
Please see the [documentation](https://docs.pdfforge.org/pdfcreator/en/pdfcreator/frequently-asked-questions/is-pdfcreator-really-free/)

If you wish to install PDFCreator Free on a domain-joined system, the installation has to be interactive. 
To do this please use the [install command](https://docs.chocolatey.org/en-us/choco/commands/install/) along with the `--notsilent` or `--not-silent` options.

**Comment by lgreif** [comment]
Hi Karlo,
Thanks for your fast response!  I saw that note in the choco log, I was looking at the choco install script and noticed there was an autohotley script in there to click through the installer that only runs on domain joined computers, but it looks like this no longer works (for multiple reasons - AHK version and looks like installer has also changed to not allow AHK to click the buttons).
