### ISSUE TITLE
(keepass-langfiles) language files outdated

### ISSUE THREAD

**Issue by choc0-git** [chocolatey-community/chocolatey-packages#2527]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

2,57+

### Download location

https://keepass.info/translations.html

### Package Page

https://community.chocolatey.org/packages/keepass-langfiles

**Comment by choc0-git** [comment]
I have created the file `keepass_2.57_langfiles.zip`, but when I try to upload to `chocolatey-packages/manual/keepass-langfiles/tools/` it shows the error message:
> Uploads are disabled. File uploads require push access to this repository.

By the way: The regex search should be updated to `http**s**://downloads\.sourceforge\.net/keepass.+?2\..+?\.zip`.

**Comment by choc0-git** [comment]
I uploaded the file here: [https://file.io/cusNueIb2387](url)
Could someone with the permissions to do so, upload the file to `chocolatey-packages/manual/keepass-langfiles/tools/`.
Thanks.

**Comment by choc0-git** [comment]
@pauby @AdmiringWorm 
Did I do something wrong that I no longer get an answer?

**Comment by pauby** [comment]
You're asking us to update a package for you. But you haven't put in the effort to make the change yourself.

If the roles were reversed, what would you do?

**Comment by choc0-git** [comment]
I tried to, but I dont have the permission to upload. Do I need to request this permission? How can I do so? I really like to help, make the change and support, but without the permission I cannot.

**Comment by pauby** [comment]
As I mentioned in the last message, submit a pull request.

**Comment by choc0-git** [comment]
Could you please tell me how to do it? I dont find a pull request template and how to add the zip-file inside?

**Comment by choc0-git** [comment]
I figured out how to create a pull request:
[https://github.com/chocolatey-community/chocolatey-packages/pull/2533](url)

But how could I request it for a review?

**Comment by choc0-git** [comment]
> This is a [manually updated package](https://github.com/chocolatey-community/chocolatey-packages/tree/master/manual/keepass-langfiles).

@pauby While according to the [README.md](https://github.com/chocolatey-community/chocolatey-packages/blob/master/manual/keepass-langfiles/README.md) you should download the lngx files manually and create a zip file, it looks to me that in the [update.ps1](https://github.com/chocolatey-community/chocolatey-packages/blob/master/manual/keepass-langfiles/update.ps1) as if this is done with the script and the zip file does not have to be created separately.

Unfortunately, I am not a programmer and cannot find the error or read the logs. How can I get further support or where or who can I ask?

**Comment by pauby** [comment]
The best place to ask questions would be in the `#community-maintainers` channel in [Discord](https://ch0.co/community). Please note that this is community assistance and amend your expectations accordingly.

**Comment by choc0-git** [comment]
I tried my best to provide the updated language files, but could not complete the tests. Could anyone follow up on this, please:
[](https://github.com/chocolatey-community/chocolatey-packages/issues/2527)
[](﻿https://github.com/chocolatey-community/chocolatey-packages/pull/2534)
﻿
﻿I really dont want to create a third account to fix this on Discord.
