### ISSUE TITLE
(virtualbox) oudated

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-packages#2545]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

7.1.0

### Download location

https://download.virtualbox.org/virtualbox/7.1.0/VirtualBox-7.1.0-164728-Win.exe

### Package Page

https://community.chocolatey.org/packages/virtualbox

**Comment by TheCakeIsNaOH** [comment]
Looks like the updater script is broken as the extension pack changed download link format.

**Comment by Unrepentant-Atheist** [comment]
Still broken...needs an update!
