### ISSUE TITLE
(python) Outdated, build failing with null

### ISSUE THREAD

**Issue by JPRuskin** [chocolatey-community/chocolatey-packages#2555]
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

3.12.7, 3.11.10

**Comment by Dutcho** [comment]
additional to what @karig mentioned, also [Python 3.14.0a1 - Oct. 15, 2024](https://www.python.org/downloads/release/python-3140a1/) as (very early) prerelease

**Comment by chadlwilson** [comment]
it looks like the autoupdate bot is broken, as nothing seems to have updated since 13 Oct: https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f

**Comment by JPRuskin** [comment]
> it looks like the autoupdate bot is broken, as nothing seems to have updated since 13 Oct: https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f

Hm. The gist hasn't been updated on the readme, but I can see update activity in the commits. I'll have a look into that separately.

**Comment by JPRuskin** [comment]
As there's no template for this kind of issue in this repository (fun, making a note), I'll say here that there appears to be an issue with the json we're passing to GitHub, and I'm going to go discuss it / continue investigating it in Discord and/or the community mail group for now.

```
Running Gist
  ERROR:  
    {"message":"Problems parsing JSON","documentation_url":"https://docs.github.com/rest/gists/gists#update-a-gist","status":"400"}
```

WRT Node (again, completely the wrong place, but just to get you unblocked if you were looking for this, and I'll edit it out if I get the reports fixed):

```
   [125/243] nodejs ERROR: 
     Can't validate URL 
     Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.":https://nodejs.org/dist/v23.0.0/node-v23.0.0-x86.msi (19.01s)
```

**Comment by chadlwilson** [comment]
Thanks @JPRuskin thats helpful. Created #2556 which will hopefully unblock nodejs updates. Sorry for the distraction here. Back to Python!

**Comment by javbux** [comment]
Python 3.12.8 is now available (Dec 3rd)
https://www.python.org/downloads/release/python-3128/
Will you be able to get this working into the community repository?
