### ISSUE TITLE
(vlc) sending wrong files

### ISSUE THREAD

**Issue by tunisiano187** [chocolatey-community/chocolatey-packages#2580]
### Checklist

- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
- [X] I have verified that this is happening in the latest available version of the package.

### Chocolatey Version

2.4.0, 2.3.0, 2.2.2, Other (note in the comments)

### Chocolatey License

None

### Package Version

3.0.21

### Current Behaviour

The included files are update.ps1, screenshot.png and readme.md

### Expected Behaviour

No embedded files, only the nuspec

### Steps To Reproduce

See here : https://community.chocolatey.org/packages/vlc#files

### Environment

```markdown
- Operating System: all
- PowerShell Version: NA
- Shell: NA
```

### Chocolatey Log

```shell
NA
```

### Anything else?

No

**Comment by AdmiringWorm** [comment]
Closing this now as the PR has been merged. This will be fixed in the next version of the package.
