### ISSUE TITLE
(googlechrome) error 1722 at install

### ISSUE THREAD

**Issue by billy-stellar** [chocolatey-community/chocolatey-packages#2589]
### Checklist

- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
- [X] I have verified that this is happening in the latest available version of the package.

### Chocolatey Version

2.4.0

### Chocolatey License

None

### Package Version

131.0.6778.86

### Current Behaviour

Chrome fails to install with generic error 1722. Freshly downloaded googlechromestandaloneenterprisex64.msi worked as expected.

### Expected Behaviour

Chrome installs successfully

### Steps To Reproduce

1. Using Ansible, install Google Chrome via Chocolatey on Windows Server 2022, OR
1. In Windows Server 2022, install Google Chrome via Chocolatey

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.20348.0
- PowerShell Version: 5.1.20348.2849
- Shell:
```

### Chocolatey Log

```shell
https://gist.github.com/billy-stellar/52b1687b4a18f22dcc339ddaf8b51254
```

### Anything else?

Is this due to the version mismatch? A new version was released today. Using latest versions of Ansible AAP. This worked yesterday. Same issue and error code when running 'choco install googlechrome --ignore-checksums' interactively.

**Comment by kernel-sanders** [comment]
I am getting the same error on Windows 11 22H2 with chocolatey and googlechrome.

**Comment by kernel-sanders** [comment]
Also being reported in the comments of the package: http://disq.us/p/3189rfn

**Comment by billy-stellar** [comment]
I saw the same popup Girts mentions (on the Choco site) - I assume he's not talking about UAC, but Chrome pops up a window when uninstalling asking what to do with browser data. I don't see that when doing a fresh install (no Chrome installed) and getting the 1722 error.

This might be helpful: if I try to install Chrome using the .msi downloaded my Chocolatey, I get the same 1722 error! Is the download being corrupted in some way?
<img width="641" alt="image" src="https://github.com/user-attachments/assets/0ea1f9bc-3ee6-493d-9a9e-808f3f230f2c">

Checking the hashes, they're the same compared to one downloaded interactively. 

On Windows 10 22H2, I don't have any issue installing Chrome with Chocolatey. However, I do get a UAC prompt when using an Admin PowerShell. 

And for some juice... I think this is Google's issue/change. When I download interactively using the same URL in the Chocolatey script (https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi) I get the same 1722.

If I download using this URL (https://chromeenterprise.google/download/?platform=WIN64_MSI&channel=stable), I can install just fine! Comparing hashes, they **do not** match. That URL redirects to below. Can we test with that URL? I'm not sure if that will change with each version, however. 

Good URL, but might have too much info, like version:
https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7BA9905483-CFC9-3864-721B-7479F381002E%7D%26lang%3Den%26browser%3D5%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dtrue%26ap%3Dx64-stable-statsdef_0%26brand%3DGCOM/dl/chrome/install/googlechromestandaloneenterprise64.msi

The iid can be removed:
https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26lang%3Den%26browser%3D5%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dtrue%26ap%3Dx64-stable-statsdef_0%26brand%3DGCOM/dl/chrome/install/googlechromestandaloneenterprise64.msi

To reiterate, when I download using the URLs above, I can install the MSI. If I use the https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi URL, I get error 1722.

**Comment by billy-stellar** [comment]
@GraphicHealer do you have any insight on this issue, or ability to test with a different URL?

**Comment by GraphicHealer** [comment]
> @GraphicHealer do you have any insight on this issue, or ability to test with a different URL?

I am so sorry  but I am very confused. I have not touched Chocolatey in over a year... Lol

**Comment by dandunckelman** [comment]
Here's a related issue w/ a fix: https://issuetracker.google.com/issues/382108340#comment17

**Comment by billy-stellar** [comment]
> > @GraphicHealer do you have any insight on this issue, or ability to test with a different URL?
> 
> I am so sorry but I am very confused. I have not touched Chocolatey in over a year... Lol

haha sorry, I just saw that you had last modified the URLs. I don't have any experience creating and testing packages or I'd do a pull request. 

Thanks @dandunckelman

**Comment by billy-stellar** [comment]
Sorry for all the noise, everyone! Sounds like Google will be fixing it on Dec 10 and a fix is not needed here (unless we need a backup URL to download from if an error is detected 👀)
